### ISSUE TITLE
Improve the ZinZen svg

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#100]
Right now the ZinZen SVG is not very 'smooth'.
The red dots/arrows indicate areas that can be improved. Either because there is a sharp corner or a long straight line.
![image](https://user-images.githubusercontent.com/44887755/156722591-648c0f8f-70e7-4e6d-86c3-364877a0029c.png)

The original drawing by hand wasn't perfect, but in an SVG editor like Inkscape you can take out the rough lines.
![beca1fd656941577237718db8d1f5e283ea8c61f48133d94bdea76808301b924](https://user-images.githubusercontent.com/44887755/156722236-7694df48-6bbb-4a5c-b3ec-83176a2c8607.jpg)

Also the R circle should not be closed.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/156873207-f3cc7344-dbd1-4f66-b756-3ceb63ec9950.png)
Will this be okay?

**Comment by tijlleenders** [comment]
It's a lot better.
Still not there yet - but OK for now.
