### ISSUE TITLE
Database upgrade UI alternative

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1014]
**New approach:**  
Whenever a Dexie SchemaDiff is detected, make a popup that allows you to backup, then reset database.

**Original issue:**
The public groups works well for new users, but existing users get a database upgrade error. 

We've run into this before and I think we said we'd include upgrade code when this happens - or at least make a concious decision not to put effort into upgrade code unless we have enough users and database schema is stabilized enough.

![image](https://user-images.githubusercontent.com/44887755/218309255-f848355c-5bef-44bc-8dcc-c87f6c80e811.png)

**Comment by tijlleenders** [comment]
If we can detect the database upgrade error we can show a popup on every startup that notifies user they are using an outdated version and need to 'reset' - which will lose all their data.

Not optimal but at least honest.
User can choose to quickly write down the current goals... or maybe we can provide a db dump file.

Restoring data to new version will be manual for now the schema is changing too quickly to support this - and there are just a few users.

**Comment by tijlleenders** [comment]
@Tushar-4781 Detecting Dexie SchemaDiff is required to let some users upgrade to the new version.  
Even manually deleting goals doesn't work: 
![image](https://user-images.githubusercontent.com/44887755/227762617-3aa0faf0-2212-4b57-9840-83b4bedc4369.png)

New approach: Whenever a Dexie SchemaDiff is detected, make a popup that allows you to backup, then reset database.

**Comment by Tushar-4781** [comment]
@tijlleenders i think we are now upgrading the schema each time we have change in schema, i think we can close this ?

**Comment by tijlleenders** [comment]
@Tushar-4781 
Yes, if upgrades are smooth and transparent to user that is better!
