### ISSUE TITLE
Design config screen

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1025]
Drawer with config for scheduler related items.

**Comment by tijlleenders** [comment]
@mallikarai05 This is something we can start designing whenever you have time.

**Comment by mallikarai05** [comment]
@tijlleenders Can we have a quick call to discuss this?

**Comment by mallikarai05** [comment]
Hi!
@Tushar-4781 @tijlleenders I have added the first iteration of the designs on the figma board, please check those out.
