### ISSUE TITLE
Show free time in MyTime

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1026]
New version of scheduler is ready for this.

**Comment by tijlleenders** [comment]
@Tushar-4781 The new version of the scheduler is required for this.
If you're ready merge https://github.com/tijlleenders/ZinZen/pull/1027 to get the latest version.  

It'll break the app - but it's a necessary step towards integration.

**Comment by Tushar-4781** [comment]
Blocked by [#256](https://github.com/tijlleenders/ZinZen-scheduler/issues/256)
