### ISSUE TITLE
Rename today in MyTime

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1048]
Replace current title for today with name of the day and the day number:
- Saturday 25th
- Monday 1st
- Friday 22nd
(th/st/nd in superscript)

This should only apply to today.

Why?
Because this is relevant information for the user and helps to distinguish today from the other days. The month and year are not shown - as that makes it too crowded and easier to remember than the day number - at least for me.

![20230225_.jpg](https://user-images.githubusercontent.com/44887755/221340100-79f94545-3f89-4ea9-aafb-68ce769fa101.jpg)

**Comment by shubhamku044** [comment]
Hey, Can I take this issue?

**Comment by vinaybadgujar102** [comment]
I am working on it.

**Comment by tijlleenders** [comment]
Thanks @vinaybadgujar102 !

**Comment by tijlleenders** [comment]
Thanks @shubhamku044 !
