### ISSUE TITLE
Confirm new edit goal with enter

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1077]
Rewritten based on discussion below:

We've gone back an forth on this but a consistent behavior is better:  
- A keyboard 'Enter' on mobile or desktop browser should have the same effect.
- The effect should be the same as the 'action button' - in this case the 'create goal/budget' button. It should not only close the keyboard on mobile.

Agree with @vinaybadgujar102 we can add a test for this in Playwright.

**Comment by tijlleenders** [comment]
Somewhere along the way this feature disappeared. Please bring it back.  

Right now there is no enter on my keyboard when I edit the goal title, only a next which takes me to duration.

**Comment by vinaybadgujar102** [comment]
Should it work for both budget and goal entity?

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Good question!  
I think for budgets Enter shpuld close the keyboard only.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Enter is not working on mobile again. Tried on GrapheneOS using Vanadium. Not sure if it is also not working in other browsers.

**Comment by vinaybadgujar102** [comment]
@tijlleenders its not working for goals only, for budget "Enter" is closing the edit modal. Will fix it soon.

I think we should start writing unit tests for the majority of our feature implementations. This will help us ensure code stability and avoid breaking changes.

**Comment by tijlleenders** [comment]
Yes, although the UI hasn't been stabilized yet ... so we should balance the effort of (re)writing tests with catching regressions manually.

**Comment by tijlleenders** [comment]
First let's rationalize the testing framework in #1879

**Comment by tijlleenders** [comment]
> @vinaybadgujar102 Good question! I think for budgets Enter should close the keyboard only.

I retract this statement. A consistent behavior is better.
