### ISSUE TITLE
Improve edit menu

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1080]
The buttons of the edit menu should conform with theme ; so rounded with theme colors - not square.

Also, the currently selected one shpuld show differently.

![Screenshot_20230324e.jpg](https://user-images.githubusercontent.com/44887755/227436357-0030d7b6-f92f-4988-9a63-26689857e3e8.jpg)

**Comment by Tushar-4781** [comment]
This needs dark theme colors.
