### ISSUE TITLE
Adapt default goals for new scheduler API

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1087]
- Regroup all daily tasks under a "Daily habits  🔁" root goal that has a few budgets:  
  - "Breakfast 🥐🥣" betqeen 6-9 1-1h / day 7-7h / week every day
  - "Lunch 🥪" between 12-14 1-1h / day 7-7h / week every day
  - "Dinner 🍽️" between 18-20 1-1h / day 7-7h / week every day
  - "Me time 🧘🏽😌" between 5-23 1-1h / day 7-7h / week every day
  - "Walk🚶🏽" between 6-21 1-1h / day 7-7h / week every day

- Add a "Work 💪🏽" budget for 6-10h / day 40h/week weekdays.

- Add a "Family time 🥰" budget for 0-6h / day 10h/week every day.

- Add "House chores 🏡🧹🛠️ " as a 0-3h/day 0-3h/week budget with a weekend filter.

- Add "Hobby project 🚂🚋" as a 1-4h/day 1-4h/week budget every day.

- Schedule "Sleep 😴🌙" between 22-7 6-8h / day 42-52h/ week, every day

**Comment by Tushar-4781** [comment]
@tijlleenders no beforeTime for sleep ?

**Comment by tijlleenders** [comment]
@Tushar-4781 Before is needed for most people - as their job and family routine requires it. Let's say before 7?
