### ISSUE TITLE
Looking for a good in-memory database to integrate with the project

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#109]
The one used by the project, [LokiJS](https://github.com/techfort/LokiJS) has not been updated in a long time. Other popular persistent storage tools have dependencies on specific state management tools or frameworks (e.g., [redux-persist](https://www.npmjs.com/package/redux-persist)). We are looking for a good in-memory database with ReactJS support and the following functionalities -
- Persist on localStorage 
- Fast indexing and searching
- File and data restore

**Comment by tijlleenders** [comment]
The current function signatures of LokiJS are pretty simple and resemble what I would think an interface using Typescript would look like in the future (new collection(options); collectionName.insert(object); collectionName.update(object); collectionName.delete(object))...
Personally - unless there is a better candidate now - I would for start using LokiJS.
We can easily swap it out later.

**Comment by pulkitvyas08** [comment]
Okay let's just go for LokiJS and work on an API so things can be generalized and only the API would need to be fixed in case we ever need to migrate to some other database
