### ISSUE TITLE
Add sound effect to completing tasks

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1093]

**Comment by Tushar-4781** [comment]
@tijlleenders can you share the sound link that you have decided

**Comment by tijlleenders** [comment]
The current one is fine - if the license has no restrictions or obligations.

**Comment by Tushar-4781** [comment]
https://www.storyblocks.com/audio/search/done-sound-effect

**Comment by tijlleenders** [comment]
Just looking at the size of their Terms of service makes me dizzy.
This is a commercial company - so can't use their "royalty free" sounds - it requires a subscription.

**Comment by Tushar-4781** [comment]
@tijlleenders the sounds are coming from here https://pixabay.com/

**Comment by tijlleenders** [comment]
Sound Effect from <a href="https://pixabay.com/sound-effects/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=music&amp;utm_content=6316">Pixabay</a>
