### ISSUE TITLE
Update header component on roadmap

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1095]
We added text and indicator:
![image](https://user-images.githubusercontent.com/44887755/227763702-b7516192-e9af-4293-8389-cd169e0f7ebe.png)

@mallikarai05 This can be done in one place - then it updates all the pages, right?

**Comment by mallikarai05** [comment]
@tijlleenders we are adding a new component so it has to be done individually, I'll update this after completing the menu page!

**Comment by tijlleenders** [comment]
Supercedec by new design...
