### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#110]
The following can be added as templates - 
- Bug reports
- Proposals / Feature requests
- Questions
- Reporting other issues like documentation or security vulnerabilities

**Comment by pulkitvyas08** [comment]
Also, all issues should have labels

**Comment by tijlleenders** [comment]
The default labels should be a good start.
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels

**Comment by pulkitvyas08** [comment]
@tijlleenders I don't have the access rights to add issue templates. No `settings` tab available to me

**Comment by tijlleenders** [comment]
Ok, I checked and seems that there are no elevated privs available to delegate these rights.
The only option I have for a role when adding people to the project is "collaborator".

If you post the template.md for the issue types we need in this issue I'll add them.

**Comment by pulkitvyas08** [comment]
> Ok, I checked and seems that there are no elevated privs available to delegate these rights. The only option I have for a role when adding people to the project is "collaborator".
> 
> If you post the template.md for the issue types we need in this issue I'll add them.

Looks like GitHub updated their default issue templates since the last time I checked. Those are pretty descriptive and quick to implement. I think they will serve the purpose here. If there is any particular thing that needs to be changed then let me know and I'll add it but FWIW, this can be closed

**Comment by tijlleenders** [comment]
@pulkitvyas08 Does something have to be done to close this issue?
If not, please close.

**Comment by pulkitvyas08** [comment]
> @pulkitvyas08 Does something have to be done to close this issue? If not, please close.

Upto you. If you think we would benefit from adding issue templates then please add them and close the issue or if you see them as something that would slow down the process of quickly adding new issues then we don't need to do anything and the issue can be closed
