### ISSUE TITLE
Change forget sound

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1108]
@Tushar-4781 
I've been using the forget and I think we need a different sound. The current one sounds like I have done something wrong...

I would like it to sound more like *swoosh* wind that blows the task away.
If you prefer I'll try finding something that fits better.

**Comment by Tushar-4781** [comment]
@tijlleenders sure, that would be a great help

**Comment by tijlleenders** [comment]
@Tushar-4781 
Sound Effect from <a href="https://pixabay.com/sound-effects/whoosh-6316/">Pixabay whoosh-6316</a>
