### ISSUE TITLE
Don't show inbox if it's empty

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1112]

**Comment by tijlleenders** [comment]
Ha!
Like the suggestionbinstead of hiding it.

@Tushar-4781 
What if I already have friends but my inbox is empty - will I still see 'inbox' and this message when I click?

**Comment by Tushar-4781** [comment]
@tijlleenders , good catch. i think i should peek into your contact first. if they exist "Your current friends haven't shared any of their goals with you"

**Comment by tijlleenders** [comment]
Yeah that works - but if I already know I have friends and an inbox - why clutter the screen with the inbox button when it is empty?

**Comment by Tushar-4781** [comment]
i think its important because this tells you about the feature which you can try with others. Indirectly this also pushes them to try out the share feature.

**Comment by tijlleenders** [comment]
Ok we go with that then!

**Comment by tijlleenders** [comment]
Yes - I agree with that.

I'm just asking to hide it when you already have loads of friends and are using inbox daily - but it just happens to be empty.

**Comment by tijlleenders** [comment]
@Tushar-4781 
I've been using this in current setting for a while and really want the inbox to disappear from the screen if there's nothing in it.

I keep pressing it just because it's there and then it reminds me I should get friends - a notification that also is not dismissable while it stays on screen for an eternal lasting three seconds.

Just remove it when empty please!

If we want to encourage anything we should encourage sharing - not getting other people to share with us.

I also thought we might add the Inbox like a top goal - renaming it to 'Clear inbox' by clearing the subGoals of incoming messages.

**Comment by tijlleenders** [comment]
![Screenshot_20230412.jpg](https://user-images.githubusercontent.com/44887755/231579713-c05fd4b7-bb95-4591-a11b-dd03103748db.jpg)
