### ISSUE TITLE
Remove notification code

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1125]
I'm getting prompted about notifications in dev. I don't want to get prompted. 

Please remove any code that triggers notification logic in the browser. If none left and I'm working with a cached older version issue can be closed immediately.

![Screenshot_20230410_085708_Chrome.jpg](https://user-images.githubusercontent.com/44887755/230845822-a979d52f-3866-4de9-bc3c-0824dffce427.jpg)

**Comment by Tushar-4781** [comment]
The notification code has already been removed in #1124, you are getting this error because the installed app has the notification code and it is responding to the last merge as soon as the new code is fetched via upgrade now, you won't see the notification in any incoming upgrades.

**Comment by Tushar-4781** [comment]
The notification code has already been removed in #1124, you are getting this error because the installed app has the notification code and it is responding to the last merge as soon as the new code is fetched via upgrade now, you won't see the notification in any incoming upgrades.
