### ISSUE TITLE
Show minutes on calendar as superscript

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1141]
Right now the calendar time is shown as a long blob of text which is hard to read.

Example: "0:00-08:00"

It would be better to:
- remove any leading 0's ; so 08:00 => 8:00
- move the minute portion to superscript position ; so 8:00 => 800 (where 00 is in superscript)

**Comment by tijlleenders** [comment]
![signal-2023-04-15-08-48-13-630.png](https://user-images.githubusercontent.com/44887755/232249918-0563d395-5052-4aee-891d-60ba6311b381.png)

**Comment by Shahzaib-Iqbal-1057** [comment]
Hey! this issue is from April, you still require work on it? I can change the way the time looks if you want. Thanks!

**Comment by tijlleenders** [comment]
@Shahzaib-Iqbal-1057 Sure take it away!

**Comment by tijlleenders** [comment]
> ![signal-2023-04-15-08-48-13-630.png](https://user-images.githubusercontent.com/44887755/232249918-0563d395-5052-4aee-891d-60ba6311b381.png)
> 
> 

@Shahzaib-Iqbal-1057 
Thanks for the PR!

I agree with you the current suoerscript doesn't look good. Is there a way for you to make the top align with the top of the hour digit - and the bottom with the middle - like above example?

**Comment by Shahzaib-Iqbal-1057** [comment]
sure!

**Comment by Shahzaib-Iqbal-1057** [comment]
Hey! I have changed the MyTimeLine.scss file as you can see in the second commit. I have introduced two new css properties for the superscript text.
-vertical-align : I used this property for alignment.
-Font-size : I changed the font-size a bit to make the superscript a little smaller, you can change it further as you like if you want to.

**Comment by Shahzaib-Iqbal-1057** [comment]
Update : 
-I changed the vertical-align property to "20%" from "text-top" now you can change the alignment yourself as well if you want to. 0% makes the superscript text to be at the bottom while 100% makes the text higher from the normal text.
