### ISSUE TITLE
Design a habit tracker

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1145]
For any goal that is a habit, keep track of the days its task was marked as done. Show that in a GitHub style overview ![279733084-720e5f26-8883-4888-8ad1-7b020e8defa3](https://github.com/tijlleenders/ZinZen/assets/44887755/8236b612-99f2-4e2d-96d8-29deb4e39893)

Where would we see/access this?

**Comment by vinaybadgujar102** [comment]
@tijlleenders I've come up with two potential designs: Calender Style and GH Style.

![Screenshot from 2023-10-27 13-40-05](https://github.com/tijlleenders/ZinZen/assets/90821253/8906049f-276b-490e-80cf-7df8d77fb49f)

**Comment by tijlleenders** [comment]
Very nice @vinaybadgujar102 

I prefer a more circle-focused than square approach. It fits better with overall 'natural' design language.  

I don't think the overall average is useful. You should be able to forget the past. A better approach is to take the average of the last three weeks. And whether your last attempt was increasing, decreasing or keeping the average stable (arrow up, down or sideways).

**Comment by vinaybadgujar102** [comment]
> I don't think the overall average is useful. You should be able to forget the past. 

@tijlleenders Can you elaborate more on this.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 If you ever did poorly you can never get the satisfaction of climbing to 100%.  I don't want to be 'punished/reminded' of my previous bad performance - but want to focus on the now and past three weeks.  
S9 don't show me my lifetime completion rate, but only the average of last three weeks.

**Comment by vinaybadgujar102** [comment]
@tijlleenders  Updated the design based on given feedback. 
We can tackle the "Completion Rate" thing while implementing this design.
![iPhone 14   15 Pro - 1](https://github.com/tijlleenders/ZinZen/assets/90821253/50bbaf02-5878-45b7-9450-d2b6d1353c05)

**Comment by tijlleenders** [comment]
Great!  

There is a lot of small text.  
Can we try to reduce this?  

For example show a bigger number with small subtext could be sufficient to convey the same information:
- 8x in a row (flame when beating record)
- 30x total
- 30% last 3 weeks (up/sideways/down arrow)

**Comment by vinaybadgujar102** [comment]
Updated Design
![iPhone 14   15 Pro - 1(3)](https://github.com/tijlleenders/ZinZen/assets/90821253/720e5f26-8883-4888-8ad1-7b020e8defa3)

**Comment by tijlleenders** [comment]
Initial design is completed, thanks @vinaybadgujar102 !
I'll make a separate issue for making this.
