### ISSUE TITLE
Keep timeline when expanding day

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1148]
Currently the timeline disappears when expanding a day on the schedule page. Since there is no transition to the Task dots or a  vertical timeline you 'lose' the overview of the day.

Instead of a vertical timeline or complicated transition let's try a first step of just keeping the timeline visible when expanding the day.

![Screenshot_20230417b.jpg](https://user-images.githubusercontent.com/44887755/232374359-dae20214-8b4a-4bef-91b1-2ed3801321df.jpg)

**Comment by vinaybadgujar102** [comment]
I would like to work on this issue.

**Comment by tijlleenders** [comment]
That is great news @vinaybadgujar102 !

The UI is currently under heavy reconstruction by @Tushar-4781 in https://github.com/tijlleenders/ZinZen/pull/1153
@Tushar-4781 Can @vinaybadgujar102 use main or add to the current PR?
If not is there a similar contribution that is required?

**Comment by tijlleenders** [comment]
@Tushar-4781

**Comment by Tushar-4781** [comment]
Hey @tijlleenders , yes this issue is open now. @vinaybadgujar102 you can give it a shot. Green signal from my side.

**Comment by vinaybadgujar102** [comment]
Thank you for the confirmation, @tijlleenders, and @Tushar-4781. I'll get started working on this issue and will let you all know if I have any questions or need any assistance.
