### ISSUE TITLE
Use tags as the edit menu

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1149]
Currently it is not visible which constraints are in use for a goal.

The selector on the left should indicate visually if it is being used or not.

![Screenshot_20230417c.jpg](https://user-images.githubusercontent.com/44887755/232375237-dd282609-2f78-4620-8f96-c1dee141d15b.jpg)

**Comment by mallikarai05** [comment]
@tijlleenders @Tushar-4781 I think having a small circle on the constraints which are in use for a goal is easily understandable.
Will need your opinion on this
![Add filter](https://user-images.githubusercontent.com/73054648/233830991-bc46a260-dfe2-40ac-a9b9-e44c70a0383a.png)

**Comment by tijlleenders** [comment]
The dots suggeat you have to do something (notification). That is not what we want to convey right?

**Comment by tijlleenders** [comment]
mm/dd/yyyy => "Choose date" ?

**Comment by tijlleenders** [comment]
Order of items should be from most used at to to least used at bottom no?

I guess duration and due date are at the top?

**Comment by mallikarai05** [comment]
> Order of items should be from most used at to to least used at bottom no?
> 
> I guess duration and due date are at the top?

Tushar mentioned this is the order you both agreed on, I feel start and due date should be on top, what would you both suggest?
@tijlleenders @Tushar-4781

**Comment by mallikarai05** [comment]
> The dots suggeat you have to do something (notification). That is not what we want to convey right?

![Edit start date](https://user-images.githubusercontent.com/73054648/233905999-62fc1c8a-88c3-4fd6-ac2f-a752ba9e0f08.png)

How would this look?

**Comment by tijlleenders** [comment]
Don't think that's intuitive either.
What does underline mean?

**Comment by tijlleenders** [comment]
@mallikarai05 How about we just remove the menu on the left and add all tags.  
When they are not being used they will be greyed out. Clicking on a tag will open the corresponding menu. 

It will crowd the tags area a bit - but I think it is more intuitive. Can you make a sample?

**Comment by tijlleenders** [comment]
Replaced by natural language interface #1362
