### ISSUE TITLE
My time page takes too long to load - and is not possible offline

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1157]
**Describe the bug**
The loading of the MyTime page takes too long. It is contrary to the design guidelines (<100ms).
Every time I switch to the scheduler page there is a blocking network call to get the wasm.
This probably also blocks the whole page in flight mode.

**To Reproduce**
1. Go to My Goals page
2. Go to My Time page
3. Check how long it takes to load the MyTime page

**Expected behavior**
The wasm should be in cache - and loaded once unless there is a new version (stale while revalidate).
Using the cached version will not block the page load (I think).

**Screenshots**
<img width="496" alt="image" src="https://user-images.githubusercontent.com/44887755/235265457-f07c084c-a23c-484a-b9cf-4c74ff56c0da.png">

**Comment by Tushar-4781** [comment]
@tijlleenders try again. lemme know after first boot does it take time or not. the primary reason could be the .wasm file after first boot its cached so i think it will be faster after initial boot.

**Comment by Tushar-4781** [comment]
Scheduler works offline as .wasm file is cached as well. Resolved by #1234
