### ISSUE TITLE
Invite link doesn't include relationship id

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1160]
**Describe the bug**
When sharing a goal you get a "Share invitation" button that is supposed to include a link to a relationship id. It doesn't.

It just has this : zinzen.me/invite/

**To Reproduce**
See above.

**Expected behavior**
Add the rel id to the link.

**Comment by Tushar-4781** [comment]
@tijlleenders try pushing the latest build on prod. It's working

**Comment by tijlleenders** [comment]
Resolved by #1200
