### ISSUE TITLE
Back button on inbox causes footer menu to multiselect

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1164]
**Describe the bug**
When inside the inbox I expect the back button to take me out again - and everything remains normal

**To Reproduce**
1. Go to inbox
2. Press back button
3. See two buttons selected at the same time on the footer menu 

**Expected behavior**
Go to the last page that was visible before pressing on Inbox icon.

**Screenshots**
<img width="230" alt="image" src="https://user-images.githubusercontent.com/44887755/235575372-67fd5915-b910-48d0-86a5-41082573e1fc.png">

**Comment by Tushar-4781** [comment]
Resolved by #1225
