### ISSUE TITLE
Replace Today/This week with This week/Next week

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1168]
**Is your feature request related to a problem? Please describe.**
I don't see the value in having a Today if Today is also included in This week.

**Describe the solution you'd like**
Replace Today/This week by This week/Next week.

**Additional context**
My Time page:
<img width="221" alt="image" src="https://user-images.githubusercontent.com/44887755/235811156-790504d7-47bb-4da8-baa4-40a08dcd2a84.png">
vs
<img width="218" alt="image" src="https://user-images.githubusercontent.com/44887755/235811181-b2ec9fdc-913d-4da1-b677-0d4660d898d9.png">

**Comment by alshareef49** [comment]
Hi, I am interested in working on this issue. Can I take this up?

**Comment by tijlleenders** [comment]
Resolved by #1671
