### ISSUE TITLE
Add more gradients to light theme

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1169]
**Is your feature request related to a problem? Please describe.**
I'd like a light blue/dark orange theme. My partner would like a light green gradient.

**Describe the solution you'd like**
Add more color gradients to the light theme selector.

**Comment by i-AmanRawat** [comment]
hey @tijlleenders, can I work on this?

1- I will have to add some more css class for adding themes for both dark and light mode.
2- Also I need to make some changes into themeChange() function to make theme switching possible
This one is just for example : 

.light-theme10 {
  --app-background: linear-gradient(180deg, #32b0ff 0%, #bfb8e0 100%);
  --primary-background: #9786de;
  --secondary-background: #6382af;
  --header-color: #1f4055;
  --bottom-nav-color: #2f1a8d;
  --selection-color: #3F3D47;
  --default-border-color: #1d7f7f;
  --modal-bg-color: #22455c;
}

also shall I make themes as per my choices or do you have some themes gradients selected?

**Comment by tijlleenders** [comment]
This is a question for @Tushar-4781 

As for the themes I can't guarantee your creation will pass the group vote... but you can always propose.  

Personally I think as long as there are no objections from a UX perspective... it should be OK. 

We are all different - so more choice is better?

**Comment by i-AmanRawat** [comment]
<img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/94544552/236529589-129d2ef8-641d-4e14-83cf-95cf3a7c7db8.png">

@tijlleenders see

**Comment by tijlleenders** [comment]
@i-AmanRawat I can see these being part of the stock themes, thanks!

**Comment by Tushar-4781** [comment]
The orange gradient is already in use. So no point of including that with slight modifications. 
I like your green gradient but the drop-down color, bottom nav, fpa are not complementing your gradient.

**Comment by tijlleenders** [comment]
Maybe you can add a light blue theme in place of the orange? I'd really like one from light blue to a little orang/red-ish... like a sunset.
![St_20230506_Chrome.jpg](https://user-images.githubusercontent.com/44887755/236598545-efe22907-cd8d-4f3a-b1a3-060d96daaeaf.jpg)

**Comment by Tushar-4781** [comment]
> Maybe you can add a light blue theme in place of the orange? I'd really like one from light blue to a little orang/red-ish... like a sunset. ![St_20230506_Chrome.jpg](https://user-images.githubusercontent.com/44887755/236598545-efe22907-cd8d-4f3a-b1a3-060d96daaeaf.jpg)

i won't stop you but it will not work out like we want, however if you are so much into the gradients we can think of a feature where you can set you own color themes, all you have to do is select these colors:
--app-background
--primary-background
--secondary-background
--header-color
--bottom-nav-color 
--selection-color
--default-border-color
--modal-bg-color

there are  some websites i have in mind that gives us gradient colors in bulk so its like we will give you list of colors for each variable from which you can choose as per your convenience. And make your own theme :D

**Comment by Tushar-4781** [comment]
but i suggest let's get some users first, you can't release all these creative stuff in current situation which is 3-4 users. otherwise later we won't have anything new.

**Comment by tijlleenders** [comment]
@Tushar-4781 Agree that working on this is not a priority right now - that's why I added the 'low prio' task.  

A customization option for theme would be nice. There's also algorithms that will pick a color acheme based on an image you upload. The first step would be to design the screens and logic on paper.  

But like you said - we can't spend time on this right now. If the green theme can be merged then that's good - if it requires more work we'll have to pause this and pick it up at a layer point in time.

**Comment by i-AmanRawat** [comment]
<img width="1440" alt="screenshot02" src="https://user-images.githubusercontent.com/94544552/236641063-15337b5e-ee14-4ff0-bf15-b25e38b59a6d.png">
<img width="1440" alt="screenshot04" src="https://user-images.githubusercontent.com/94544552/236641071-332037ab-6252-41c6-99e4-af5fbcf4eb76.png">
<img width="1440" alt="screenshot01" src="https://user-images.githubusercontent.com/94544552/236641086-73272f8a-04a9-4aaf-8e48-e2b3e1020fa8.png">

@Tushar-4781 @tijlleenders have a look !

**Comment by tijlleenders** [comment]
Superceded by #1494
