### ISSUE TITLE
Increase touch area for checkbox

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1174]
**Is your feature request related to a problem? Please describe.**
It's very annoying to have to aim at a small part of the screen to tick a checkbox.

**Describe the solution you'd like**
Increase the tap area for the checkbox like so:  
<img width="306" alt="image" src="https://user-images.githubusercontent.com/44887755/235822209-2de386f5-241a-4b72-8478-c1c82e8938b5.png">

**Describe alternatives you've considered**
None.

**Additional context**
This kind of checkboxes are used in multiple places.  
All of them need to be improved.

**Comment by vinaybadgujar102** [comment]
Can you please assign this issue to me?  Thanks : )

**Comment by vinaybadgujar102** [comment]
Can you please assign this issue to me?

**Comment by vinaybadgujar102** [comment]
#1214

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Great news!
