### ISSUE TITLE
Every issue added to the ZinZen repo should automatically be assigned to this project

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#118]
Not only should every new issue be assigned to the project, it should also be of status "Backlog"

**Comment by pulkitvyas08** [comment]
@tijlleenders I have setup the project board workflow (to add new issues added on the project to the `Backlog` status) and added a CI workflow (to add new issues to the `ZinZen project board` project). The issue that the CI workflow is facing right now is the lack of required permissions. 

Basically, you would need to add a `PAT` with `repo` and `admin:org` scope, add it to `secrets`, and provide that token to this CI workflow. If you could create that secret then I would do the subsequent steps. The required steps have been documented at https://github.com/peter-evans/create-or-update-project-card#create-a-card-in-an-organization-or-user-project

**Comment by tijlleenders** [comment]
**Added ADD_ISSUE_TO_PROJECT_PAT secret to ZinZen repo GitHub Actions secrets.**

A little bummed the control on PATs is not very granular.
This makes the security best practice of 'least privilige' a lot harder.

Seems this is not a priority for GitHub: https://github.com/github/roadmap/issues/184

I've now scoped it to:
- repo:public_repo = "Access public repositories"
- admin:org = "Full control of orgs and teams, read and write org projects"

Hopefully that'll work.

**Comment by pulkitvyas08** [comment]
Agreed. I have a GH enterprise account and things are the same over there too. Apart from using some other DVCS platform or deploying your own implementation, there's not much to do. Anyway thanks for the prompt response, I'll add the token to the workflow

**Comment by tijlleenders** [comment]
Creating new issues lead to failed workflow run: https://github.com/tijlleenders/ZinZen/actions/runs/2023881021

**Comment by pulkitvyas08** [comment]
Yes, looking for the issue. Will be done soon hopefully

**Comment by tijlleenders** [comment]
Done.

**Comment by pulkitvyas08** [comment]
@tijlleenders I'm getting this error on the workflow run 

![image](https://user-images.githubusercontent.com/54947769/161691561-b607d069-4075-4251-9795-552efc5a3bf4.png)

The token showing up as `token: ***` indicates that the token either doesn't exist or cannot be found by the repo. Can you look into it? And maybe create a token with all possible rights and we can try using that to see if this is related to authorization

**Comment by tijlleenders** [comment]
Tried playing with the yaml format.
Tried increasing the scope of the token.
Tried using a repository project instead of a user project.
So this is the new workflow file:
```
on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: 1
          column-name: Backlog
          issue-number: ${{ github.event.issue.number }}
```
Somehow it is still showing the token: ** even though I removed it in the invocation...
![image](https://user-images.githubusercontent.com/44887755/161826095-0d68950c-9ee7-42aa-be37-b1e134520ad7.png)

Added debug logging to action workflow by setting ACTIONS_RUNNER_DEBUG secret to true and downloading log archive.
Found this in runner-diagnostic-logs folder:
```
[2022-04-05 18:26:17Z INFO ProcessInvokerWrapper] Process started with process id 1523, waiting for process exit.
[2022-04-05 18:26:17Z INFO JobServerQueue] Try to upload 1 log files or attachments, success rate: 1/1.
[2022-04-05 18:26:17Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2022-04-05 18:26:17Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2022-04-05 18:26:17Z INFO ProcessInvokerWrapper] Finished process 1523 with exit code 1, and elapsed time 00:00:00.4126040.
[2022-04-05 18:26:17Z INFO CreateStepSummaryCommand] Step Summary is disabled; skipping attachment upload
[2022-04-05 18:26:17Z INFO StepsRunner] Step result: Failed
[2022-04-05 18:26:17Z INFO ExecutionContext] Publish step telemetry for current step {
  "action": "peter-evans/create-or-update-project-card",
  "ref": "v2",
  "type": "node16",
  "stage": "Main",
  "stepId": "745e91ee-9815-5c93-c9b0-e2d032c829c4",
  "hasPreStep": false,
  "hasPostStep": false,
  "result": "failed",
  "errorMessages": [],
  "executionTimeInSeconds": 1
}.
```
Since there is no clear error message I'm giving up.
Logging an issue with the maintainer of the project to let him know of our troubles.

**Comment by tijlleenders** [comment]
After some help from [Peter Evans](https://github.com/peter-evans) I realized I was not using the right debugging flag.  
To get debugging on actions I should add a repo secret ```ACTIONS_STEP_DEBUG``` set to ```true``` - not ```ACTIONS_RUNNER_DEBUG```.  

I'm leaving it on as it might be helpful in the future to debug Actions.  

Anyway, that led me to the typo ```project-name: 1``` => ```project-number: 1```  
Adding an issue works fine for the project defined on the repo.  
When switching to the project defined on the user it fails to retrieve the project list:  
```##[debug]RequestError [HttpError]: Not Found
##[debug]    at /home/runner/work/_actions/peter-evans/create-or-update-project-card/v2/dist/index.js:4041:23```  

I increased the scope to maximum permissions. That didn't help. So it's not a permissions thing.  
Will investigate further later.

**Comment by tijlleenders** [comment]
Using a BETA project seems to be problematic.
I created a normal project.

Only the normal project shows up in the GET result on 'https://api.github.com/users/tijlleenders/projects'.

**Conclusion:**
Don't use this action for a BETA project belonging to a user. *

*As long as GitHub API does not show it in the GET result on 'https://api.github.com/users/INSERT_USER_HERE/projects' even though the project is set to visibility public.  
  
  
Also, as long as we don't use a repo-scoped project - excessively scope PAT is required. :(

**Comment by tijlleenders** [comment]
Auto-assigning to the project makes them go to the top of the Backlog column automatically.  
This is not OK since then they become highest priority automatically.  

Using the [new project board](https://github.com/users/tijlleenders/projects/2) it is actually quite easy to drag any new/open issues to the Backlog as an explicit choice. That way they also land at the right initial priority.  

**Removed the action workflow and the tokens.**
