### ISSUE TITLE
Rename 'Archive' to 'Done'

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1181]
**Describe the bug**
When I mark something as 'done' it goes to the 'Archive' section on the screen.  
It makes more sense something would go to 'Done'. It also feels more satisfying to look at your 'Done' list than at your 'Archive' list.  
Details ... that count. Thanks @alpeshl for mentioning it!

**To Reproduce**
1. Go to a Goal
2. Click on 'Done'
3. Scroll down to section 'Archive'
4. Introspect and realize it would be nicer if 'Archive' was called 'Done'

**Expected behavior**
'Archive' section is called 'Done' in UI, **and** in code.

**Screenshots**
<img width="217" alt="image" src="https://user-images.githubusercontent.com/44887755/236065047-cb91c0db-fc54-40d9-8353-86b9911dcd73.png">

**Comment by Tushar-4781** [comment]
@tijlleenders this issue is already done i guess ?

**Comment by tijlleenders** [comment]
Looks like it!
