### ISSUE TITLE
Replace footer menu sub-text for Calendar

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1182]
**Is your feature request related to a problem? Please describe.**
The sub-text for footer menu option Calendar doesn't provide a good enough expectation.  
We thought it was a good idea to show 'May 5th' below the calendar icon - but actually it doesn't intuitively indicate what whill happen when you press the button.

**Describe the solution you'd like**
Rename sub-text for Calendar icon to 'Schedule'.

**Describe alternatives you've considered**
Rename it to Calendar. It is longer and less accurately describes what the page is about.

**Additional context**
<img width="226" alt="image" src="https://user-images.githubusercontent.com/44887755/236083805-2eae44dd-54b5-4b97-ab03-1ffb0aff1470.png">

**Comment by Tushar-4781** [comment]
let's name is schedule

**Comment by tijlleenders** [comment]
@Tushar-4781 Yes - agree 'Schedule' is better than 'Actions'.  
In my mind Actions would make sense - but for other people this is 'undefined'. :)  
'Schedule' has very little chance of misinterpretation. I edited the issue description accordingly.

**Comment by tijlleenders** [comment]
Welcome @i-AmanRawat !  
Very happy to receive the contribution :) Let us know if you have questions.
