### ISSUE TITLE
Add link to blog in menu dropdown.

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1187]
**Is your feature request related to a problem? Please describe.**
The link to blog.zinzen.me has disappeared.  

**Describe the solution you'd like**
Please add it after 'Feedback' and before 'Change theme'.   
<img width="210" alt="image" src="https://user-images.githubusercontent.com/44887755/236372551-3efd3a43-ae9d-45e6-b26c-d7e1089deb21.png">

**Describe alternatives you've considered**
None.

**Comment by vinaybadgujar102** [comment]
I can work on it

**Comment by tijlleenders** [comment]
The link should open similar to the Donate page.
