### ISSUE TITLE
Minimize friction confirmation popup

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1190]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you press a button to do something and you get a bunch of text to read before being able to do/get the 'simple thing' you just asked for.

**Describe the solution you'd like**
Confirmation modal should highlight the most logical choice, and place it on the right side (based on the fact that a larger portion of us are right-handed).
<img width="307" alt="image" src="https://user-images.githubusercontent.com/44887755/236583896-3e38d0ac-ae62-480f-ae51-a1933e83d5d4.png">

**Describe alternatives you've considered**
None.

**Additional context**
Here's how that looks for some other screen:  
<img width="197" alt="image" src="https://user-images.githubusercontent.com/44887755/236584017-1f5dfac8-45c8-46b7-8ed2-58b6ac412d83.png">  
So to make it consistent the highlight in light theme should be this style:  
<img width="82" alt="image" src="https://user-images.githubusercontent.com/44887755/236584070-7ee60d24-4365-4332-91aa-bc5a54a67c63.png">

<img width="338" alt="image" src="https://user-images.githubusercontent.com/44887755/236584105-1ef265c8-1f7b-41a5-8c3f-86d1049162c6.png">

**Comment by Tushar-4781** [comment]
@tijlleenders this can be close now right ?

**Comment by tijlleenders** [comment]
@Tushar-4781 
#1295 Covers 95% of what I mentioned.
I guess we can make the UI overall consistent when a designer takes a look at it.
