### ISSUE TITLE
Use accordion mode for onboarding panel

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1192]
**Is your feature request related to a problem? Please describe.**
It's very annoying when I want to read an intro text on the onboarding screen and the panel expands 'off screen'.
<img width="295" alt="image" src="https://user-images.githubusercontent.com/44887755/236587357-a88ced0b-16cc-4982-aa6e-0f8688cb5d54.png">

**Describe the solution you'd like**
Use [accordion mode](https://ant.design/components/collapse#components-collapse-demo-accordion) for the panel.

**Describe alternatives you've considered**
None.

**Additional context**
I believe antd is used even though we used bootstrap before - but haven't checked.

**Comment by giri-madhan** [comment]
Hi @tijlleenders , Could I work on this issue?
