### ISSUE TITLE
Make the design for custom/suggested new emotion

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#120]
There can be all kinds of combinations:  
Which label?  
Permanent option or one-off?  
...  
but for now just keep it simple: type and it will save without a category.

Sometimes you want to log something like feeling like a Marvel character.
Example: "I feel like a terrible green Hulk right now!!!!"
"I feel Captain America today".

**Comment by tijlleenders** [comment]
Might also be related to adding context to a registry - more Diary like "this was when my friend told me about abc..."

**Comment by mallikarai05** [comment]
As discussed in the meeting, the quickest way is to add a feeling for the day (without a category) for now. Are there any changes required in the design? or I can start with the mobile design 
![image](https://user-images.githubusercontent.com/73054648/163321089-7126c6bd-dc2c-41f7-8868-5738eecb36bd.png)
![image](https://user-images.githubusercontent.com/73054648/163321165-1fa9c840-4fa6-49d6-a1c0-f846e192722b.png)

**Comment by tijlleenders** [comment]
Looks good!
I believe we should design for mobile first (or only) - then desktop.

**Comment by mallikarai05** [comment]
The designs for the mobile view
![image](https://user-images.githubusercontent.com/73054648/163533404-90a36dd4-71c2-4891-b734-aa7b9654316c.png)
![image](https://user-images.githubusercontent.com/73054648/163533423-ee26c6b5-cef0-4318-8ed4-e8842785c18a.png)

**Comment by tijlleenders** [comment]
Looks great!
Can we change the wording to "Add a custom feeling!" ?

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/163541861-0d353e0b-0cdf-4b15-bacc-a5ce7a453193.png)
