### ISSUE TITLE
Add backup-restore in menu

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1207]
**Is your feature request related to a problem? Please describe.**
It's very annoying when I can't backup.  
It makes me stressed that I'll lose something - and I depend on ZinZen to work.

**Describe the solution you'd like**
I want to have a fallback I can rely on - like a file in JSON that I can use to switch to some other tool.

**Describe alternatives you've considered**
None.

**Additional context**
It was present - so it's just a matter of adding it back.

**Comment by Tushar-4781** [comment]
Blocked by #1163 
The backup restore is using react-bootstrap modal and it has to be re-developed as per new theme. This issue will be resolved in #1163
