### ISSUE TITLE
Print input JSON to console

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1211]
**Is your feature request related to a problem? Please describe.**
It's very annoying when we have to write test cases for the scheduler by hand.

**Describe the solution you'd like**
I can use the UI to configure a test case, then use the browser console to print the raw input JSON for copy/pasting.

**Describe alternatives you've considered**
None. Duplicating this logic somewhere else would not be a good idea.

**Additional context**
Idea for this functionality came from #310.

**Comment by Tushar-4781** [comment]
Resolved in #1212
