### ISSUE TITLE
Styling edit screen in dark mode

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1226]
**Describe the bug**
The edit screen is not formatted for dark mode.

**To Reproduce**
1. Enable dark mode
2. Edit a goal
3. See unreadable placeholder text
4. Type
4. See unreadable goal title:
![Screenshot_20230529_120731_Chrome.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/45039a1b-b6d3-456b-af34-845cb29f5e66)
5. Also see there are large white dropdowns that should be styled differently in dark mode.

**Expected behavior**
Readable screen.
No white dropdowns or buttons.

**Comment by Tushar-4781** [comment]
by changing color of placeholder's for all input can resolve this issue

**Comment by tijlleenders** [comment]
The title is fixed but the From To and Duration are still white boxes...
