### ISSUE TITLE
Home button for navigation

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1235]
**Describe the bug**
I'd like the home button in breadcrumb, the 'MyGoals' text at top and the 'Goals' in bottom navigation (only when already on MyGoals page) to take me to the top of the hierarchy of goals.

**Comment by Tushar-4781** [comment]
@tijlleenders is it similar to #1196

**Comment by tijlleenders** [comment]
@Tushar-4781 
#1196 is purely about design/styling.  
This is about what happens when ypu click it.
