### ISSUE TITLE
Can't update timings 'between'

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1239]
**Describe the bug**
Refuses to save update on goal.

**To Reproduce**
1. Go to clean dev version
2. Edit Sleep for 22-7
3. Click 'Update goal'
4. Nothing happens

**Expected behavior**
Update goal when I click on 'Update goal'

**Comment by Tushar-4781** [comment]
It's because once the button is clicked the popup is not closed. Will Fix it quick
