### ISSUE TITLE
Enhancement: Reduce time to activate drag mode

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1240]
Based on first user experiences the drag function is a little slow to activate. People are used to other apps where drag activates faster.

**Describe the solution you'd like**
Reduce time to activate drag by 50%.

Could we use https://github.com/clauderic/dnd-kit ?

Alternatively - if there are issues between scrolling through the list and dragging - 
we could also only activate the drag on the circle...

**Comment by tijlleenders** [comment]
Discussed and it seems having a 'decent' drag&drop experience is quite hard to do in a React app.  
Native apps apparently have an advantage here.  

Does anyone know how to do this smoothly and with a quicker reaction time than long-press?

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders Are we making adjustments on the goals?

**Comment by Nicholas-Kipkoech** [comment]
I made some tests using my mobile device and I realized it takes time to activate. Let me research then come up with an optimized solution around it.
