### ISSUE TITLE
Once change theme is clicked, switch mode activates unexpectedly.

### ISSUE THREAD

**Issue by vinaybadgujar102** [tijlleenders/ZinZen#1245]
**Describe the bug**
After clicking the "Change Theme" button and applying the new theme, the options to change the theme appear every time a different page is selected from the bottom navigation bar. The Switch Mode is activated whenever I navigate through pages.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click 3 vertical dots on the top right corner and select Change Theme.
2. Apply any theme.
3. Navigate to any other page/section.
4. See the bug

**Expected behaviour**
After changing and applying the theme once, the options to change the theme should not reappear every time a different page is selected.

**Additional context**
There is also some unexpected behaviour observed due to this bug in other parts of the application.

**Comment by tijlleenders** [comment]
@vinaybadgujar102  
Thanks for catching this, I nearly pushed the dev version to production yesterday.

Please self-assign this issue if you'd like to work on it. You could throw in a test too if you feel up to it so we avoid this in the future. There are some examples to follow in the repo.

**Comment by vinaybadgujar102** [comment]
@tijlleenders @Tushar-4781 If I click change theme and then lets say mark a goal done, then I am again experiencing same issue.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 

Thanks I can reproduce it by finishing my theme selection after completing a goal.  

I do think this this is a different issue that merits a separate bug report.

**Comment by Tushar-4781** [comment]
Guys, did you updated the app via inbox?

**Comment by vinaybadgujar102** [comment]
@tijlleenders Can I add Screen Recoding in Issue?

**Comment by tijlleenders** [comment]
@vinaybadgujar102 
Yes a screen recording is always better than a screenshot or an explanation. Make sure you show you're updating to latest version.
