### ISSUE TITLE
Change theme mode activates unexpectedlty

### ISSUE THREAD

**Issue by vinaybadgujar102** [tijlleenders/ZinZen#1247]
**Describe the bug**
After clicking the "Change Theme" button and then marking a goal done in "My Goals" page, the options to change the theme appear every time a different page is selected from the navigation bar.

**To Reproduce**
1. Click on 'Change Theme' button
2. When options to change theme appears, select any goal and click done.
3. Navigate to any other page.
4. See the bug.

**Expected behavior**
The bug should be resolved.

**Screen Recording**
https://www.loom.com/share/72084b8705c64df6bd475fe6931bc7aa

**Comment by Tushar-4781** [comment]
Even its a rare case i have found a simple and fast solution that is to add a back-drop in bottom Navbar component so that if you click else where the change theme gets deactivated.
