### ISSUE TITLE
Prevent browser auto-install prompt

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1254]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you open an app for the first time to try it out and you immediately get an install prompt even before trying out the app.

**Describe the solution you'd like**
Avoid the browser auto-install prompt as it's best practice to only show the install prompt after user selects install from settings - when the app has been evaluated.  

**Describe alternatives you've considered**
None.

**Comment by tijlleenders** [comment]
Removed low prio as today I saw a user being blocked in onboarding because bottom navigatiom was being hidden by install prompt. User didn't want to install but also didn't click it away.  
This led to a focus on the three-dot menu for figuring out what the app could do and how to navigate - which then failed.

**Comment by Tushar-4781** [comment]
PS: once a solution is implemented, then build the app locally ( using **npm run build-local**  ) and then run a preview ( using **npm run preview** ) this would allow you to test the pwa locally

**Comment by tijlleenders** [comment]
@Tushar-4781  
Nice! That was an issue for me - I had to merge first :)

**Comment by tijlleenders** [comment]
Technically this could be as simple as cathing the beforeInstallPrompt event and storing it in a variable for later use (like for if  we add an install option in settings menu).
