### ISSUE TITLE
Doesn't remember don't ask again choice

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1269]
**Describe the bug**
Can't get ZinZen to remember my choice.

**To Reproduce**
1. Start a fresh browser.
2. Delete and mark "don't ask again"
3. Delete again ... and get asked again

**Expected behavior**
After you mark "don't ask again" it will not ask again for deleting.

**Screenshots**
![delete-without-questions-not-working](https://github.com/tijlleenders/ZinZen/assets/44887755/56905e3d-9efb-4354-9545-1c4fb0a22974)

**Comment by Tushar-4781** [comment]
To Resolve this we need to add translation of all languages

**Comment by dirudeen** [comment]
Hello! I'm new to open source projects and I will appreciate it if you could let me contribute to your project?

**Comment by tijlleenders** [comment]
Hi @dirudeen ,
You're welcome to contribute in any way that suits you. Raise an issue, make a comment, give feedback, tell a friend, fix an issue, etc.

Let me know if you need help - or have any questions.

**Comment by dirudeen** [comment]
Sure Thank you, I will start working on it asap

**Comment by dirudeen** [comment]
Hello, it seem to like the issue has been fixed in latest version. when I forked, cloned then run the project on PC the "don't ask me again" modal works exactly as expected

**Comment by tijlleenders** [comment]
@Tushar-4781 commented earlier:
> To Resolve this we need to add translation of all languages

@dirudeen So I think someone added the translations.

You are right, we can close this now.  
Thanks for looking into it!

**Comment by dirudeen** [comment]
Sure you are welcome.
