### ISSUE TITLE
"Forget" doesn't update timeline

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1276]
**Describe the bug**
After forgetting a Task it disappears from the Mytime page - but not completely. It is still visible in the Timeline.

![Screenshot_20230715_070232.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/8eb3882d-0807-4d7e-8248-6f69b101c8bf)

**Comment by Tushar-4781** [comment]
@tijlleenders 
which scheduler is this ?

**Comment by Tushar-4781** [comment]
there are changes in working and new modifications are added in UI so we have to modify the UI approach as well.
PR #1304 created the foundation for this feature. Once it gets merge, we can test the new approach and can close this issue
