### ISSUE TITLE
"Free" time doesn't show on timeline

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1277]
**Describe the bug**
"Free" time doesn't show on timeline.

This happens in dev mode only.  

I think it's better to refactor so that free time doesn't have to be explicitly passed to UI by the scheduler. Any time not scheduled is "free".

**Comment by Tushar-4781** [comment]
yes, the JS scheduler doesn't return the free slots and because of that the hrs are not visible
