### ISSUE TITLE
Completing sleep 22-6 also completes next day's part (22-0)

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1280]
**Describe the bug**
With dev mode on:
In the morning, marking 'Sleep' as done for the past night also completes the part of sleep for the coming evening.

**Comment by Tushar-4781** [comment]
this ain't a bug, the JS scheduler doesn't support the actions

**Comment by tijlleenders** [comment]
@Tushar-4781 Since scheduler doesn't support this atm I'm keeping this open.
