### ISSUE TITLE
Can't complete goal with flight mode on

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1289]
**Describe the bug**
Sometimes I can't conplete a goal with flight mode on. 

**To Reproduce**
It's hard to reproduce consistently. Some goals will conplete - some won't. Sometimes navigating up and down the goal stack solves the issue.

I have a video but too large to post on GH.

**Comment by Tushar-4781** [comment]
@tijlleenders please check this issue again as JS scheduler is now default. at my end things are working fine.

**Comment by tijlleenders** [comment]
Will leave this open as I only test this once a month.

**Comment by Tushar-4781** [comment]
PWA looses everything in cache when the installed app is closed. And when we restart the app after that in offline mode there is nothing in cache so these operations doesn't work. in this case it need to play sound so that file is not present in cache so it doesn't work.

**Comment by tijlleenders** [comment]
@Tushar-4781 Navigating away from place in hierarchy also "loses" the cache. I don't have to restart the app for producing the issue. Complete something successfully online - going one level up - turning on flight mode - and navigating back will make it impossible to complete goals.
