### ISSUE TITLE
Fire up CI only when PRs are created

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#131]
Need your input on this @tijlleenders @mallikarai05. Do we need to run the CI pipeline when a new branch has been pushed to the repository? I think it would be better to run the CI/CD only when PRs are created (and modified subsequently)

**Comment by tijlleenders** [comment]
Agree that only on PR would be better - but what inconvenience does running the pipeline on a new branch currently cause - except being unnecessary?

**Comment by pulkitvyas08** [comment]
Nothing much but once the number of tests increase, running CI on every file change might exceed the monthly free github actions quota before the end of the month

**Comment by tijlleenders** [comment]
Good point.
For now I can't see any statistics on how much minutes we use.

It is also not clear whether there is a limit ( the answer on https://github.community/t/for-public-repositories-is-there-a-monthly-limit-on-minutes/129017 kind of avoids the question ) - although I would think this is likely.

A FREE plan gets us 2000 minutes/month.
A PRO plan would increase this to 3000.

**I don't think we'll hit the 2000 anytime soon, so not a high prio.**
Once we hit the limit - we can think about:
- limiting the CI hitrate
- switching to paid PRO GitHub plan
- switching to Vercel / TravisCI / AWS (free/paid)

**Comment by tijlleenders** [comment]
And of course limit the CI hitrate where we can if not much trouble to add (ie not triggering this for new branch).
