### ISSUE TITLE
Goals splitted in consecutive days are not visible in first two days

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#1320]
For Example _Sleep 6 hrs every day between 22-7_

**Comment by tijlleenders** [comment]
@Tushar-4781 Sleep is now viaible 'tomorrow' but the part flowing over from 'yesterday' is still not visible on the first day.


In the Rust scheduler we dixed this to make the calendar >>for this goal<< start one day earler at the 'after' time whenever a daily goal has an 'after' > 'before' - or when 'after' + duration > 0:00.
After scheduling we then 'cut off' yesterday for that goal.

**Comment by Tushar-4781** [comment]
@tijlleenders please double check this, as per our discussion this bug doesn't exist

**Comment by tijlleenders** [comment]
@Tushar-4781 Sleep is now visible 'tomorrow'. Can't reproduce.

**Comment by tijlleenders** [comment]
@Tushar-4781 Will 0-6 never be scheduled on Today?
