### ISSUE TITLE
Design & Develop the MyGoal new UI

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#1327]
As discussed, it is crucial to track the time spent on tasks. If the user forgets to mark tasks as Done/Forget/Reschedule before the day ends, it's essential to present these unfinished tasks on the following day. This will allow the user to review and make decisions, ensuring that the hours are appropriately carried forward to the scheduler, facilitating a seamless schedule.

**Comment by tijlleenders** [comment]
@Tushar-4781 So we decided this will only be done for Goals that have a due date _and_ only if there is impossible, right?  
That reduces the amount of overload notifications when you don't use the app for a few days. Your history/track record for habits will just be blank - as you didn't update on the day itself. This can't be corrected for now.  

Implementation of impossible:
The current thought is to add a ! to the center of the circle.  
The circle can also be used for a notification dot - or an emoji extracted from the title - but the ! has precedence.

**Comment by tijlleenders** [comment]
Oh just saw it said "&develop" in the title...
