### ISSUE TITLE
Let JS scheduler schedule sleep for today

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1340]
**Is your feature request related to a problem? Please describe.**
It's very annoying when all my tasks get packed in 0-6 timeframe because scheduler doesn't schedule sleep from yesterday to today

**Describe the solution you'd like**
Make an exception for "Sleep" (in all languages) in JS scheduker so that it schedules for today too.

**Describe alternatives you've considered**
Start scheduling one day earlier for tasks where after > before.

**Comment by Tushar-4781** [comment]
@tijlleenders can be closed now
