### ISSUE TITLE
JS scheduler not respecting weekdays

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1347]
**Describe the bug**
Filter on weekdays doesn't work when there are filler goals. Only filler goals don't respect it - the rest works fine.

**Comment by Tushar-4781** [comment]
> **Describe the bug** Filter on weekdays doesn't work when there are filler goals. Only filler goals don't respect it - the rest works fine.

@tijlleenders could you please elaborate more by example ?

**Comment by tijlleenders** [comment]
https://github.com/tijlleenders/ZinZen/assets/44887755/9c869f3d-9290-473c-bf2f-42ff62ba3855

You can see that tomorrow (Sunday) filler goal Work ia scheduled - even though I specified On weekdays.

**Comment by Tushar-4781** [comment]
@tijlleenders its working for me i think there is some issue of synchronization. did u complete some part of hrs earlier ?

**Comment by Tushar-4781** [comment]
can you tell me how did u manage to do this. I remember i saw this earlier as well i think while resolving import export file this was skipped as we didn't saw it causing issue. just remove every week and it will work fine. lemme know if issue persist

**Comment by tijlleenders** [comment]
@Tushar-4781 Even if I do '40h op weekdays once (8h / day) tussen 8-18' it doesn't work.

**Comment by Tushar-4781** [comment]
yes @tijlleenders yes @tijlleenders i m aware of it. the current UI and scheduler doesn't allow every & on at same time. i was just figuring out that how do we handle on UI first

**Comment by tijlleenders** [comment]
@Tushar-4781 ah OK I misunderstood. 
Thanks for the update. I'll be patient :)

**Comment by Tushar-4781** [comment]
i was engaged in done mechanism. i will take this down first. no issues. thanks for reminder
