### ISSUE TITLE
Suggestion: Use Chakra UI as the styling component library

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#135]
@tijlleenders @pulkitvyas08 I suggest using the Chakra UI library for styling components.
https://github.com/chakra-ui/chakra-ui
Pre-made components can help in making the development much faster in the longer run.
If there is any other library we can use we can discuss it.

**Comment by pulkitvyas08** [comment]
+1 to this. Great suggestion. The way we are doing styling and making components right now is very inefficient and will take a lot of time to implement a lot of pages. Chakra being FOSS also aligns perfectly with the FESS philosophy of ZinZen

**Comment by tijlleenders** [comment]
One UI framework max plz.

**Comment by tijlleenders** [comment]
Ok let's stick with react-bootstrap since it is quit well documented, mature, popular, and MIT licensed.
If anything is impossible or feels like really cumbersome/hard then we can do a full review of alternatives.

Added this framework (and others) to Readme.md with #155
