### ISSUE TITLE
Let a budget be shared by all descendant goals

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1355]
**Is your feature request related to a problem? Please describe.**
It's very annoying when I have something I want to do for max 2h/week but I don't care what day it is on - but I do want to set a max per day.  
Let's say I have some books I want to read:  
- Book A 30h
- Book B 20h
I want to read max2h per week, max 1h per day - as a shared config for all the books; so at the parent level 'Read about topic X'.  
How do I configure this?  
I do not want to configure anything special manually per book except the estimated once duration.
I've tried multiple things that didn't work.  

**Describe the solution you'd like**
Make budgets impact ALL Goals below without having to copy something to the child level. When you copy a config to a lower level it is no longer a *shared* budget.

**Describe alternatives you've considered**
Repeat weekly 2h with 1h/day budget at parent level.  
When creating a child/book it will propagate the 1h/day to the child/book. This produces the wrong result in the scheduler. When removing the 1h/day on the child/book the scheduler schedules way too many hours per week.

**Comment by Tushar-4781** [comment]
Dependency: RUST scheduler

**Comment by tijlleenders** [comment]
Resolved by splitting goals into Budgets and simple Goals.
