### ISSUE TITLE
Simplify hours free display

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1356]
**Is your feature request related to a problem? Please describe.**  
It's very annoying when there's lots of repeating text on the screen.

**Describe the solution you'd like**
If there are no hours free don't show anything.  
If there are, write 'Xh free' instead of 'X hours free'

**Describe alternatives you've considered**
None.

![Screenshot_20230806_065350_Chrome.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/58abe242-998e-4205-adc0-a47ec397d2d1)

**Comment by Shahzaib-Iqbal-1057** [comment]
Hey I'll do my best to work on this(First-time contributor here!).

**Comment by tijlleenders** [comment]
Hi @Shahzaib-Iqbal-1057 
That's great!

Let me know if you have questions ;)

**Comment by tijlleenders** [comment]
Closed by #1359
