### ISSUE TITLE
Validate/improve duration input

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1360]
**Is your feature request related to a problem? Please describe.**
It's very annoying when I try to enter a duration as a new user and nothing gets scheduled.

**Describe the solution you'd like**
Whenever I enter an invalid duration, like "0,5" hours, the scheduler should automatically round it to whole hours, with a minimum of 1. This should apply to any input field where hours are set - so not only the goal duration but also the max /day and max /week.

**Describe alternatives you've considered**
Show a dialog saying only whole hours are aloud - but that's just annoying. A toast could be nice, but then also auto-correct.

**Comment by Shubham-Praj** [comment]
Hii @tijlleenders is this issue open ? If yes could you please assign this to me.
Thanks

**Comment by Tushar-4781** [comment]
@Shubham-Praj go ahead

**Comment by tijlleenders** [comment]
@Shubham-Praj If you want an extra challenge you can handle 0,5 as well as 0.5... Dutch people use a comma instead of a period for some strange reason....

**Comment by Shubham-Praj** [comment]
Thanks @Tushar-4781 & @tijlleenders
