### ISSUE TITLE
Show 100% done if there are no tasks today.

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1374]
**Is your feature request related to a problem? Please describe.**

![20230807_204017_DuckDuckGo.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/0d4e33f6-1926-425c-82ed-ea6a4aff2d83)

**Comment by Senatrius** [comment]
I think adding a simple ternary operator to check if there are tasks that day and show 100% by default if there aren't would be enough. Will take a look at it.

**Comment by tijlleenders** [comment]
Thanks @Senatrius !
