### ISSUE TITLE
Show impossible on Goal and Goal parents

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1377]
**Is your feature request related to a problem? Please describe.**
It's very annoying when something is impossible and you only find out when it's too late.

**Describe the solution you'd like**
Whenever there is a Goal that:  
- has impossible Tasks from scheduler output
show a ! inside the circle of the corresponding Goal, and any parents.  
When navigating 'down' the Goal hierarchy, always order Goals with a ! on top - so you can easily find the Goal that has an issue quickly.

**Comment by vinaybadgujar102** [comment]
@tijlleenders, Based on my understanding, a goal should display an exclamation mark "!" within its circle  if either of the following conditions is met:

- The goal has an assigned due date.
- The task scheduler marks it as impossible.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Thanks for checking the description of the issue was wrong.  
Actually the scheduler should be able to figure out the logic - so just marking anything the scheduler says is impossible with ! is sufficient.

**Comment by vinaybadgujar102** [comment]
@tijlleenders please give me some idea about how ! mark should look in goals with and without childrens

**Comment by tijlleenders** [comment]
Round - not square.

That's alk the design there is atm.

**Comment by tijlleenders** [comment]
Just a suggestion:  
![6_215436_Chrome.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/1deefae9-72cc-48b6-bf2b-d85f6233a110)

**Comment by tijlleenders** [comment]
...or if that's conplicated prefix the title with '!  '
