### ISSUE TITLE
Add dark theme for add feelings buttons

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#138]
![Screenshot_20220322-182431_DuckDuckGo.jpg](https://user-images.githubusercontent.com/44887755/159539633-60ce122b-fd0d-4164-9215-cd85a57b0cf1.jpg)

**Comment by mallikarai05** [comment]
@tijlleenders the dark theme for add feelings buttons is added now, if there are any changes let me know!
