### ISSUE TITLE
Show quick action light/dark toggle

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1380]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you're in the dark and the screen is bright. Going to the menu is just too mich hassle.

**Describe the solution you'd like**
In the header menu to the left of search icon show:
- a dark icon when screen is light _and_ time is between 18:00 and 6:00
- a light icon when screen is dark _and_ time is between 6:00 and 18:00
- show nothing when one of conditions above is not met 

**Describe alternatives you've considered**
Auto-adjust based on time. This could be a third toggle option in the dropdown menu but we should not assume everyone wants that.

**Comment by vinaybadgujar102** [comment]
Hey @tijlleenders, can I take this?
