### ISSUE TITLE
Add paper crumble sound when deleting Goal

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1382]
**Is your feature request related to a problem? Please describe.**
It's very nice when you get auditory feedback on actions.

**Describe the solution you'd like**
Play sound of a paper crumbling when deleting a Goal. Sound should be public domain license.

**Comment by Shahzaib-Iqbal-1057** [comment]
Sure! Let me see what I can do

**Comment by tijlleenders** [comment]
That's super @Shahzaib-Iqbal-1057 , thanks!  
Make sure it's comparable in size to other sound effects. ;)
