### ISSUE TITLE
Could be more flexible if user could change their language form dropdown menu.

### ISSUE THREAD

**Issue by FullStackSorcerer** [tijlleenders/ZinZen#1384]
**Is your feature request related to a problem? Please describe.**
Ex. I've accidentally selected wrong language from start and i don't found any way to change that back to desired language. 

**Describe the solution you'd like**
We could add language selector in drop down menu.

**Comment by tijlleenders** [comment]
Thanks for the suggestion @FullStackSorcerer !

It's indeed something that could be useful - although we don't want to overcrowd the menu with options that are hardly ever used.  
For now I think the functionality is useful - and it can be placed after the backup-restore option until we find a better spot.  

Would you like to work on it?

**Comment by FullStackSorcerer** [comment]
Sure!
