### ISSUE TITLE
Switch to Vite

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#139]
In all my recent projects I've been using Vite.js (https://vitejs.dev/) as the build system to replace webpack and the results are always amazing. The time-consuming and resource-intensive webpack is just unusable as the project progresses. It took 3 minutes on my system to just start the server and add on to that the time it takes for each reloads/refresh after making changes, the developer experience just becomes really frustrating. I would strongly recommend migrating to Vite immediately

**Comment by tijlleenders** [comment]
Let's discuss this Friday.
Changes to the project should be instant as we're not using compiled languages (yet).

The main function of webpack/vite in my view is minimizing download size by bundling/compressing assets.
For dev environments this doesn't matter and can be skipped.
