### ISSUE TITLE
Design a catchall 404 page

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#140]
There should be a 404 page displayed on slugs not covered by the source

**Comment by mallikarai05** [comment]
Should the design have a button that directs back to the dashboard? Is there anything else that has to be added?

**Comment by pulkitvyas08** [comment]
> Should the design have a button that directs back to the dashboard? Is there anything else that has to be added?

Just the navbar should be good enough

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/161395878-374d23c5-6c71-4b83-a31d-64282b7d0c0c.png)
I actually ended up making the page, is this okay? Are there any changes required?

**Comment by pulkitvyas08** [comment]
> ![image](https://user-images.githubusercontent.com/73054648/161395878-374d23c5-6c71-4b83-a31d-64282b7d0c0c.png) I actually ended up making the page, is this okay? Are there any changes required?

Looks good to me, go ahead. If there are any changes then we can always revisit
