### ISSUE TITLE
Move Create/Update goal button

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1409]
**Is your feature request related to a problem? Please describe.**
Ex. It's very annoying when I have to scroll down to bottom of the screen when quickly adding a few goals/items in a list.

**Describe the solution you'd like**
Move the 'Create goal' button to the right of the hours field. That way we don't have to scroll all the way down for a quick add goal.

![20230819_19421.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/5dd8b414-eecc-4855-88a5-1c0c79c313fe)

**Comment by Shubham-Praj** [comment]
Hi @tijlleenders can you please assign this to me

**Comment by tijlleenders** [comment]
@Shubham-Praj Sure thing!
