### ISSUE TITLE
Remove unused code, refactor code standards issues

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#141]
There are some problems with the code in terms of following the standards and a few places where unused code is left for no reason. It is more or less a pet peeve of mine to fix these things before putting out any serious code so I'll take a small amount of time to get the following done - 
- Remove unused code
- Refactor default exports/imports to named exports/imports
- Fix some code standards issues (indentations, empty lines, spaces, etc)

**Comment by tijlleenders** [comment]
Yes!
Clean the workspace before doing the work.
