### ISSUE TITLE
Code style standards

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#142]
@tijlleenders @mallikarai05 I'm not aware of any existing documentation or references that are followed in the project for code standards. Please point me in the right direction if something like that exists. We can discuss this later if it doesn't

**Comment by pulkitvyas08** [comment]
I did prepare a style standards doc sometime ago. Let me check if I can find it again

**Comment by tijlleenders** [comment]
Let's use a standard formatter like Prettier or Google formatter in the CICD.
This way we enforce a standard on the code repo.
Locally we can use the IDE extension.

Blocked by #42

**Comment by pulkitvyas08** [comment]
> Let's use a standard formatter like Prettier or Google formatter in the CICD. This way we enforce a standard on the code repo. Locally we can use the IDE extension.

+1
> 
> Blocked by #42

Okay let me get back to this after fixing the said issue

**Comment by tijlleenders** [comment]
Code style standards are included in what needs to be done for #250, so this issue can be closed.
