### ISSUE TITLE
Timebar over sub menu

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1422]
**Describe the bug**
Timebar over sub menu:
![Screenshot_20230822_190451_Chrome.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/683d360a-6d95-4e31-aeed-b78030d91c0f)

**Comment by webAbhi** [comment]
Hey @tijlleenders, can i help here ? i would love to work on this !!

**Comment by tijlleenders** [comment]
Sure @webAbhi , thanks!
