### ISSUE TITLE
Short pling sound effect when creating goal

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1430]
**Is your feature request related to a problem? Please describe.**
It's very cool if you get a positive sound after setting a new goal.

**Describe the solution you'd like**
A very short pling. Not as long as when completing a goal but still positive.

**Comment by Ktn-mariam** [comment]
Hi @tijlleenders, could you assign this issue to me if it is open? Thank you!

**Comment by tijlleenders** [comment]
Sure @Ktn-mariam thanks!

Please make sure the licenae for the sound is 100% free ;)
