### ISSUE TITLE
Navigate to top of goals with top menu

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1432]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you quickly want to navigate to the top of your goals - but the home icon in breadcrumb is quite small and the bottom menu is far away from your focus zone.

**Describe the solution you'd like**
Make the 'My goals' top menu navigate to the top of your goals tree on click.
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/15763569-7234-4d25-9229-f4ca74d29f1d)

**Comment by OpherM** [comment]
what page is this?

**Comment by tijlleenders** [comment]
Hi @OpherM , sorry for the confusion. The screenshot is in Dutch - but it's the MyGoals page. Right now clicking on MyGoals header doesn't doe anything.

Would you like to work on this?
