### ISSUE TITLE
Pre-fill hours of the day by default

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1433]
**Is your feature request related to a problem? Please describe.**
It's very annoying when I have to fill out fields when they can be pre-filled to fit the most common usecases.

**Describe the solution you'd like**
Put real values (not a placeholder) in the hours of the day fields: 9-18

**Describe alternatives you've considered**

**Additional context**

This was part of #1363 but since the logic of differentiating between placeholder, suggestion and user-defined values and relationships for autocalculation was complicated we left out some default values. For hours of the day we can implement it though since we can use real values directly - not placeholders - and it is not dependant on other input fields.

**Comment by Ktn-mariam** [comment]
Hi, @tijlleenders I'm interested in working on this open issue. Could you please assign it to me? Thank you!

**Comment by tijlleenders** [comment]
That's super nice @Ktn-mariam !
