### ISSUE TITLE
Goal screen responsiveness 

### ISSUE THREAD

**Issue by webAbhi** [tijlleenders/ZinZen#1435]
**Describe the bug**
Goals screen ui is not properly displayed in smaller device.

**To Reproduce**
use a small device to access access Goals tab.

**Expected behavior**
UI should be rendered without breaking the page.

**Screenshots**
![Screenshot_20230823-203408_Chrome](https://github.com/tijlleenders/ZinZen/assets/25529176/2878fa0e-86a3-43c5-b684-e064c9b43366)

**Comment by tijlleenders** [comment]
Thanks for taking the time to create a bug report @webAbhi !

Could you explain what is going wrong? 
Is it the 'half circles'?

I see a screenshot of an older version of the UI. If you refresh the browser/app (pull down), close and re-open the app you should be on the latest version.

Maybe that will already fix whatever you think is the bug - for sure if it's the half circles.

**Comment by tijlleenders** [comment]
@webAbhi !

The title also mentions responsiveness. That is something that is best captured by a video or console logging with timestamps.

**Comment by webAbhi** [comment]
It was the half circles which was bothering me, but I can see it's fixed now. Thanks !!
