### ISSUE TITLE
Auto reduce max duration to 99

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1443]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you accidentally enter a three digit duration like 120 when you actually wanted to enter 20. It then shows like 20 on the edit screen when in fact it's 120.

**Describe the solution you'd like**
Whenever a duration >99 is entered - autocorrect to 99.

**Describe alternatives you've considered**
Allow durations of >99 and show 3 digits. This has several problems. It isn't easy to work/think with so many hours. If we need a big duration we'd like to enter days, weeks or months. Also it's not a common use case - when there are alternatives: use a repeat + due date or break down the work jnto max 99h subGoals.

**Comment by Shubham-Praj** [comment]
Hey @tijlleenders could you please assign this to me

**Comment by tijlleenders** [comment]
Go for it @Shubham-Praj !
