### ISSUE TITLE
Reduce height of breadcrumb boxes and round corners more

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1466]
**Is your feature request related to a problem? Please describe.**
It's very annoying when boxes are oversized - and conflicting with the round /circle theme.

**Describe the solution you'd like**
- Reduce total height of breadcrumb boxes.  
- Round the corners to make it look more like pills than boxes.

**Describe alternatives you've considered**
Don't use boxes. Don't know what would be the alternative that still allows to show the color of respective subgoals.

**Additional context**
![St_20230903_0e.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/8b7acee9-7589-4deb-b98c-b0a2b38bbb60)

**Comment by vinaybadgujar102** [comment]
@tijlleenders I can do it

**Comment by tijlleenders** [comment]
@Tushar-4781 Does this interfere with your PR under works?

**Comment by tijlleenders** [comment]
Hey @vinaybadgujar102 
Would be great if you can work on this!
