### ISSUE TITLE
[BUG] Broken link in README.md

### ISSUE THREAD

**Issue by RuthwikReddy09** [tijlleenders/ZinZen#1476]
**Describe the bug**
The development setup page link is broken in README.md file

**To Reproduce**
Steps to reproduce :
1. Go to README.md
2. Scroll down to Getting Started Section
4. Click on "Development Setup Page" link

<img width="939" alt="Screenshot 2023-09-03 172328" src="https://github.com/tijlleenders/ZinZen/assets/126862059/35c97ad8-61f1-4d97-8057-c1a4b1a90736">

**Comment by tijlleenders** [comment]
Thanks for reporting this @RuthwikReddy09 and welcome to ZinZen!

The dev setup link should point to https://github.com/tijlleenders/ZinZen/blob/main/documentation/technical/Readme.md  

The setup isn't real complicated. We like it  simple. :)


We'll get it fixed soon - unless you want to make a PR yourself.

**Comment by tijlleenders** [comment]
... and let us know if you run into trouble so we can make it easier for the next person.
