### ISSUE TITLE
Navbar buttons not working + remove menu

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#148]
Seems like their `OnClick` has not been connected with the router yet.
Also the logo or the ZinZen link on the navbar should redirect to homepage.
Remove the stuff marked with red X.
![image](https://user-images.githubusercontent.com/44887755/162404409-4318fab4-0959-4713-8351-8ab6ca2a6d6b.png)

**Comment by pulkitvyas08** [comment]
Also the logo on the navbar should redirect to homepage

**Comment by tijlleenders** [comment]
On the choose theme page the menu button is still showing.

**Comment by pulkitvyas08** [comment]
> On the choose theme page the menu button is still showing.

Fixed in #218
