### ISSUE TITLE
Remember place in goal hierarchy after switching to Journal

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1481]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you lose your place in the Goal hierarchy just by switching to your Journal for an instant.

**Describe the solution you'd like**
Remember where you were in the Goals hierarchy when navigating the bottom menu.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by vinaybadgujar102** [comment]
@tijlleenders  Can you elaborate on this? I am not able to reproduce this issue.

**Comment by vinaybadgujar102** [comment]
Issue resolved
