### ISSUE TITLE
Dark mode for Toast messages

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1482]
**Is your feature request related to a problem? Please describe.**
It's very annoying when a big white thing show up unexpectedly in dark mode.

**Describe the solution you'd like**
A dark mode Toast.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by vinaybadgujar102** [comment]
@tijlleenders I can work on this

**Comment by tijlleenders** [comment]
Excellent @vinaybadgujar102 !
