### ISSUE TITLE
Friendly URL display

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1484]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you don't remember the URL and have to click on it to find out.

**Describe the solution you'd like**
A short summary of the URL in the form of [four first characters of Domain .. three last characters of Domain] where Domain is the part right below/before the TopLevelDomain (ie .com .dev etc).
So 'https://subsomething.example.com/page/locator' would become 'example' - underlined but 'https://subsomething.longerexample.dev/another/page' would become 'long..ple' - underlined.

**Describe alternatives you've considered**
Show full url when first clicking on it. This would be annoying as you need to click twice every time to navigate to the page.

**Additional context**
![20230905_084543_Chrome.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/29a5e3e3-ec96-483b-a2d8-d478979b97cf)

**Comment by vinaybadgujar102** [comment]
I can work on this @tijlleenders

**Comment by tijlleenders** [comment]
Ow that's great @vinaybadgujar102 !
