### ISSUE TITLE
New dark/light theme

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1494]
**Is your feature request related to a problem? Please describe.**
The current theme is not suitable for everyone and makes extreme personalisation difficult.

**Describe the solution you'd like**
Implement new themes as such:  
https://github.com/tijlleenders/ZinZen/assets/44887755/0ec153c9-42aa-42c9-b68c-0a9b2806fdba

**Describe alternatives you've considered**
We've played around with a custom designed set of themes. This is less conplicated and offers more guarantees for contrast/consistency whilst still offering a free range of colors personalisations.

**Additional context**
The colors of the current goals can remain the standard colors.  
Also the way of selecting the theme shoukd not be as in the video - just use the current theme selection menu.

**Comment by vinaybadgujar102** [comment]
I would like to clarify whether these new themes will completely replace the current theme style, or will they be added as additional choices alongside the existing ones?

**Comment by tijlleenders** [comment]
Completely replace, right @Tushar-4781 ?

**Comment by vinaybadgujar102** [comment]
@tijlleenders are there any design files of new themes for reference?

**Comment by Tushar-4781** [comment]
> Completely replace, right @Tushar-4781 ?

yes we have replaced with more simple design
