### ISSUE TITLE
Add auto-format to CI

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1507]
**Is your feature request related to a problem? Please describe.**
It's very annoying when code gets merged that is formatted differently than agreed upon.

**Describe the solution you'd like**
Format the code in CI according to the project guidelines provided in #1506 

**Describe alternatives you've considered**
None. This is necessary when accepting contributions from the outside.

**Additional context**
None.

**Comment by Tushar98644** [comment]
@tijlleenders I would like to take up this issue under hacktoberfest

**Comment by tijlleenders** [comment]
Oh that's great @Tushar98644 

This issue is blocked by #1506 - or do you see a workaround?

**Comment by Tushar98644** [comment]
> Oh that's great @Tushar98644
> 
> This issue is blocked by #1506 - or do you see a workaround?

I think this issue is already solved , a pre-commit hook is already implemented which will format the code according to the settings defined in the `.prettierrc` before someone commits the changes

**Comment by tijlleenders** [comment]
Thanks @Tushar98644 !
I've added the `hacktoberfest-accepted` label.
