### ISSUE TITLE
Add Playwright Tests for sharing feature

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#1516]
Follow the steps: - 
- On User 1 window
      1. Open app, finish onboarding
      2. Select a goal on my goals page
      3. click on circle and select share action
      4. select "share privately" from the popup
      5. click on plus btn to add contact
      6. write a name "User 2" and click on share invitation
 
- Open that link in new window that will be acting as User 2
      1. Open app, finish onboarding
      2. paste link and add the contact
     
- On user 1 window, click on the contact btn again to share the goal this time
      
- On user 2 window
      4. refresh the window
      5. switch to my time and switch back to my goals
      6. check if inbox icon is visible
      7. click on inbox and check whether goal is present or not

**Comment by Tushar-4781** [comment]
Blocked by #1491

**Comment by tijlleenders** [comment]
@Tushar-4781 So the issue blocking this is solved. 

Can we implement the test as described in this issue?
