### ISSUE TITLE
Temporarily pause following changes sent by the sharer

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#1519]
So let's say **A** shared a goal with **B**  and **B** followed **A**, he also requested **A** to follow him back. And **A** denied and after some time **A** decided to follow and get all changes. how can he do that ? are the changes going to be in Partner's mode if yes then how should he add him back to the collaboration so that the updates can be seen by his other participants.

**Comment by tijlleenders** [comment]
I think your idea of clicking the participants of A's goal and re-activating the follow B is a good way of doing this.  
Only the differences at that point (note: possibly not identical to all of the changes) would then be presented for accept/deny. Only the differences accepted by A would be propagated to those following A - but they would seem to come from A.

**Comment by tijlleenders** [comment]
@Tushar-4781 I think this discussion is settled.  
Morphing this to an issue - and putting it on the backlog.

**Comment by tijlleenders** [comment]
Not sure if this can be separated from #1517 - but I'd like to give prio to #1486 this week.
