### ISSUE TITLE
Empty Goals are created using Spacebar

### ISSUE THREAD

**Issue by vinaybadgujar102** [tijlleenders/ZinZen#1523]
**Describe the issue**
When creating a new goal, it is possible to create an empty-looking goal by simply pressing the spacebar as the goal's title. This results in a goal that appears blank.

**To Reproduce**

1. Go to Goals page using bottom navigation.
2. Click on '+' button in bottom right corner
3. Press spacebar
4. Empty goal is created

**Expected behavior**
Users should not be able to create a goal with only spaces as its title.

**Comment by Shubham-Praj** [comment]
Hey @tijlleenders can you please assign this to me

**Comment by tijlleenders** [comment]
Sure, thanks!
