### ISSUE TITLE
Use darker background in dark mode

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1527]
**Is your feature request related to a problem? Please describe.**
The background of the new theme is too light. The previous one was nicer. [Google material design recommends #121212](https://m2.material.io/design/color/dark-theme.html#properties)

**Describe the solution you'd like**
Use #121212

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Shubham-Praj** [comment]
Hey @tijlleenders please assign this to me. 
I have 1 question. This color change has to be done for all dark themes right ?

**Comment by tijlleenders** [comment]
That's great @Shubham-Praj !

Yeah, for all dark backgrounds at lowest elevation - so the goal backgrounds for all dark themes, but not the header background.
