### ISSUE TITLE
Overflow in Goal Title background in new/edit goal modal

### ISSUE THREAD

**Issue by vinaybadgujar102** [tijlleenders/ZinZen#1533]
**Describe the issue**
There is little overflow on the right side of the goal title background colour. 

**Expected behavior**
Fix the overflow

**Screenshots**
![image](https://github.com/tijlleenders/ZinZen/assets/90821253/e86627a4-f73a-449f-971b-7eb112057166)

**Comment by tijlleenders** [comment]
Thanks @vinaybadgujar102 

Indeed this needs to be fixed.
