### ISSUE TITLE
Feedback in menu doesn't work

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1540]
**Describe the bug**
Clicking 'Feedback' from menu doesn't do anything.

**To Reproduce**
Click 'Feedback' in menu.

**Expected behavior**
Takes you to the Feedback page.

**Screenshots**
None.

**Additional context**
None.

**Comment by devmusiczz** [comment]
Hey @tijlleenders I'll take this up. Assign this issue to me.

**Comment by tijlleenders** [comment]
Thanks @devmusiczz 

I'm not sure if other people also experience this. So far I'm the only one I think.

**Comment by devmusiczz** [comment]
@tijlleenders I think this is the genuine issue. I experienced the same.

**Comment by tijlleenders** [comment]
Ok then g'luck!

**Comment by tijlleenders** [comment]
@devmusiczz 
It's not happening in the [dev version](https://zinzen.vercel.app) so I think we just need to push dev to prod?

**Comment by devmusiczz** [comment]
@tijlleenders yes! it's also working well on local setup.

**Comment by tijlleenders** [comment]
@devmusiczz Thanks anyway 👍!
