### ISSUE TITLE
Remove group.service.ts

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1543]
**Is your feature request related to a problem? Please describe.**
This feature is abandoned in favor of sharing pseudo-anonymously in combination with hints.

**Describe the solution you'd like**
Remove any reference to group goals.

**Describe alternatives you've considered**
Leave it. This clutters the code and confuses newcomers.  
If we need the code we can always retrieve it from git history.

**Additional context**
None

**Comment by Tushar-4781** [comment]
Hey @vinaybadgujar102 can u take this ?

**Comment by vinaybadgujar102** [comment]
@Tushar-4781 can you elaborate on what needs to be done?
