### ISSUE TITLE
Url in parenthesis

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1553]
**Describe the bug**
When I add a url to a goal title enclosed in () the app freezes.

**To Reproduce**

1. Edit a goal title
2. Add (example.com)
3. Save and see error

**Expected behavior**
Saves normally.

**Screenshots**
None.

**Additional context**
None.

**Comment by boredcity** [comment]
Seems interesting, I'd love to take a look if you're ok to assign me.

**Comment by tijlleenders** [comment]
Oh that woukd be nice @boredcity !

**Comment by Tushar-4781** [comment]
Closed by #1554

**Comment by tijlleenders** [comment]
Thanks @boredcity !
