### ISSUE TITLE
Notify there is a new partner in partner mode

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1558]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you accept a partner/relationship request by clicking on a link and naming the partner - but then don't know you can click on the ZZ logo to go to partner mode.

**Describe the solution you'd like**
After I accept a new partner/relationship, take me to that partner's goals. Clicking on the header or logo should first take me to partner root goals, then switch me back to my goals.

**Describe alternatives you've considered**
Put a dot/animation/something on the ZZ logo so you click on it after accepting a new partner/relationship request. This is less user friendly as it requires you to take an extra step after accepting/naming.

**Additional context**
None.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 We could use the https://ant.design/components/tour component to signal where to click to see the partner's goals.

**Comment by vinaybadgujar102** [comment]
I've got a couple of questions about the Partner Mode Tour on:

**Tour Steps:** How many steps should we include in the tour? Do you have any ideas for the titles and descriptions for these steps? 

**Tour Activation:** Should the tour trigger only the first time a user accepts a partner link, or every time they accept a new partner?

**Comment by tijlleenders** [comment]
@vinaybadgujar102 It's just one step - activated the first time only.
