### ISSUE TITLE
Can't see suggestion accepted by partner

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1559]
**Describe the bug**
After I make a suggestion to my partner and (s)he accepts it - I don't see it in partner mode.

**To Reproduce**

1. A suggests subgoal to B
2. B accepts goal
3. A should see the subgoal in B's goals - but currently doesn't.

**Expected behavior**
See 3.

**Screenshots**
None.

**Additional context**
None.

**Comment by Tushar-4781** [comment]
Gets auto resolve, if #1519 gets resolved
