### ISSUE TITLE
Initial summary of budget wrong

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1574]
**Describe the bug**
When I open the budget details for the first time the hours on the summary (45 is incorrect) don't match the theoretical maxima (that correctly show on the slider as 9).

**To Reproduce**
1. Make a new goal and set the between hours.
2. See that the summary hours don't match the hours on the slider bar

**Expected behavior**
Correct values for budget summary.

**Screenshots**
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/16733b71-b840-41d3-b082-0f29feae7c39)

**Additional context**
 Dynamically adapting when using the slider can be a separate issue.

**Comment by webAbhi** [comment]
so as per my understanding, we want to fix **9 hrs / day** and **45 hrs / week** text to show **1 hrs/day** and **5 hrs/week** ?

**Comment by tijlleenders** [comment]
@webAbhi Yes, that's correct. Would you like to work on this?

**Comment by webAbhi** [comment]
Sure, i can fix this. please assign this to me.

**Comment by webAbhi** [comment]
Hey @tijlleenders, i am unable to reproduce this issue. 
can you please check the current version. i even tried moving to a incognito window.

<img width="1357" alt="Screenshot 2023-11-02 at 8 45 06 AM" src="https://github.com/tijlleenders/ZinZen/assets/25529176/2dc28a63-33c0-4a16-b0b0-dd949f0452fc">

**Comment by tijlleenders** [comment]
Thanks for checking @webAbhi 

Try adjusting the slider from the initial values to 10-11 before uncollapsing the budget details. You will see the total summary remains unchanged 9h/day 45h/week - instead of 1h/day 5h/week.

**Comment by tijlleenders** [comment]
Resolved by #1593
