### ISSUE TITLE
Reduce the use of !important

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#162]
Currently !important is used quite extensively.
The SCSS design needs to be revisited to make it:
- easier to understand/maintain
- easier to override by client

Motivation:
https://dev.to/alvaromontoro/using-important-in-css-75c

**Comment by pulkitvyas08** [comment]
The referenced blog doesn't take in the limitations set by CSS frameworks. IMO `!important` is the only clean way to get things done in a lot of cases including here. Otherwise, you will have to define your own components which will take time and resources for no reason

**Comment by tijlleenders** [comment]
Ok - it seemed like an antipattern - but I'm no expert on this subject.
Closing it so we can prioritize other concerns.
