### ISSUE TITLE
Make Mytime less busy

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1624]
**Is your feature request related to a problem? Please describe.**
It's very nice when a screen you use frequently is well-designed - and not too busy.

**Describe the solution you'd like**
Don't show hours by default.  
Instead only show the hours, and the options once you click on the Task.  
If you click again you go to the Goal as usual - unless you use any of the Task actions.

**Describe alternatives you've considered**
None. It's an experiment.

**Additional context**
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/48c69392-d6b7-47f5-8102-253a4f852317)

**Comment by vinaybadgujar102** [comment]
@tijlleenders do you also want task actions to be moved to the same row as task hours
