### ISSUE TITLE
Correct placement of add button in browser

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1627]
**Is your feature request related to a problem? Please describe.**
It's very annoying when somebody opens ZinZen on browser for the first time - and doesn't see the add button because it's way outside of the main area.

**Describe the solution you'd like**
Correctly place the + button on browser, just like on mobile

**Describe alternatives you've considered**
Leaving it the way it is - as we're designing for mobile only.  
This is however a quick-fix - and can help with the first contact that for some people will be on browser.

**Additional context**
We choose to support mobile-first and mobile-only - so that we can focus and get more done.
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/072c108e-ecc7-4d43-8714-b330a4d878b5)

**Comment by Sanket-Arekar** [comment]
Hey @tijlleenders I would like to work on this issue. Can you Please assign me this issue?

**Comment by chinmayborade** [comment]
Please consider me to resolve this issue

**Comment by tijlleenders** [comment]
Sure @chinmayborade 

Would be nice if you can help out!

**Comment by chinmayborade** [comment]
Hey Can you please pin the repo @tijlleenders

**Comment by chinmayborade** [comment]
Yes thank you so much

**Comment by tijlleenders** [comment]
@chinmayborade We want to resolve this issue today ... because we need it for a recording session of a a Dutch movie coming out in February. Do you have anything to commit?

Otherwise we'll resolve it in the coming hours.

**Comment by chinmayborade** [comment]
so sorry @tijlleenders actually i had exams thats why didnt got time to resolve  this but you can assign me anything on next task thank you

**Comment by tijlleenders** [comment]
np @chinmayborade Feel free to look around on the [project board](https://github.com/users/tijlleenders/projects/4/) !
