### ISSUE TITLE
Add 'Hints' toggle to Goal and Budget edit screen

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1629]
**Is your feature request related to a problem? Please describe.**
It's very nice to get hints.

**Describe the solution you'd like**
Add a (default switched off) Hints toggle to the Goal and Budget create/edit menu like so:
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/58ddb582-3f59-49ef-8c5a-d6e4a4c55c72)

**Describe alternatives you've considered**
Integrating the text inside the toggle like so:
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/d81fd513-003a-48b8-9731-f2fe45abb85b)

This does however create a very big area of action color on the screen. It also is less readable/accessible with font size being smaller and lower contrast. 
The alternative with 'Hints' outside of the toggle is better/cleaner/more discreet/more accessible/less noisy.

**Additional context**

![Image](https://github.com/tijlleenders/ZinZen/assets/44887755/027e0ea7-2b9c-4343-92c1-0676341d4a59)

![Image](https://github.com/tijlleenders/ZinZen/assets/44887755/fcadb6d0-700f-40be-b9cc-86d34999e6c5)

The Hints functionality will not be complete - but this toggle is the first step.  
It later has to be connected to querying the pseudoanonymousmessages endpoint to retrieve any hints on a random weekly basis - and create a notification dot if there are new Hints, together with a Hint modal with 'Report'/'Dismiss'/'Next'/'Add'/'Snooze for a week' buttons.  
There will be separate issues for that.

**Comment by Sanket-Arekar** [comment]
Hey @tijlleenders I would like to work on this issue. Can you Please assign me this issue?

**Comment by tijlleenders** [comment]
Hi @Sanket-Arekar sure that would be wonderful.  

You've already got two issues on your name so let's keep this one one the backlog till you're finished with those ok?

**Comment by Sanket-Arekar** [comment]
yes. I can do this

**Comment by siva9495** [comment]
@tijlleenders can you please assign me in this issue?

**Comment by tijlleenders** [comment]
Of course @siva9495 !

**Comment by tijlleenders** [comment]
Hi @Sanket-Arekar do you have a PR or can I give this to someone else?

**Comment by tijlleenders** [comment]
@Sanket-Arekar Thanks for trying and responding!  

@siva9495 Still up for this?

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Could you pick this up?
