### ISSUE TITLE
Better contrast for default yellow in light theme

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1630]
**Is your feature request related to a problem? Please describe.**
It's very annoying when contrast is too low.

**Describe the solution you'd like**
Find a yellow that has better contrast in loght theme. Preferably follow some usability/accessability standard.

**Describe alternatives you've considered**
None.

**Additional context**
![_20231126_ckGo.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/5f99d198-3bbd-40f9-a7e7-bf9153eeaaaf)

**Comment by Sanket-Arekar** [comment]
Hey @tijlleenders  I would like to work on this issue. Can you Please assign me this issue?

**Comment by tijlleenders** [comment]
Hi @Sanket-Arekar that's great!

**Comment by chinmayborade** [comment]
Hey I will surely try to resolve this issue

**Comment by chinmayborade** [comment]
Can you please assign this to  me ??

**Comment by tijlleenders** [comment]
@chinmayborade 
That's great but this issue is already assigned to @Sanket-Arekar ...

**Comment by Sanket-Arekar** [comment]
Please check and review the changes and let me know.
