### ISSUE TITLE
Replace 'Following' button with a switch

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1631]
**Is your feature request related to a problem? Please describe.**
It's very annoying when a button is not clear. Right now the 'Following' button has the action color:
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/5b36ceb3-aec5-4136-8880-830dc899b081)
... but when I unfollow it has a near-identical appearance:  
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/619d3c5d-300a-46ef-84ac-09b023a9f889)

**Describe the solution you'd like**
Replace the "Following" button: 
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/1d8cce62-e2cb-414d-8c4a-e50508cf57cf)
... with a switch:
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/ef5076e3-09ae-4b01-ab24-a01683fcef28)
+ to make the switch make sense change the title of the modal to 'Following' instead of participants.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by siva9495** [comment]
Hi @tijlleenders 
Is this ok, or should I make any changes?
![Screenshot (8)](https://github.com/tijlleenders/ZinZen/assets/57442699/8ec7f853-1058-459f-8c02-18744f82393e)
![Screenshot (9)](https://github.com/tijlleenders/ZinZen/assets/57442699/ad400786-8e88-4591-aed7-62af05ed3a00)

**Comment by Sanket-Arekar** [comment]
Hey @tijlleenders  I would like to work on this issue. Can you Please assign me this issue?

**Comment by siva9495** [comment]
Ok @tijlleenders 
I will check and update it. Can you please assign me this issue?
