### ISSUE TITLE
Consistent font size in edit modal

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1632]
**Is your feature request related to a problem? Please describe.**
It's very annoying when a font is too small - or there are many different font sizes being used.

**Describe the solution you'd like**
Make the Title font just as big as goal title fonts.  
Make the action button subtexts just as big as the Goal subtext.  
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/aee7c672-5670-4f3b-a946-4e07f2390fde)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by DarioPrazeres** [comment]
Is there Someone to work with?

**Comment by tijlleenders** [comment]
Hi @DarioPrazeres , would you like to try this issue?

**Comment by DarioPrazeres** [comment]
yes, I would like and I speak portuguese too if I have a way to contribute with translate the project I am free!

**Comment by tijlleenders** [comment]
@DarioPrazeres That is super cool!

You're welcome to work on this. You can also check out the Portuguese translation files - and correct anything weird.  
There are some parts of the app that are not translated yet...

**Comment by tijlleenders** [comment]
Please make a separate branch `git checkout -b dario/1632/consistent-font-size` or similar and submit a PR.

**Comment by pessiMargalit** [comment]
I'd like to take this issue if you still need it.

**Comment by tijlleenders** [comment]
Welcome @pessiMargalit - that would be nice!
