### ISSUE TITLE
Move 'Sleep' to 'Daily habits'

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1636]
**Is your feature request related to a problem? Please describe.**
It's very nice when things are organized.

**Describe the solution you'd like**
Put default goal Sleep into 'Daily habits'.

**Describe alternatives you've considered**
None.

**Additional context**
![0306_DuckDuckGo.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/cf0c06c2-f3a9-4352-a25a-7a8874dc029c)

**Comment by Sanket-Arekar** [comment]
Hey @tijlleenders I would like to work on this issue. Can you Please assign me this issue?

**Comment by tijlleenders** [comment]
Hi @Sanket-Arekar , due to inactivity I'm moving this back to the parking lot.  
It's not a problem - life happens. However I do want to free this up for someone else to be able to pick it up.
