### ISSUE TITLE
Change wording goal time summary

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1637]
**Is your feature request related to a problem? Please describe.**
It's very annoying when there's more words than necessary.

**Describe the solution you'd like**
ONLY when the minimum per day > 0 AND all 7 days are selected: replace the 'on any day of the week' with 'daily'.

**Describe alternatives you've considered**
None.

**Additional context**
![447_DuckDuckGo.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/7f450252-165a-457c-b43c-a0a662e65404)

**Comment by Sanket-Arekar** [comment]
Hey @tijlleenders I would like to work on this issue. Can you Please assign me this issue?

**Comment by tijlleenders** [comment]
Hi @Sanket-Arekar , that's great!

**Comment by Sanket-Arekar** [comment]
Hey, I fixed the issue. Here's the Pull request link https://github.com/tijlleenders/ZinZen/pull/1639

**Comment by tijlleenders** [comment]
@Sanket-Arekar If you add 'Resolves #issuenumber' to the PR description it will auto-close the issue upon merge ;).
