### ISSUE TITLE
only import required files

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#165]
1.
[The i18n.js file](https://github.com/tijlleenders/ZinZen/blob/main/src/translations/i18n.js) imports all languages.
This bloats the app download time/cost + local cpu, storage and mem required.

It should only import the language chosen by the user.

2.
[The App.js file](https://github.com/tijlleenders/ZinZen/blob/main/src/App.js) imports all pages in the app.
It should only import the page required by the user - and possible pre-cache the next one as an optimization.

**Comment by pulkitvyas08** [comment]
Do we want something like lazy import?

**Comment by tijlleenders** [comment]
Yeah - I guess you can call it that.
But if we explicitly call import on files that are not required ... lazy import will not help us and still load them.

**Comment by pulkitvyas08** [comment]
Okay let me research a bit on how things work under the hood for imports like what we need and get back here

**Comment by tijlleenders** [comment]
This needs a little more thought / exploration.  
Right now we are using a single file that gets loaded on first use (webpack/vite build result).  
Being selective in which files we need for which user requires a different approach like adding a fetch request for the exceptions.  

This can always be added later.  
For now the translation files are not so big so not an issue in terms of download size.  
Adding an issue to test for a max bundle size.
