### ISSUE TITLE
Align add button to Journal in browser mode

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1653]
**Is your feature request related to a problem? Please describe.**
It's very annoying when things are not aligned.

**Describe the solution you'd like**
Align the Add button with the Journal when in browser mode (on desktop).
On mobile everything is fine.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/66c0583a-8a14-4d74-a90a-1964b020fb8c)

**Comment by realrohitgurav** [comment]
Hi! I've raised the PR for this issue. Do let me know if the changes are as requested :)

**Comment by tijlleenders** [comment]
Thanks @realrohitgurav that's great!

Please ask to be assigned the issue first next time to avoid duplicate/parallel work on an issue.
