### ISSUE TITLE
Correct font color in dark theme for Search placeholder

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1659]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you can hardly read something.

**Describe the solution you'd like**
Apply correct dark theme font color for Search bar placeholder text in dark theme.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/ce1081a1-371b-4ddb-a9b0-21d6dd33b3dd)

**Comment by kalrog-dev** [comment]
Hi I'd like to take this as my first issue. :)
