### ISSUE TITLE
control theme with css vars

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#166]
Currently the theme is controlled in the component code:
```
                    <Button
                        variant={darkModeStatus ? "brown" : "peach"}
                        size="lg"
                        className={
                            darkModeStatus
                                ? "dashboard-choice-dark1"
                                : "dashboard-choice-light1"
                        }
                    >
```

This is not necessary as components can reference the css var.
For example: "foreground-color".
Depending on the theme chosen this will change the CSS settings and thereby change the component colors.

In short: the component shouldn't have to know about the theme.

Example implementation: https://css-tricks.com/easy-dark-mode-and-multiple-color-themes-in-react/

**Comment by pulkitvyas08** [comment]
A shared partial SCSS file containing all the variables and mixins is the standard react way of doing this. @mallikarai05 you may want to explore along these lines

**Comment by pulkitvyas08** [comment]
> Currently the theme is controlled in the component code:
> 
> ```
>                     <Button
>                         variant={darkModeStatus ? "brown" : "peach"}
>                         size="lg"
>                         className={
>                             darkModeStatus
>                                 ? "dashboard-choice-dark1"
>                                 : "dashboard-choice-light1"
>                         }
>                     >
> ```
> 
> This is not necessary as components can reference the css var. For example: "foreground-color". Depending on the theme chosen this will change the CSS settings and thereby change the component colors.
> 
> In short: the component shouldn't have to know about the theme.

I don't see how that is possible as the given example is doing exactly the same thing as what we are doing

**Comment by tijlleenders** [comment]
**You are absolutely right Pulkit.**  
I was confused...  
The component should know about the theme using a state variable.  
Whenever the var is changed (ie user changes theme setting) the components using the them var will reload with react magic.
