### ISSUE TITLE
Issue about the malfunctioning 'cancel' button in the confirmation modal when deleting a goal.

### ISSUE THREAD

**Issue by siva9495** [tijlleenders/ZinZen#1669]
**Describe the bug**
@tijlleenders ,
I'm encountering an issue when deleting a goal, the 'cancel' button in the confirmation modal isn't functioning 
![Screenshot 2023-12-05 231426](https://github.com/tijlleenders/ZinZen/assets/57442699/fb6e58b4-c82c-4898-9a10-1a8651a9833f)
.

**Comment by siva9495** [comment]
@tijlleenders , can you please confirm it.

**Comment by tijlleenders** [comment]
@siva9495 Nice catch!

I confirm the bug.

**Comment by tijlleenders** [comment]
Sure thing!
