### ISSUE TITLE
Send all budgets including ancestors to scheduler

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1674]
**Is your feature request related to a problem? Please describe.**
It's very annoying when budgets don't get scheduled.

**Describe the solution you'd like**
Send all budgets, including any ancestors, to the scheduler.

**Describe alternatives you've considered**
Send only budgets without ancestors. This will give trouble in the future. The scheduler will not have enough info for nested budgets.

**Additional context**
None.

**Comment by vinaybadgujar102** [comment]
@tijlleenders I think it is already fixed in PR #1619

**Comment by tijlleenders** [comment]
Hmm... OK - there's too many PRs hanging around.  
Let's clean that up this weekend - and try to merge PRs ASAP - but at least every weekend as not everyone is available daily.

**Comment by vinaybadgujar102** [comment]
@tijlleenders i think we can close this as we are sending everything to scheduler

**Comment by tijlleenders** [comment]
Yes, agree!
