### ISSUE TITLE
Remove warning you can't add more than one contact

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1676]
**Is your feature request related to a problem? Please describe.**
It's very annoying when the UI tells you things that are not true.

**Describe the solution you'd like**
Correct the wording on 
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/ca5fa600-4a95-4172-8365-ba5e52de8f69)
- Only show 'You don't have a contact yet. Add one!' when you actually don't have a contact
- Remove the rest of the text about not being able to add more than one contact

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by siva9495** [comment]
Hi @tijlleenders , can you please assign me to this issue?

**Comment by tijlleenders** [comment]
Sure thing @siva9495 !

**Comment by siva9495** [comment]
Hello @tijlleenders, If no contacts are added, display this text "You don't have a contact yet. Add one!". If at least one contact is added, do not display the text.

**Comment by tijlleenders** [comment]
Yes @siva9495 that's correct.
