### ISSUE TITLE
Align collaboration icon

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1688]
**Is your feature request related to a problem? Please describe.**
It's very nice when things are aligned.

**Describe the solution you'd like**
Align collab icon and + button

**Describe alternatives you've considered**
None.

**Additional context**
![20231212_080358_Chrome.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/c2a28f8c-dad4-4b9a-9bea-b1008e3e5572)

**Comment by siva9495** [comment]
Hello @tijlleenders , can you please assign me on this issue?

**Comment by tijlleenders** [comment]
Of course!

**Comment by tijlleenders** [comment]
Hi @siva9495 , due to inactivity I'm moving this back to the parking lot.
It's not a problem - life happens. However I do want to free this up for someone else to be able to pick it up.

**Comment by neerajkumarc** [comment]
Hey @tijlleenders I would love to work on this.

**Comment by tijlleenders** [comment]
Sure @siva9495 !

**Comment by tijlleenders** [comment]
Sure @neerajkumarc !

**Comment by tijlleenders** [comment]
Closing this as we're changing the approach to how collaboration is shown.  
- By default goals are private, shown with a lock icon instead of a circle.
- You can share via the edit menu, anonymously or with specific contacts.
That will change the lock icon into a circle, meaning it is shared, at least anonymously.
