### ISSUE TITLE
Don't underline the space in front of a URL

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1697]
Resolves #1698 

**Describe the bug**
Whenever a URL is entered, the URL should be underlined - as it's clickable.  
Now, the space before the URL is also underlined - which looks weird.
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/d4f2a791-db01-442f-a4c5-025c2e3f385f)

**To Reproduce**

1. Create a goal with title "test test.com"
2. See error

**Expected behavior**
Don't underline the space.

**Comment by siva9495** [comment]
Hello @tijlleenders , I would like to solve this. Can you please assign me?

**Comment by tijlleenders** [comment]
Sure thing!

**Comment by tijlleenders** [comment]
Cleaning this up as already merged / resolved.
Tip @siva9495 : Adding 'Resolves #1698' to the PR description will auto-resolve it on merge of the linked PR.
