### ISSUE TITLE
Add tagline on second onboarding screen

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1699]
**Is your feature request related to a problem? Please describe.**
It's very nice when the onboarding screens are consistent.

**Describe the solution you'd like**
Add the tagline "Better together" from the first screen to the second screen also.  
Please also make the 'together' lowercaps (no capital T).

**Describe alternatives you've considered**
None.

**Additional context**
First screen:  
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/c10c678a-d66e-49af-ab24-d9ea03fe394b)

Second screen:  
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/8a2841c7-f50e-459d-bc55-0cf11b19f08b)

**Comment by siva9495** [comment]
Hello @tijlleenders, Can you please assign me to this?

**Comment by tijlleenders** [comment]
Sure thing!
