### ISSUE TITLE
Show overdue for goals with due date

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1705]
**Is your feature request related to a problem? Please describe.**
It's very annoying when I have two days left - when in fact the Goal is two days overdue.

**Describe the solution you'd like**
When a Goal is past due date, say "X day(s) ago".

**Describe alternatives you've considered**
None.

**Additional context**
![Screenshot_20231220me.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/465eadcc-ac42-4320-8242-4f8430d6c16e)

**Comment by ThomasLagace** [comment]
Hello @tijlleenders, could you assign me to this one?
