### ISSUE TITLE
Center ZinZen text logo

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1706]
**Is your feature request related to a problem? Please describe.**
It's very annoying when things are not aligned.

**Describe the solution you'd like**
Align the ZZ text logo:
![1221_205924_Chrome.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/1d7e96a6-af0c-48e7-990f-22b0a7269ab5)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ThomasLagace** [comment]
Hi @tijlleenders, can I get assigned to this one?

**Comment by tijlleenders** [comment]
Sure thing @ThomasLagace 

You can resize the text logo a bit if it touches the + button.
