### ISSUE TITLE
Singular/plural form differentiation in "days left/ago"

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1718]
**Is your feature request related to a problem? Please describe.**
It's very annoying the correct plural form is not used. #1705 was not clearly specced - and thus fixed in a way that removes the differentiation between writing "1 day ago/left" and "2 days ago/left" - and just says "day(s)" for any case.

**Describe the solution you'd like**
Use the correct spelling:  
- day when singular. 
- days when plural. 

Note: for Dutch it's dag/dagen ... so "Nog x dag(en)"/ "y dag(en) geleden"

**Describe alternatives you've considered**
None. This is a small check and improves readability a lot.

**Additional context**
![31225_073442_Chrome.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/06a83682-7548-4f02-b831-e7ecf546d5ec)

**Comment by mukul7661** [comment]
I am pretty aware how to make these changes. Please assign this to me @tijlleenders

**Comment by tijlleenders** [comment]
Nice @mukul7661 !
