### ISSUE TITLE
Note in Journal is not editable

### ISSUE THREAD

**Issue by mukul7661** [tijlleenders/ZinZen#1720]
**Describe the bug**
In Journal page, the note is not editable once saved. 

**To Reproduce**

1. Go to Journal
2. Click on edit button for any feeling
3. The note is not editable

**Expected behavior**
The note should be editable.

**Screenshots**
![Screenshot from 2023-12-26 15-06-32](https://github.com/tijlleenders/ZinZen/assets/102760496/a746b909-0aa6-4acb-8e69-1b0863d99ed0)

**Desktop (please complete the following information):**
- OS: Ubuntu
- Browser: chrome
- Version 120.0.6099.109 (Official Build) (64-bit)

**Comment by mukul7661** [comment]
Please assign this issue to me @tijlleenders

**Comment by tijlleenders** [comment]
Nice catch @mukul7661 

This was possible before ... but we didn't protect it with a regression test.
