### ISSUE TITLE
Switch to partner mode easily

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1729]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you have yo click on a small area when a bigger area is also possible.

**Describe the solution you'd like**
Increase tap area for the area to the right of the ZZ icon.

**Describe alternatives you've considered**
None.

**Additional context**
![1_072254_Chrome.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/62b43faa-0a8a-4b36-8da5-8ffc42ae463f)

**Comment by vinaybadgujar102** [comment]
@tijlleenders. Currently when the user is on the "My Goals" page and clicks the header title, they are redirected to the root My Goals page. This current functionality sends users to the goals root page when they are in subgoals. Please suggest, how this should be handled.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Thanks for mentioning that. I think that's better.  

I modifies the issue to increase the touch area of the header to take you to the root of the Goal hierarchy.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 
I believe I made a mistake reviewing this. The area of the switch to partner mode should be increased to the surrounding square area - not just the logo circle.  

I teated it on mobile (by zooming) and only the logo reacts to a click.
