### ISSUE TITLE
Clearer layout for language choice

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1731]
**Is your feature request related to a problem? Please describe.**
It's very annoying when some people are 'blind' for the language that is pre-selected. This is the first interaction with the app and should be optimized. Sone people don't read the first choice and skip over it - thinking it's the introduction to the choice menu.

**Describe the solution you'd like**
Preselect the language that is most probable at the top (radio select), but don't highlight with a background color.

**Describe alternatives you've considered**
None.

**Additional context**
![_20231231_074259_DuckDuckGo.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/16649f0d-c593-4901-89af-4fba9a444784)

**Comment by ThomasLagace** [comment]
Hey @tijlleenders, I would like to work on this one, could I get assigned?
