### ISSUE TITLE
Remove bottom popup on share

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1738]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you need four clicks to share something with a contact.

**Describe the solution you'd like**
Reduce the number of clicks needed by removing the choice between sharing 'private' and 'pseudo anonymously'.  
Go directly to where you would go if you click 'private'.  
Sharing 'pseudo anonymously' is still possible, but is now integrated with the hints feature. If you want to get hints - you automatically share the goal with ZinZen&reg; ; so pseudo anonymous.

**Describe alternatives you've considered**
None. Maybe add a Hints switch in the edit screen too... but let's take it slow.

**Additional context**
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/d7c360a4-5ebc-41ad-bd26-4976a0a86a6f)

**Comment by BogdanskiJ** [comment]
I'll try

**Comment by tijlleenders** [comment]
Sure @BogdanskiJ , thanks.
