### ISSUE TITLE
Call getHints API whenever a goal is saved and getHints are enabled

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1739]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you have a toggle to get hints ... but don't actually get any.  

**Describe the solution you'd like**
Call getHints API as shown in screenshot.  
This is the URL : https://ryah5agkswabywebsdqk7ar4om0wjdrn.lambda-url.eu-west-1.on.aws/
Only include the parent of the goal when the parent also has hints enabled!

NB: This issue is only for calling the API - not for doing anything with the result.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/745a13f8-0b44-45b7-ab4a-3b83206731d0)

**Comment by tijlleenders** [comment]
@vinaybadgujar102 yes, include the parentTitle only if hints are also enabled on the parent.  

This will allow us to crowdsource content for suggestions: if anyone ever enables hints on a goal with an identical name to parentTitle - they can get the goal title for which suggestions were previously asked.

**Comment by vinaybadgujar102** [comment]
@Tushar-4781 can we store hints field in goalCollection

**Comment by tijlleenders** [comment]
@Tushar-4781 @vinaybadgujar102 I made a separate issue #1823 to store and show the Hints.  
This issue just fetches them whenever a Goal with Hints enabled is created/edited.  
As mentioned in #1823, this is only one mechanism to call the API.
