### ISSUE TITLE
Simplify sharing menu

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1741]
**Is your feature request related to a problem? Please describe.**
It's very annoying when there is more text than necessary.

**Describe the solution you'd like**
Simplify like so:  
![3_115421_DuckDuckGo.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/a68078d4-ea9b-4a6b-bd52-8cb0176cdf3e)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Jayanth-Parthsarathy** [comment]
Hey @tijlleenders. I would love to work on this.

**Comment by tijlleenders** [comment]
Sure @Jayanth-Parthsarathy, Thanks !

**Comment by Jayanth-Parthsarathy** [comment]
Hello @tijlleenders. Please take a look at this.
