### ISSUE TITLE
Omitting Unnecessary 'on' field while creating new goal and edit/save existing

### ISSUE THREAD

**Issue by vinaybadgujar102** [tijlleenders/ZinZen#1744]
**Is your feature request related to a problem? Please describe.**
It's not necessary to save goal properties/tags it doesn't need. Goal only needs duration/ due date/ hints properties to be saved but in background other onDays property is also saved. 

NB: Maybe hints should be in a different collection?

**Describe the solution you'd like**
Do not save `onDays` property for goal - not even as null. `filters`, which `onDays` is part of, should be absent when passing to the scheduler, just like `budget` and `min_duration`.  
For existing goals, the fields should be removed entirely after an edit/save action.
The same goes for the 'filter' field in root of goal on simple goals (not as part of budgets).

**Screenshot**
![Screenshot from 2024-01-06 10-20-57](https://github.com/tijlleenders/ZinZen/assets/90821253/e32741b6-875b-418d-9520-bbe6a2207763)

**Comment by tijlleenders** [comment]
@Tushar-4781 I guess this requires a dB change?  
This is what the scheduler expects now:  
```
#[derive(Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Goal {
    pub id: String,
    pub start: NaiveDateTime,
    pub deadline: NaiveDateTime,
    #[serde(rename = "budget")]
    pub budget_config: Option<BudgetConfig>,
    pub filters: Option<Filters>,
    pub min_duration: Option<usize>,
    pub title: String,
}

```

**Comment by tijlleenders** [comment]
This does not need to be solved in the frontend.  
We can refactor the output that goes to the calendar whilst leaving this `on` field on the goal, as null or not.
