### ISSUE TITLE
Handle Possibly Null Values in timeBudget Property of GoalItem Interface

### ISSUE THREAD

**Issue by vinaybadgujar102** [tijlleenders/ZinZen#1760]
**Describe the bug**
The GoalItem interface includes a timeBudget property that consists of perDay and perWeek fields, both of type string | null. We need to handle possibly null values in the timeBudget property to avoid potential runtime errors.

**Proposed Changes:**
Don't save "timeBudget" property in "goalCollection" db if its values are undefined/null

**Comment by tijlleenders** [comment]
@Tushar-4781 What do you think of this? I don't see anything going wrong as scheduler accepts the whole timeBudget is either present or absent. If present, the fields perDay and perWeek shouldn't be null.

**Comment by tijlleenders** [comment]
@Tushar-4781 *bump*

**Comment by Tushar-4781** [comment]
yeah this inconsistency has to be removed as we have updated our edit goal flow and design. let the timeBudget field be there but the type can be converted to undefined or { perDay: string & perWeek: string }
