### ISSUE TITLE
Formatting on MyTime page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1764]
**Is your feature request related to a problem? Please describe.**
It's very annoying when important elements are less visible than less important ones.

**Describe the solution you'd like**
Switch the font color/thickness of the MyTime time and action buttons.

Also remove the last |

**Describe alternatives you've considered**
None.

**Additional context**
![_202638_DuckDuckGo.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/a4f6094f-0ee8-4aa1-813f-1547e7983754)

**Comment by Jayanth-Parthsarathy** [comment]
Hey @tijlleenders . Please assign this to me. I would like to work on this.

**Comment by tijlleenders** [comment]
Sure thing @Jayanth-Parthsarathy

**Comment by Jayanth-Parthsarathy** [comment]
@tijlleenders should we also switch the font size of the goal timing and the action buttons, or would just switching the thickness suffice?

**Comment by tijlleenders** [comment]
@Jayanth-Parthsarathy We try to avoid multiple font sizes as it makes the screen busy.  
Big and small (so 2) on any screen is a good rule of thumb. Given that, propose what feels right to you.
