### ISSUE TITLE
Open close MyTime Tasks by clicking on title.

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1765]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you expect something and something else happens. Many users expect the Tasks to open/close (uncollapse/collapse) by clicking on the title.  
Rught now clicking on the title will take you to the Goal that created the Task on MyGoals.

**Describe the solution you'd like**
Open/close Task when clicking on Task title on MyTime.  
Add a 'Goal' option in the Task options that will take you to the Goal.

**Describe alternatives you've considered**
An option modal that only opens when clicking on the Task ball. This is consistent with the My Goal page and can provide bigger buttons.  
Too much work for now?

**Additional context**
None.

**Comment by Jayanth-Parthsarathy** [comment]
Hey @tijlleenders  can you assign this to me. I would like to work on this

**Comment by Jayanth-Parthsarathy** [comment]
I assume the behavior you mean is this

![image](https://github.com/tijlleenders/ZinZen/assets/86654557/55effc66-fcfc-444a-bdc6-a44b99ec783b)

Clicking on this leads to the actual goal page instead of toggling it

![image](https://github.com/tijlleenders/ZinZen/assets/86654557/9839cb0f-8969-424b-8d93-3a866928f0e6)

Do correct me if I am wrong

**Comment by tijlleenders** [comment]
@Jayanth-Parthsarathy That's great!

Thanks for double checking. You are on the wrong page. The issue is that clicking on the green area on this screenshot should do the same as the blue area: (un)collapse.  

It does something different now.

**Comment by Jayanth-Parthsarathy** [comment]
Thanks for the clarification. I was on the wrong page, but now that I am on the MyTime page, how do I actually add tasks? I already have some goals by default in the MyGoals page, but it seems like MyTime doesn't show anything even after clicking the days.


My goals:

![image](https://github.com/tijlleenders/ZinZen/assets/86654557/ec51c2b4-86b1-4857-8e0b-b6fdf28e4ac1)

And clicking the days in the MyTime page does not open anything:

![image](https://github.com/tijlleenders/ZinZen/assets/86654557/b00a11d1-9460-4b5a-bc30-8647beafe2d5)

**Comment by tijlleenders** [comment]
@Jayanth-Parthsarathy  

The scheduler that auto-generates and auto-plans your Tasks based on the Goals is still in early stages, and breaks when you add Goals it can't (yet) handle. You probably added some Goals - and if you open the console window on browser you'll see errors from the scheduler.

Please try resetting the page (clear cache/browser data) or open it in a fresh incognito window. Then it should work.  

Hope you see the magic in a calendar as a function - but have the patience to work with an early version!

**Comment by Jayanth-Parthsarathy** [comment]
Thank you for the clarifications, @tijlleenders! No worries! The app looks fantastic ❤️.

If users want to navigate directly to the goal, should we add a feature where they can click on the button below to go to the actual goal.

![image](https://github.com/tijlleenders/ZinZen/assets/86654557/c307566a-0ec5-4a1d-8a8a-60bd13331a35)

**Comment by tijlleenders** [comment]
@Jayanth-Parthsarathy  

Right on!  
A 'Goal' option there is handy - and a better way.

**Comment by Jayanth-Parthsarathy** [comment]
@tijlleenders I have made the necessary changes. Do let me know if any changes are to be made.
