### ISSUE TITLE
Switch edit layout rows for easier access

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1774]
**Is your feature request related to a problem? Please describe.**
It's very annoying when ypu want to quickly add sonething and have to find a tiny 'enter button' on a mobile keyboard - just to find the big orange 'Make goal' button.

**Describe the solution you'd like**
Switch layout rows so 'Make goal' button is not hidden by keyboard and accessible for quick add.

**Describe alternatives you've considered**
Add a button on the title edit bar. This would reduce the space available for the title.

**Additional context**
I know clicking on the empty space above the popup also works - but it's not intuitive - and not obvious for a first user.  

![119_064533_Chrome.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/c6b1e69f-e1c3-4e9f-94c3-47cc24453081)

**Comment by harith-hacky03** [comment]
I am eager to fix it .Can you please assign me ?!

**Comment by tijlleenders** [comment]
Sure @harith-hacky03 
Thanks!
