### ISSUE TITLE
Enforce consistency in budget

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1783]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you can define an unrealistic budget.

**Describe the solution you'd like**
Avoid that you can make a budget in which:  
- the sum of all max/day is not lower than the min per week
  For example, if I have a goal of exercising 1-2 hours per day...
  ... I should not be able to set a minimum per week of more than 14h.
- sum of all min/day is not lower than the min per week - or the max per week
  For example, if I have a goal of exercising 1-2 hours per day...
  ... I should not be able to set a min per week or a max per week lower than 7  

**Describe alternatives you've considered**
None.

**Additional context**
Scheduler will panic if this happens - so best to avoid it on the input side (edit budget screen).  
This could require adapting the budgets of the default goals so that some of them have 0 as the min per day.

**Comment by vinaybadgujar102** [comment]
@tijlleenders please elaborate the issue

**Comment by tijlleenders** [comment]
You're absolutely right, this was not clear.  
I updated the description. It's a little tricky to reason about but I think I got it now...
