### ISSUE TITLE
Allow 0 as minimum budget value

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1788]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you can't set 0 as the minimum budget.

**Describe the solution you'd like**
Allow 0 in the slider as the minimum value.

**Describe alternatives you've considered**
None.

**Additional context**
The starter goals from #1787 include a goal with 0 minimum.
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/1077ba43-6224-408a-bcd6-884871e4af27)

**Comment by vinaybadgujar102** [comment]
@tijlleenders As we are allowing users to set min budget value to be 0, there is also the possibility of users setting both min-max to be zero which I think should not be allowed, right?
If yes then what message(warning) should we throw to the user

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Good point. If min is zero we can assume max to be non-zero.

No need to throw the user an error - just prevent the user from making the error.
