### ISSUE TITLE
Don't show ending hour if next starting hour is identical

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1794]
**Is your feature request related to a problem? Please describe.**
It's very annoying when there is duplicate info on a screen.  
This makes it busy for nothing.

**Describe the solution you'd like**
Don't show the ending hour if the next starting hour is the same.  
However, do show the ending hour if the next starting hour is not identical, like here:
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/0e43c6df-118a-4203-92bb-e3e7772965a6)

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/588a2962-866e-4f33-af27-41a6bb471b80)

**Comment by vinaybadgujar102** [comment]
blocked by #1772
