### ISSUE TITLE
Align + to center of action button

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1796]
**Is your feature request related to a problem? Please describe.**
It's very annoying when things are not aligned.

**Describe the solution you'd like**
Align the + to the center of the action button.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/2008f503-6a11-4bf1-b803-dc40cf7aa9bb)

**Comment by aabse** [comment]
Hi! Can I work on it?

**Comment by tijlleenders** [comment]
Sure thing @aabse !
