### ISSUE TITLE
Can't add Feeling for multiple days

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1797]
**Describe the bug**
Can't add a Feeling om two different days.

**To Reproduce**

1. Go to My feeling
2. Add something
3. Wait a day and try to add something
4. See nothing happens

**Expected behavior**
Add something two days in a row.

**Screenshots**
![_120735_DuckDuckGo.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/dc81c3cf-cbe8-450a-995e-533f04349ee5)

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Please test this without adjusting the system date. It's still not working on DuckDuckGo. I haven't tested Chrome.  

This should work in any browser - as there is no reason to rely on imperfectly supported browser features to get this working.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 
Getting errors in Chrome too:
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/05c04b75-e35f-4be2-b56f-ed9452c6161a)

**Comment by tijlleenders** [comment]
@Tushar-4781 Can you maybe advise? I'd like to have this fixed before the movie release...

**Comment by Tushar-4781** [comment]
@tijlleenders can we close this or you want to keep it open ?

**Comment by tijlleenders** [comment]
Euh... yeah thanks for checking.
Nevermind - I think this must be a Chrome incongnito-specific issue - or I was just not awake yet...

Let's see. For now I'm closing the issue again.
