### ISSUE TITLE
Wrong scheduler input

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1804]
**Is your feature request related to a problem? Please describe.**
It's very annoying when the scheduler can't do it's work because it gets the wrong input.

**Describe the solution you'd like**
When sending goals to the scheduler:
- only include the `budgetConfig` and `filters` fields if
  - `onDays`
  - `afterTime` 
  - `beforeTime`  
  are all present (non-null) in the goalCollection. 

**Describe alternatives you've considered**
Use separate types - that would impact the UI logic disproportionately.

**Additional context**
Example of field that's going wrong where budgetConfig is not present and the rest is still being sent:  
```
{
      "id": "fe365ae9-9ceb-45ea-bb05-157d1a08d76e",
      "title": "Do practice exam",
      "filters": {
        "afterTime": 9,
        "beforeTime": 18,
        "onDays": [
          "mon",
          "tue",
          "wed",
          "thu",
          "fri"
        ]
      },
      "createdAt": 1698608088628,
      "start": "2023-09-10T00:00:00"
    }
```

**Comment by vinaybadgujar102** [comment]
@tijlleenders, how can i reproduce this issue?

**Comment by tijlleenders** [comment]
@vinaybadgujar102 I realize this is only because my data still has 'residues' from the old schema. New users will not experience this. Will manually edit my backup file then!
