### ISSUE TITLE
Allow 'enter' on keyboard for saving input on browser edit screen

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1809]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you're not on mobile - and try to save a goal by pressing enter.

**Describe the solution you'd like**
Save the goal when enter is pressed while editing the title.

**Describe alternatives you've considered**
Go to the next input field. That might be better - till you reach the save input and then exit the edit screen. Let's try the direct save first.

**Additional context**
We're currently only developing for mobile - so this is low prio and only useful when testing things quickly not related to the device.

**Comment by devndevs** [comment]
I will be happy to help with this.

**Comment by devndevs** [comment]
@tijlleenders are we good to close this issue out?

**Comment by tijlleenders** [comment]
Hi @devndevs it will be auto-closed when the PR merges - since we mentioned 'resolves #' in the PR description. ;)

**Comment by tijlleenders** [comment]
Oh we didn't - yeah I'll close it.
