### ISSUE TITLE
Clicking on done Task shouldn't take me to Goal

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1811]
**Is your feature request related to a problem? Please describe.**
It's very annoying when behavior is inconsistent.

**Describe the solution you'd like**
When I click on a Task title it opens/closes the extra info (collapse).  
When I do the same thing on a done Task title it takes me to Goal - when it shoukd instead do the same as a todo Task.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by mehedihasan2810** [comment]
@tijlleenders Would like to work on this issue 
but I'm encountering an error which is coming from the scheduler
hence I am not getting the task res data.

Any idea?

The error from the console - 
`scheduler_bg.wasm:0xa1ffb Uncaught (in promise) RuntimeError: unreachable`

**Comment by tijlleenders** [comment]
@mehedihasan2810 I think the error in the console is unrelated to what you want to do. The scheduler is called to produce the Tasks from your Goals. After that Tasks are a UI/Frontend thing. The Tasks output from the scheduler is actually cached. Clicking on a Task should not trigger a scheduler run.

Please try resetting your cache if you are not seeing ant Tasks.

**Comment by tijlleenders** [comment]
@mehedihasan2810 The issue is done. Just assigned you for administrative purposes / full credits.
