### ISSUE TITLE
Restrict Goal property inheritance by subGoals to color and language

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1815]
**Is your feature request related to a problem? Please describe.**
It's very annoying when SimpleGoals and BudgetGoals get their properties mixed. Currently this is happening where BudgetGoal-specific fields like `on`, `filters` and `timeBudget` get inherited by SimpleGoals that are subGoals of that BudgetGoal.

**Describe the solution you'd like**
Only let subGoals inherit the color of the parent goal. The type (Simple/Goal) of parent or child don't matter.

The language of the created Goal is the currently selected language of the interface.

**Describe alternatives you've considered**
Make two different types. That would make UI harder as for navigation/etc it has benefits to treat them as the same type. Maybe that can be solved by having two types with a same 'hierarchy' interface - but that's beyond this issue. This is a quick fix.

**Additional context**
None.

**Comment by vinaybadgujar102** [comment]
@tijlleenders, we currently inherit 'start,' 'due,' and 'habit' from parents and have stopped inheriting 'beforeTime,' 'afterTime,' 'on,' and 'timeBudget.' from #1839. It seems you're suggesting we should only inherit 'goalColor' and 'language' for goals, but since these are automatically applied when goals are created, inheriting them might not be necessary. I believe we should only inherit properties that are related to simpleGoals.

**Comment by tijlleenders** [comment]
> @tijlleenders, we currently inherit 'start,' 'due,' and 'habit' from parents and have stopped inheriting 'beforeTime,' 'afterTime,' 'on,' and 'timeBudget.' from #1839. It seems you're suggesting we should only inherit 'goalColor' and 'language' for goals, but since these are automatically applied when goals are created, inheriting them might not be necessary. I believe we should only inherit properties that are related to simpleGoals.

Ok, so we're already on the way to reducing inheritance! 👍🏽  

- Color: I would like subGoals to have the same color as the parent. The type (Budget/Simple) of the parent and child don't matter.  
- Language: This makes sense not to inherit, actually. You are right. I'll update the description of the issue.

**Comment by tijlleenders** [comment]
The color should match the parent's in the initial add screen - but user is allowed to change that at any time.
