### ISSUE TITLE
Set dark theme as default for new users

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1820]
**Is your feature request related to a problem? Please describe.**
It's very annoying when most users prefer a dark theme and the default is light.

**Describe the solution you'd like**
Set dark theme as default for new users - from language choice onward.

**Describe alternatives you've considered**
None. We have to choose a default. Dark seems to be more in demand. You can always change it via settings.

**Additional context**
Thanks @devndevs for the suggestion.

**Comment by mehedihasan2810** [comment]
@tijlleenders Would like to solve this problem. Please assign it to me. Thanks

**Comment by tijlleenders** [comment]
@mehedihasan2810 Sorry, I think @vinaybadgujar102 beat you to it. He's a core member so can self-assign from backlog.

Anything else you would like to work on?  
There's plenty of issue on our [project board](https://github.com/users/tijlleenders/projects/4).

**Comment by mehedihasan2810** [comment]
yep didn't see that he was assigned that's why deleted the comment as soon as noticed. Ok I'm going to take a look and ping you if any issue suits me
