### ISSUE TITLE
Align Goal circles to logo

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1822]
**Is your feature request related to a problem? Please describe.**
It's very annoying when things are not aligned.

**Describe the solution you'd like**
Align Goal circles to the logo.

**Describe alternatives you've considered**
None.

**Additional context**
![20240203_214612_Chrome.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/bb876903-b62e-4f75-9acc-3f8bc3e5a345)

**Comment by tijlleenders** [comment]
Sure thing @DevDaniloFerrari , thanks!

**Comment by DevDaniloFerrari** [comment]
@tijlleenders I've created the PR.
