### ISSUE TITLE
Store and show Hints

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1823]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you call the Hints API but do nothing with the result.  
#1739 enabled getting the Hints, now we need to store and show them.

**Describe the solution you'd like**
Store all retrieved hints in a collection - and show them on the appropriate goals, just like the 'Done' drawer, but then a separate 'Hints' drawer below it.  
When clicking the Goal circle for each Hint you will have three options:  
- Accept hint
- Delete hint
- Report hint

**Describe alternatives you've considered**
None.

**Additional context**
There is still no mechanism to check for new Hints on a schedule.  
This will be implemented by a separate issue. For now, if you want to see if there are new Hints (call the fetch Hint API) - you'll need to edit the Goal for which you want Hints. In the future, there will be two triggers for calling the Hints API:  
- When creating/editing a Goal with Hints enabled
- On the Hint schedule   

The Hint schedule will have some business logic to check more frequently in the beginning - then exponentially back off if there are no new Hints found.

**Comment by vinaybadgujar102** [comment]
@tijlleenders, how should each hint be displayed in the drawer? like should it only have goal title or also a random colored circle similar to goal

**Comment by tijlleenders** [comment]
Yeah, similar to Done and Trash drawers. The circle can act as a menu for the hint options like 'Add for me', 'Hide forever', 'Report spam' etc..
