### ISSUE TITLE
Clickable element's cursor is not pointer

### ISSUE THREAD

**Issue by mehedihasan2810** [tijlleenders/ZinZen#1833]
**Is your feature request related to a problem? Please describe.**
Ex. It's very annoying when we hover over a clickable element(button) and we see it's cursor is not pointer. It is a bad accessibility.

**Describe the solution you'd like**
Make all the clickable element's cursor pointer and improve the accessibility

**Describe alternatives you've considered**
N/A

**Additional context**

https://github.com/tijlleenders/ZinZen/assets/117534561/63aeec3e-5e75-4cfc-8b16-9406cd137118

**Comment by tijlleenders** [comment]
Thanks for 'pointing' this out @mehedihasan2810 :)

I totally agree.  

However, we are focussing on the mobile experience first... so I'm going to add the low prio label.  

Of course you are (or someone else is) welcome to submit a PR, it would be appreciated!

**Comment by mehedihasan2810** [comment]
Hi @tijlleenders I am going to submit a PR for this one

**Comment by tijlleenders** [comment]
That's great!
