### ISSUE TITLE
Playwright test timing out - flaky

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1854]
**Describe the bug**
Playwright test is timing out. This is seen as a PASS in CI.  
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/9033d1e7-565b-444f-95af-2fa37fe38c24)

**To Reproduce**
See GH Action:
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/a2d6cac3-4c77-422c-9f0d-3c18af116c82)

**Comment by vinaybadgujar102** [comment]
@tijlleenders the test shows passed because as mentioned in the line 39, one test is flaky means it failed initially but passed on retry. you can refer to https://playwright.dev/docs/test-retries.

Tests sometimes fail because the elements related to sharing/collaboration feature doesn't always work as expected. For ex. when user shares a goal, the reciever should see it after refreshing the page, but this doesn't always happen. This unpredictable behavior is probably why the test passes when run again

**Comment by tijlleenders** [comment]
main branch is failing after soft delete PR. This is not a good situation. Please find a fix.

**Comment by vinaybadgujar102** [comment]
@tijlleenders the test fails when it tries to accept the changes made to the goal during collaboration. I don't know why this is happening. This works fine when I do it myself (manually), but the test isn't passing. I need to look into this thoroughly, it might take some time.

**Comment by tijlleenders** [comment]
You mean running the same test in an automated way - so not manually - works on ypur machine?

**Comment by vinaybadgujar102** [comment]
No. What I mean is that if I, as a user, perform the steps mentioned in the test manually, it works correctly. However, it does not work in the test environment. 
It is not working on my machine either.

**Comment by tijlleenders** [comment]
Ok, well then the first step is to get them working in an automated fashion on your local machine.  
- If that works, we look at the difference in run environment vs CI.  
- If not, it's the automated test that is the issue, not the environment/CI. Probably you need to add a refresh (otherwise you won't trigger fetch updates) - or add a longer wait.

**Comment by vinaybadgujar102** [comment]
I tried everything I could to make the test run correctly (added refreshes, waits, page changes, playwright version updates, etc) but it doesn't seem to work, don't know why.

**Comment by tijlleenders** [comment]
> Ok, well then the first step is to get them working in an automated fashion on your local machine.
> 
>     * If that works, we look at the difference in run environment vs CI.
> 
>     * If not, it's the automated test that is the issue, not the environment/CI. Probably you need to add a refresh (otherwise you won't trigger fetch updates) - or add a longer wait.

Does it work automated locally?

**Comment by vinaybadgujar102** [comment]
No it is not working locally also. It passes once in a while but mostly fails.

**Comment by tijlleenders** [comment]
Ok, well at least then you have a good setup to iterate possible solutions. What's the flop-rate? Does it succeed 10% or 90% of the time? Just retrying the test twice can be a workaround for now.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Can we increase the time the test is allowed to run to two minutes to see if that fixes the flaky tests?

![image](https://github.com/user-attachments/assets/4cda321a-21d7-42ef-b96d-1e00b5177bd5)

**Comment by vinaybadgujar102** [comment]
@tijlleenders, Will give this a shot.

**Comment by tijlleenders** [comment]
Closed by #2049
