### ISSUE TITLE
ESLint issues

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1864]
**Describe the bug**
After 'fixing' issues in ESLint that were only visible in the log (GitHub gave green checks) it seems that there have been a few issues that we didn't catch: https://github.com/tijlleenders/ZinZen/actions/runs/8416860179 

**To Reproduce**
See the link, 
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/c99d0882-0efc-4e38-9caa-23cd4cbdff8c)

**Expected behavior**
At least fix the errors.

**Comment by vinaybadgujar102** [comment]
fixed by #1871
