### ISSUE TITLE
Implement state for skipped Activities

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1866]
**Is your feature request related to a problem? Please describe.**
It's very confusing when you skip an Task on the Calendar - and 
- it then get crossed out, as if it was actually done
- it resets on a refresh / navigate away/come back

**Describe the solution you'd like**  
- Remember what is skipped for the current day ~~week so it doesn't reset on a new scheduler calculation~~
- ~~reduce the hours of the corresponding budget min/max per week, or goals sent to the scheduler~~
- ~~provide a global not-on to the scheduler to keep that slot completely empty~~
- reset the skipped hours at the end of the **day** ~~week~~  

**Added after discussion in PR:**  
- Don't change the information sent to the scheduler (a new calculation is not even required) - but mask the skipped Task visually in the frontend (show the slot as free even though scheduler has the Task there).
- Remove 'Skip' and 'Reschedule' as options on Tasks.
- Replace them with a 'Not now' option that opens a 'Not now' modal.
- The 'Not now' modal has the same options as current 'Postpone' modal, but an added option 'Skip' when the Task is the result of a Budget. When the Task is from a simple Goal, there is no such option.

**Describe alternatives you've considered**
None.

**Additional context**
#1400 provides a 'Reschedule' button for Tasks, next to the Skip.
We could simplify the submenu for tasks by - merging 'Skip' and 'Reschedule' into a generic 'Not now' - wand adding a skip option to the existing reschedule (renamed to 'Not now') options popup.

**Comment by tijlleenders** [comment]
@Tushar-4781 Updated description of 'Skip'.

**Comment by vinaybadgujar102** [comment]
> provide a global not-on to the scheduler to keep that slot completely empty

@tijlleenders what does global not-on mean?

**Comment by tijlleenders** [comment]
@vinaybadgujar102 It is an extra parameter to give to the scheduler, meaning 'keep these time slots completely free, nothing at all may be scheduled here'.  

Not sure if scheduler can handle it - if not we will add that.
