### ISSUE TITLE
Port Cypress tests to Playwright

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1879]
**Is your feature request related to a problem? Please describe.**
It's very annoying when we have two frameworks for tests when we can have one.

**Describe the solution you'd like**
Port all the Cypress to Playwright and delete Cypress dependency.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 I think we don't have any more tests in Cypress, right?  
Then we only need a PR to remove all Cypress mentions and dependencies to close this issue.

**Comment by vinaybadgujar102** [comment]
@tijlleenders Some tests are remaining. In #1929, only the failing test was migrated. Migrating all the tests in that PR would have made it unrelated and hard to review.
