### ISSUE TITLE
Question: Should the 'My Feelings' page be an infinite scroll

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#189]
@tijlleenders @pulkitvyas08 Need your suggestion for this

**Comment by tijlleenders** [comment]
Hi Mallika,

I have an opinion ... but the most important thing is to get a functioning
use case as soon as possible so people can actually start using it.
So I would say implement whatever is easiest for you now.

**Comment by tijlleenders** [comment]
Implementing the way that is easiest/fastest (fixed result set).   
After users start using it - we can think about a more complicated way (infinite scroll).
