### ISSUE TITLE
Typing "Test:" clears Goal input

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1891]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by khanSoliheen** [comment]
@tijlleenders , when we are trying to create a goal with any text and adds : to the end. It gets cleared after that. Am I right?

**Comment by tijlleenders** [comment]
Yeah, the text just disappears. It shouldn't.

**Comment by tijlleenders** [comment]
Probably relayed to the URL detection.

**Comment by Shubham-Praj** [comment]
Hiii @tijlleenders could you please assign this to me.

**Comment by tijlleenders** [comment]
Sure @Shubham-Praj !
