### ISSUE TITLE
Why was location state chosen over URL routes?

### ISSUE THREAD

**Issue by vinaybadgujar102** [tijlleenders/ZinZen#1898]
I have a question regarding design choice of the project. 

We heavily rely on location state to pass information in different components like:
- when clicking on task we send its id as state to navigate the related goal
-  we maintain state to check if partner mode is enabled or not. 
- to open focus timer of specific task we do the same.

Cant we replace this with routes for some functionality?
 
**Example:**  
- to see subgoals we can have route like: `http://zinzen.me/MyGoals/:goalId`
- for partner mode: `http://zinzen.me/MyGoals/partners`
- for focus: `http://zinzen.me/MyTime/:taskId/focus`

**Comment by tijlleenders** [comment]
Hi Vinay, this is a question for @Tushar-4781 
If resolved, we can add the motivation to the Architectural Decision Records (ADRs).

**Comment by vinaybadgujar102** [comment]
@Tushar-4781 Thank you for the detailed explanation. I understand the reasons behind our current approach and the considerations for the changes. We can focus on this adjustment later as suggested.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Can you make a new issue to document this as an ADR - and close this one?
