### ISSUE TITLE
Remember 'done' state for today when Goal is completed.

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1903]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you mark a Task done, which can mark a Goal done - and then the hours you spent on it (and the crossed out title) disappear from your today timeline, replaced by other (new) things to do during those hours.

**Describe the solution you'd like**
Send any completed Goals for which there is a Task done today to the scheduler - as if it were a Goal not yet completed.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by vinaybadgujar102** [comment]
@tijlleenders According to my understanding, for a particular goal (not budget), there is a task scheduled. If I mark the task as done and also mark the related goal as done on the Goal Page. This goal should then be sent to the scheduler, which is currently not happening. Right?

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Let's implement #1407 first before getting into the details of this one.  
There might be a different way of achieving the same result.

**Comment by tijlleenders** [comment]
Blocked by #1918

**Comment by tijlleenders** [comment]
Changed the approach for this. We are informing the scheduler of the done Tasks for today in #1407 , so that the scheduler can place them in the same spot (preferably marked as done) - and adjust budgets accordingly https://github.com/tijlleenders/ZinZen-scheduler/issues/466 .
