### ISSUE TITLE
Remove auto-capitalization from Goal title

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1927]
**Is your feature request related to a problem? Please describe.**
It's very annoying when your goal title is auto-capitalized on every word. This haopens in the title of the goal, when showing the subgoals for that goal.

**Describe the solution you'd like**
Don't affect capitalization.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Shubham-Praj** [comment]
Hii @tijlleenders please assign this to me

**Comment by tijlleenders** [comment]
Great @Shubham-Praj !
