### ISSUE TITLE
Autocomplete title based on Archive goals

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1930]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you have lots of (recurring)  shopping list items in archive - and you have to search for it manually, not sure if it was already in the archive. If you don't check - you have to type more and also get duplicates.

**Describe the solution you'd like**
While typing a goal/budget title, search the archive for the first archived goal/budget with the same starting characters.
If found, show the rest of the text from the archive to the right of the cursor, in a lighter/placeholder color.
When tapping to the right of the cursor on the autosuggestion, remove the goal/budget from archive and complete all element (title/options) in the modal based in the archive.

**Describe alternatives you've considered**
Show a list when multiple matches. Confusing and more complicated. Just show the first match.

**Additional context**
None.

**Comment by vinaybadgujar102** [comment]
@tijlleenders should this work both for adding new goals and editing existing ones?

**Comment by tijlleenders** [comment]
In dev this works, but the Goal stays in 'Done' ; a refresh is needed to make it active.  
It also shows a toast for Goal updated, instead of Goal (re-)created.

**Comment by vinaybadgujar102** [comment]
> In dev this works, but the Goal stays in 'Done' ; a refresh is needed to make it active.

@tijlleenders, please provide screen recording for this, I am not able to reproduce it.

> It also shows a toast for Goal updated, instead of Goal (re-)created.

So the toast should display "Goal (re)created". Right?

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Here you go:  
/home/tijl/Videos/Screencasts/Screencast from 2024-09-20 12-46-38.webm 

I also noticed that clicking on the text is necessary. Previously that was not the case, clicking anywhere on Goal title area would complete the goal.

**Comment by vinaybadgujar102** [comment]
@tijlleenders,

> In dev this works, but the Goal stays in 'Done' ; a refresh is needed to make it active.

I couldn't reproduce the issue. Could you please verify if it's still occurring?

**Comment by tijlleenders** [comment]
Yes on dev a refresh is still needed. This is not acceptable.

Also the suggestions seem to search ALL goals, when keeping them restricted to children of the current parent is more useful.
