### ISSUE TITLE
Add a Goal from My Time page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1958]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you open the app to quickly add a Goal, and first have to switch to My Time page to add a Goal.

**Describe the solution you'd like**
- Add a '+' button on the My Time page, just like on My Goals.
- When adding a Goal via My Time page, don't leave the My Time page - just show the add Goal modal
- When saving, regardless of where you are in the Goal hierarchy on the My Goals page, since you added via My Time in a hurry, there is no reasonable place to put it, other than the root level.  
This way you can add quickly, even on My Time, and sort out where you want it in you hierarchy later.

**Describe alternatives you've considered**
None.

**Additional context**
#1957 Needs to be done first.

**Comment by vinaybadgujar102** [comment]
Should the user be able to add only simple goals, or should they also have the option to add budgets?

**Comment by tijlleenders** [comment]
@vinaybadgujar102 #1957 has already made an option to add a budget via a long press. No extra work should be required. I don't see a use case for quuck-adding a budget - but it can't hurt to support this from a consistency of UI point of view. If used, the budget will go in root.
