### ISSUE TITLE
Clicking Goal doesn't work on desktop (develop branch)

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1976]
**Describe the bug**
Can't go to subGoals on desktop.

**To Reproduce**
1. Open develop on desktop
2. Try going into 'Daily habits'
3. See error

**Expected behavior**
Go into a Goal when it is clicked.

**Screenshots**
On request.

**Additional context**
We used to only mind mobile, but the time is right to minimally support desktop ... as the syncing feature is near.

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders  Have seen where the issue is on that. Ill get create pull request for it.

**Comment by tijlleenders** [comment]
Closed by #1982
