### ISSUE TITLE
Bug: new create goal modal incorrectly prefilled with data from previous edit goal session (develop)

### ISSUE THREAD

**Issue by vinaybadgujar102** [tijlleenders/ZinZen#1979]
**Describe the bug**
When editing a goal, its options are usually prefilled in the config goal modal. However, if the config modal is closed and a new goal is added, it gets incorrectly prefilled with the options of the goal which was previously opened for edit.

**Screenshots**
[Screencast from 26-07-24 01:40:24 PM IST.webm](https://github.com/user-attachments/assets/78a7729b-2557-46bf-9593-c4a16a238a27)

**Comment by tijlleenders** [comment]
Nice catch. It helps when you show your cursor in screencasts ;)

**Comment by vinaybadgujar102** [comment]
@tijlleenders I am not able to reproduce it anymore.

**Comment by tijlleenders** [comment]
Then it is resolved.
