### ISSUE TITLE
Creating sub goal/budget causes error

### ISSUE THREAD

**Issue by vinaybadgujar102** [tijlleenders/ZinZen#1987]
**Describe the bug**
After creating sub goal/budget, app breaks.

**Screencast**
[Screencast from 26-07-24 08:31:05 PM IST.webm](https://github.com/user-attachments/assets/3a08d3b8-ce06-4f73-885d-193e6e67b3ea)

**Console Error**

![Screenshot from 2024-07-26 20-34-50](https://github.com/user-attachments/assets/a5efc238-3f07-48c9-add1-8db0a6fdffb2)

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Can you be a bit more specific by adding a screencast and console errors?  
Or are you now busy implementing the fix already?

**Comment by vinaybadgujar102** [comment]
> @vinaybadgujar102 Can you be a bit more specific by adding a screencast and console errors? Or are you now busy implementing the fix already?

updated the description

**Comment by Nicholas-Kipkoech** [comment]
@vinaybadgujar102 I noticed this issue today, was this working on main branch?

**Comment by tijlleenders** [comment]
@Nicholas-Kipkoech You can test this yourself, locally or on ZinZen.vercel.app  ;)
