### ISSUE TITLE
Sorting subgoal errors out the app

### ISSUE THREAD

**Issue by vinaybadgujar102** [tijlleenders/ZinZen#1988]
[Screencast from 26-07-24 08:07:06 PM IST.webm](https://github.com/user-attachments/assets/b2f13aa6-a707-4e5d-8b35-0b92019ecfcf)

**Comment by vinaybadgujar102** [comment]
@Nicholas-Kipkoech have you started working on this?

**Comment by Nicholas-Kipkoech** [comment]
Yes, incase of any issue ill tag you along.

**Comment by Nicholas-Kipkoech** [comment]
@vinaybadgujar102 Can you take over this?
