### ISSUE TITLE
Completing starter goals gives weird outcome

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1989]
**Describe the bug**
Something goes wrong when completing multiple goals.

**To Reproduce**
[Screencast from 2024-07-26 16-58-25.webm](https://github.com/user-attachments/assets/3bfa1e88-7057-4104-b1bb-72c02dfe0d00)
No console errors.

**Expected behavior**
Completing multiple goals should archive all of them.
They should only be visible in the Trash of the Goal they were in.

**Additional context**
None.

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders Have tested this and it seems to be working fine.

**Comment by Nicholas-Kipkoech** [comment]
Seems the issue is in the subgoals.

**Comment by tijlleenders** [comment]
@Nicholas-Kipkoech Maybe better to skip this until @vinaybadgujar102 finishes #822

**Comment by vinaybadgujar102** [comment]
@tijlleenders, I think has been resolved

**Comment by tijlleenders** [comment]
Yes, closing this as I can't reproduce this in `develop` branch.
