### ISSUE TITLE
Restoring from done missing

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#1991]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you want to restore from done, and it's missing.

**Describe the solution you'd like**
Implement restore from done, just like it is done in the main branch, adapt if needed:  
![image](https://github.com/user-attachments/assets/a16067b1-cfb2-4bd4-91f5-c2c51561cb40)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders I have debuged this and it seems that the goal is not updated on the db when you complete it as done

**Comment by vinaybadgujar102** [comment]
@tijlleenders, this is resolved by Tushar in latest commits to develop branch

**Comment by tijlleenders** [comment]
@vinaybadgujar102 Not entirely. There are still bugs. Start fresh on develop, go to Daily habits, delete a Goal.  
No trash shows up. You could say it's a different issue - but it"s required to get to a  restore.
