### ISSUE TITLE
Breadcrumb only shows latest level down

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#2003]
**Describe the bug**
In main the breadcrumb is working. In develop branch it isn't.

**To Reproduce**

1. Go to Daily Routine, then Lunch
2. See 'Daily routine' is not in the breadcrumb

**Expected behavior**
See 2.

**Screenshots**
None.

**Additional context**
None.

**Comment by Nicholas-Kipkoech** [comment]
@tijlleenders This also should be resolved in #2002

**Comment by tijlleenders** [comment]
@Nicholas-Kipkoech Why? The PR has been merged already - so it's possible to separate the issues. 

Please make a new PR for this issue.
