### ISSUE TITLE
Highlight extra stars

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#2030]
**Is your feature request related to a problem? Please describe.**
It's very annoying when people leave feedback without giving a star rating. Out of all people leaving feedback, 99% don't give stars other than the default three stars.

**Describe the solution you'd like**
Show a clear outline on the stars, so they don't blend into the background. My hypothesis now is that the stars are not clicked because it is not visible that there are more than three stars.

**Describe alternatives you've considered**
Changing the layout to explicitly ask for a star rating. This makes the barrier to giving feedback higher, and is not worth it. If people are OK with the default three stars, don't add extra clicks.

**Additional context**
![image](https://github.com/user-attachments/assets/60d6e85f-36e0-4dcd-ba4b-6b0a8048dbda)
![image](https://github.com/user-attachments/assets/c4a48869-1ed1-4bba-b37f-5ed12fd7719b)

**Comment by codervinod123** [comment]
@tijlleenders please assign to me

**Comment by tijlleenders** [comment]
Thanks @codervinod123 !

**Comment by codervinod123** [comment]
@tijlleenders is there any setup guide?
