### ISSUE TITLE
Remove % done bar from UI and code

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#2046]
**Is your feature request related to a problem? Please describe.**
It's very annoying when the screen is cluttered. The % done was a nice experiment, but it's better to visually implement this on the existing day bar itself.

**Describe the solution you'd like**
This issue is just for removing the %done bar from the UI and code.  

**Describe alternatives you've considered**
We're keeping it - but will find a way to superpose this information on the existing day bar.

**Additional context**
You can see the grey %done bar here:  
![image](https://github.com/user-attachments/assets/79732ad4-cefa-45f3-9b91-554a8683c86c)

**Comment by codervinod123** [comment]
@tijlleenders please assign to me.

**Comment by tijlleenders** [comment]
Allright @codervinod123 !

**Comment by codervinod123** [comment]
@tijlleenders by mistake i have removed the assignment to me , i will make sure i would not happen in future
