### ISSUE TITLE
Close any modal on desktop using 'escape' key

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#2052]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you're using keyboard only to add some goals, tap 'enter' by accident - and then have to grab the mouse/pen to close a modal

**Describe the solution you'd like**
When any modal is opened - 'escape' key will close it.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by aarifkhan7** [comment]
Hey

I'm a beginner interested in contributing to open source, and this issue seems like a good starting point for me. Could you please assign it to me?

Thanks!

**Comment by tijlleenders** [comment]
Sure thing @aarifkhan7 

If you read through the documentation there's a howto on how to setup the project locally, as well as how to fork/PR back.

**Comment by aarifkhan7** [comment]
Thanks for the info! I'll set things up on my end and try to replicate the issue.

Thanks, I appreciate your guidance!
