### ISSUE TITLE
Open modal for goal with 'spacebar' key.

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#2053]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you're used to using 'spacebar' to click on things - and it doesn't work.

**Describe the solution you'd like**
When navigating through goals using the keyboard, pressing 'spacebar' key will go into the highlighted goal, just like tapping/clicking.

**Describe alternatives you've considered**
Using 'enter' key - but this is reserved for quick-adding goals.

**Additional context**
None.

**Comment by harshalranjhani** [comment]
hi can you please assign this issue to me?

**Comment by tijlleenders** [comment]
Yeah, great!
