### ISSUE TITLE
Replace 'are you sure' modal with Toast for deletion

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#2054]
**Is your feature request related to a problem? Please describe.**
It's very annoying when you're testing to have to click the 'don't show this again' every time you refresh the app state.

**Describe the solution you'd like**
Just show a Toast with message  
"Moved to Trash!  
We'll delete it in 7 days."

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://github.com/user-attachments/assets/205dfed7-7c06-4e9a-9ac4-635a179592b4)

**Comment by harshalranjhani** [comment]
hii can you please assign this issue to me?

**Comment by vinaybadgujar102** [comment]
Sure!
