### ISSUE TITLE
Remove the duplicate code from GoalsPage.scss

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#2070]

**Comment by Shifra-fraiman** [comment]
Hi @tijlleenders,
I would like to do it,
Please assign this issue for me.

**Comment by tijlleenders** [comment]
@Tushar-4781 Are you already working on this?

**Comment by tijlleenders** [comment]
> Hi @tijlleenders,
> I would like to do it,
> Please assign this issue for me.

Sure thing @Shifra-fraiman , thanks!

The dev setup and fork guide is in the docs, if needed.

**Comment by vinaybadgujar102** [comment]
resolved by #2071
