### ISSUE TITLE
Need to refresh twice to receive a sharing update

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#2075]
**Describe the bug**
Need to refresh twice to receive a sharing update.

**To Reproduce**
See video.

**Expected behavior**
Updates should come trough upon a refresh, at least.

**Screenshot**
[Screencast from 2024-11-08 08-32-45.webm](https://github.com/user-attachments/assets/8d7c6ca6-e401-492c-82b6-5d159db9bcd3)
creenshots**

**Additional context**
There is a related issue to improve checking for updates periodically with exponential back-off #2074

**Comment by arashveysi3** [comment]
working on it

**Comment by tijlleenders** [comment]
That's cool @arashveysi3 - thanks for checking first.  

Let us know if you need help.  
Basic forking/dev setup is in the docs, in case you need it.

**Comment by tijlleenders** [comment]
@vinaybadgujar102 FYI this is in progress.

**Comment by arashveysi3** [comment]
just made a pull request. please check and let me know Dear @tijlleenders
