### ISSUE TITLE
code backsticks (```) are visible in task title

### ISSUE THREAD

**Issue by vinaybadgujar102** [tijlleenders/ZinZen#2088]
**Describe the bug**
Currently if user types goal title wrapped in 3 backticks it is considered as a code block in the app. The backticks are not visible in goal title but they are in associated task title.

**Expected behavior**
@tijlleenders please update this with the expected behaviour

**Screenshots**
![image](https://github.com/user-attachments/assets/949e7dd1-0d26-4df9-9825-e73808a55aa1)

**Comment by tijlleenders** [comment]
Nice catch @vinaybadgujar102 .

The way I think about it is that code snippets you want to copy/paste should never have a duration - and thus will never be seen in the calendar. The example you made is not realistic in my opinion.  

I feel the best way to go about this is just let it be, unless you have a better suggestion.
