### ISSUE TITLE
Enable install to iOS

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#209]
A PWA should be installable to iOS phones.

**Comment by Tushar-4781** [comment]
@tijlleenders can we close this ?

**Comment by tijlleenders** [comment]
No, it is still important to do at some point but I'll add a low prio label

**Comment by Tushar-4781** [comment]
@tijlleenders #678 is duplicate of this ig ?

**Comment by tijlleenders** [comment]
Yes this is a duplicate.
