### ISSUE TITLE
Remove dots at ends of timeline

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#2091]
**Is your feature request related to a problem? Please describe.**
It's very annoying/confusing when you think something is a handle you canbclick/move - and it is not.

**Describe the solution you'd like**
Remove the 'dots' at the ends of the timelines.

**Describe alternatives you've considered**
None.

**Additional context**
![IMG_20241215_093144.jpg](https://github.com/user-attachments/assets/c634499b-bc31-449d-bd7b-7e80bd3a9362)

**Comment by jeyasimma** [comment]
Could you assign it to me , I will try to Remove dots at ends of timeline...

**Comment by tijlleenders** [comment]
Sure thing @jeyasimma , thanks!

The docs have technical forking/setup help. Let us know if you need anything.

**Comment by jeyasimma** [comment]
okay, 
![Screenshot 2024-12-21 195415](https://github.com/user-attachments/assets/5b908e14-2a3d-4c16-92a3-4d6e48f8650c)
where I saw the timeline page to set the time between, it did not show the time between it showed duration. 
![Screenshot 2024-12-21 201701](https://github.com/user-attachments/assets/59d16a05-6a4b-4006-8b37-c73100328b51)

**Comment by tijlleenders** [comment]
Sorry about that, it is hidden behind a long press on the + , then add Budget.

Alternatively you could edit one of the default goals, like 'Work'.

**Comment by jeyasimma** [comment]
it's okay could you tell me the exact file that you code for this page and timline

**Comment by tijlleenders** [comment]
Sure, I think that's https://github.com/tijlleenders/ZinZen/blob/main/src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx but I'm not a TS expert so I could be wrong...

**Comment by jeyasimma** [comment]
![WhatsApp Image 2024-12-23 at 9 15 50 PM](https://github.com/user-attachments/assets/61b162a3-5e02-4544-869e-622e64d84721)
Is this okay or not ?

**Comment by vinaybadgujar102** [comment]
<img width="375" alt="image" src="https://github.com/user-attachments/assets/cc6373e1-7729-4507-a5e9-8458d1d74b92" />

@jeyasimma its expected to look like this as described in issue
@tijlleenders please confirm

**Comment by jeyasimma** [comment]
Ooh sorry I will correct

**Comment by jeyasimma** [comment]
![WhatsApp Image 2024-12-23 at 10 13 57 PM](https://github.com/user-attachments/assets/9fc66167-fbb2-4712-bce3-9e942270f528)
okay?

**Comment by tijlleenders** [comment]
Yeah, well done @jeyasimma 

Let's move to code review.

**Comment by jeyasimma** [comment]
It's okay , review it 👍

**Comment by tijlleenders** [comment]
I'm sorry @vinaybadgujar102 but this implementation seems problematic.  
There seems to be a lot of re-rendering going on, and the mouse-over is way off position. I recorded both in desktop mode - and in mobile mode:  
[Screencast from 2024-12-24 08-26-07.webm](https://github.com/user-attachments/assets/036a8006-98df-4337-bfc7-2e18c10ab538)

I´m keeping this issue open, and reverting the PR.

**Comment by vinaybadgujar102** [comment]
@tijlleenders yeah. I also saw this re-rendering problem. but it's not introduced by this changes. They only changed css. I was going to create issue for this.

**Comment by tijlleenders** [comment]
Ok, go ahead. Closing this.
