### ISSUE TITLE
Make design for add goal page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#213]
Design the add goal page.  
There should be a text box to enter something.  
Suggestions can appear to add special fields.  

Initial thoughts to get started: 
![image](https://user-images.githubusercontent.com/44887755/162416318-98a832df-c692-4f85-9dc0-017159707a3c.png)
  
Colors and personalization are an important part of making the goal hierarchy quickly navigable (memory palace). There should be a default color(s) based upon the color of the parent(s). For now we are only adding one layer (no hierarchy) so every added goal will have a new randomized color (like when creating a new GitHub label but without the popup?).

**Comment by mallikarai05** [comment]
The 'Add Time' can be an optional entry. Is there anything else? 
You get to this page after clicking the 'plus button' next to my goals (similar to how it works for my feelings). When you click on 'My Goals' you get a list of goals, with random colors.
![image](https://user-images.githubusercontent.com/73054648/164877843-a6f8269b-25a9-4185-9ef7-b2a426681126.png)
![image](https://user-images.githubusercontent.com/73054648/164878013-c153665a-259f-410c-bd32-57df9723ad08.png)

**Comment by tijlleenders** [comment]
Sorry for not being clearer in the description.  

"Suggestions can appear to add special fields." => if someone types 'Walk 30m daily' there should be a suggestion to turn 30m and daily into 'duration:30m' and 'repeat:daily' key-value pairs stored with the remaining "walk" title in the repository.  
The question is : how is this transformation visually suggested to the user? How is it shown when user decides to apply the transformation?  

"There should be a default color(s) based upon the color of the parent(s)." => How is the chosen color shown to the user? In the background of the typing area and as a key-value pair?

**Comment by tijlleenders** [comment]
Also, how do you confirm you're done (save)? 
How do you cancel?

**Comment by tijlleenders** [comment]
Mallika will add some new designs today.

**Comment by mallikarai05** [comment]
I have worked on 3 designs, combining them this seems the best fit in terms of user experience and convenience. (the other ideas include providing additional options like if the duration entered in 30 minutes to provide options like '1 hour', or setting a fixed time for the task if necessary)
![image](https://user-images.githubusercontent.com/73054648/166138152-b4ea0f90-3fb8-4ea9-be4b-927e04ad2615.png)
![image](https://user-images.githubusercontent.com/73054648/166138161-29cc98ac-9a36-4353-ba0c-e376db41bdfa.png)
If we need to add something or change it let me know.

**Comment by tijlleenders** [comment]
Looking good!
Can I suggest to make the input box already in the color it will appear in
later?
The current color can be a badge like the daily. By clicking the color you
can cycle through the colors, similar to tags on GitHub:
[image: image.png]

**Comment by tijlleenders** [comment]
Looking good!
Can I suggest to make the input box already in the color it will appear in
later?
The current color can be a badge like the daily. By clicking the color you
can cycle through the colors, similar to tags on GitHub:
![image](https://user-images.githubusercontent.com/44887755/166146067-43e0640c-a89b-4059-b0e3-b76341b69d21.png)

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/166742920-b4e4d3b8-e2ae-49bb-b2e2-e59ac1e2557a.png)
