### ISSUE TITLE
Find two people to work on the project bigtime during june/july

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#235]
Two weeks to find them.
Two weeks to get familiar with the project.
June + July = summer of ZinZen

**Comment by mallikarai05** [comment]
@tijlleenders I think we have enough people to work on the project right now. Can we close this issue?

**Comment by tijlleenders** [comment]
Thanks for the effort @mallikarai05 !
... and keep your eyes and ears open ... success = opportunity * preparation
