### ISSUE TITLE
Make design for the 'Explore' page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#241]
The explore page is where you can browse plans to achieve goals that other people have shared.

The first page is high level categories.
![image](https://user-images.githubusercontent.com/44887755/165918436-6a2f7c54-1f3a-4348-9d7d-302f07a435cb.png)

It would be nice to have pictures as well as titles.
Pictures should not be licensed or should be created by us.

**Comment by tijlleenders** [comment]
Some inspiration : https://youtu.be/ouyuO04yXO8

**Comment by Tushar-4781** [comment]
![image](https://user-images.githubusercontent.com/39093015/166790572-6efc57d5-c4a5-44e1-87b7-475d50537f1d.png)
![image](https://user-images.githubusercontent.com/39093015/166791332-0027ed1d-8fd0-48ef-8923-a96b29a51526.png)
![image](https://user-images.githubusercontent.com/39093015/166791587-f582c8e7-c081-489e-9964-b818c540797f.png)
![image](https://user-images.githubusercontent.com/39093015/166792721-a585c22c-33b6-43ea-85bd-87a59b6c1b20.png)
![image](https://user-images.githubusercontent.com/39093015/166794704-6cc2ea52-688e-4b60-9ca5-490cec054ee3.png)
![image](https://user-images.githubusercontent.com/39093015/166795127-45632dc1-e43f-4d3a-8231-dae251be5650.png)
![image](https://user-images.githubusercontent.com/39093015/166795243-07b1489a-9355-4307-abd3-aa06e94fedcd.png)
![image](https://user-images.githubusercontent.com/39093015/166796513-ad0fbe97-af79-47eb-ab95-d9e629df5b5b.png)
![image](https://user-images.githubusercontent.com/39093015/166796708-bb6fa712-489f-4c06-9542-4914749e0869.png)

**Comment by Tushar-4781** [comment]
![image](https://user-images.githubusercontent.com/39093015/166800088-f4a134ef-11a9-43f7-9fda-ab124fca6720.png)

**Comment by mallikarai05** [comment]
Hi, this looks good. 
I'm not sure about the colors though, also can you please share the link to the Figma board you are working on?

**Comment by Tushar-4781** [comment]
Hi @mallikarai05, actually I was working on the layout first. Styling can be done once the layout is finalized. You can check the designs below

figma link - https://www.figma.com/file/V8bJoZRlagnELqmhV3Q4Cb/Untitled?node-id=0%3A1

**Comment by tijlleenders** [comment]
![Screenshot_20220505-131813_DuckDuckGo.jpg](https://user-images.githubusercontent.com/44887755/166912750-14d1abdf-4328-4959-8431-76d6192c8624.jpg)

I like this one best.

We're focussing on mobile for now.

**Comment by tijlleenders** [comment]
In practice, the + button is only needed at the level where you can add a plan. "Career goals" is not something you can add - but "Get a promotion" is.

**Comment by Tushar-4781** [comment]
Yeah for that I designed on of the screen where there is a drop down so thing is you can jump to different categories like "career goals" can have different scenarios so those can be listed below ( without + button )  or another way could be if you scroll down you will be in same category like assuming a category "party" so there can be multiple scenarios birthday, anniversary etc but if you do right swip then you will switch to another category like from party -> career goals ( same can be done by choosing category from drop down menu ). so a little bit more details are required.

**Comment by tijlleenders** [comment]
It's an collaborative exploration :)

Good for now!

**Comment by tijlleenders** [comment]
@mallikarai05 Any comments before we close this?

**Comment by tijlleenders** [comment]
For future reference all the designs: 
![Screenshot_20220505-134617_DuckDuckGo.jpg](https://user-images.githubusercontent.com/44887755/166916849-aad4bedf-1401-4ab5-93b9-9533f9a2d619.jpg)

**Comment by Tushar-4781** [comment]
Hi @mallikarai05, I think you can carry it out from here. I have just done the layout part. There is still more like styling and especially choosing up right images and all that. Maybe you can handle the other half better than me because I m very poor in styling. :_ ).

**Comment by mallikarai05** [comment]
I made a few changes to the page to match the current theme and color palette, will this be okay?
![image](https://user-images.githubusercontent.com/73054648/167256934-bfc2bd43-7586-4012-8fcf-4271c680f979.png)

**Comment by tijlleenders** [comment]
Looks great @mallikarai05 !

So clicking on it will go the the list of plans you can add to the calendar?

Ok for now.
I'll make an issue to come up with a list of plans (just titles) per category and another issue to implement the pages.

**Comment by mallikarai05** [comment]
@tijlleenders yes, that was the idea!

**Comment by Tushar-4781** [comment]
nicely done @mallikarai05 
Suggestion: Is there something we can do for that padding on the left, right, and bottom? There is a sense of emptiness.

**Comment by Tushar-4781** [comment]
@tijlleenders,  I have 3 points that need to be taken care of before we work on this design:

1. We need relatable pictures for goals ( **Not licensed**/**self-created** as mentioned by you earlier ). 
2. What about the UX like how scroll will happen left swipe or scroll down ?
3. These are the goals for now that we have to list?
![image](https://user-images.githubusercontent.com/39093015/167288009-09141c2c-44f8-4878-a353-7ea4316a7d9e.png)

**Comment by tijlleenders** [comment]
1+2 @mallikarai05 can you specify this in the related design issue?

3. Yes, this is thr list of categories we're going with for now.

**Comment by mallikarai05** [comment]
@tijlleenders If needed I can create something that can be used for the goals instead of images if required, we always have an option to just use emojis/smiley faces instead. 
And for the UX, I think it's better to scroll down.
@Tushar-4781 thanks for the pointers!

**Comment by tijlleenders** [comment]
Images is fine for now. Using images from Unsplash will go faster than creating it yourself.  

Just paste the Unsplash links for each image and Tushar can take it from there.

**Comment by mallikarai05** [comment]
Adding the links for the images here.

Relationship goals: [https://unsplash.com/photos/AsahNlC0VhQ]

**Comment by mallikarai05** [comment]
Adding the links for the images here.
[Relationship goals](https://unsplash.com/photos/AsahNlC0VhQ)
[Health and fitness goals](https://unsplash.com/photos/6WrKKQcEnXk)
[Mind and spirit goals](https://unsplash.com/photos/NTyBbu66_SI)
[Career goals](https://unsplash.com/photos/zEqkUMiMxMI)
[Nature and environment goals](https://unsplash.com/photos/eOpewngf68w)
[Personal growth and learning goals](https://unsplash.com/photos/DUmFLtMeAbQ)
