### ISSUE TITLE
Fix jerky and slow page loading

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#248]
**Something is wrong with the way new pages are loaded; it feels like a browser refresh.**
We are using create-react-app PWA as a template - which I believe is considered a single page app (SPA).

One of the things I expect from an SPA is that screen changes do not feel like a browser refresh.  
This is what is happening now:  
1. I see this page  
![image](https://user-images.githubusercontent.com/44887755/166098204-962042ee-1e07-406e-ae9d-afd6d0795244.png)

2. Then I see this page  
![image](https://user-images.githubusercontent.com/44887755/166098299-fcf9fd3e-4e22-4dbb-a0e8-dbd8a52d5923.png)

3. I have the feeling I just experienced a browser refresh.  

It is quite fast, so for the details to be clearly seen you need to:  
1. Open Developer Tools (press F12)
2. Go to the network tab
3. Click 'No throttling'
4. Select 'Slow 3G'
5. Click the ZinZen logo to 'reload' the page

![image](https://user-images.githubusercontent.com/44887755/166098414-03e79cfb-bfcb-43d2-b74a-1fe2d065dcac.png)

One thing that might fix this is #231 - as loading from cache might make the above changes so fast that you can't consciously see them ; but maybe there is something else that can be done too to eliminate this two-step process altogether?

**Comment by pulkitvyas08** [comment]
Facing the same issue. It needs to be mentioned that we are no longer using the webpack as the module bundler for this application. Vite has replaced it for that. So from what I can infer this is Vite's HMR (https://vitejs.dev/guide/api-hmr.html) related issue. Looking into the potential causes.
