### ISSUE TITLE
Stars on feedback page not working properly

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#262]
When selecting 5 stars, then 4; it doesn't work.

Additional fix: the default stars should be 5.

**Comment by Tushar-4781** [comment]
@tijlleenders you mean that on the front end we have to show the default Rating as 5 stars?

**Comment by tijlleenders** [comment]
Yeah, that way a low rating is FOR SURE intentional, not an oversight.

**Comment by tijlleenders** [comment]
...and 5 is what we're aiming for.
