### ISSUE TITLE
Feedback page should not refresh

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#265]
Right now the feedback page refreshes.

You can see this clearly by opening developer tools (F12) and setting the network speed to 'Slow 3G' on the network tab.

![image](https://user-images.githubusercontent.com/44887755/166874429-07d5570c-81e1-4fb6-8d02-959b082d7aa3.png)

**Comment by GithinjiHans** [comment]
Already handled it.
