### ISSUE TITLE
Save feelings on click and take to dates page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#275]
Using the API from #117 still need to save the feelings and take the user to an overview page.

**Comment by pulkitvyas08** [comment]
The work from #274 indeed saves the feelings. You can check it in the indexedDB section of `developer tools -> storage`. Attaching a screenshot for the same.

![image](https://user-images.githubusercontent.com/54947769/167106295-75a9aff6-e56d-4aa0-ad9f-113f6d097cca.png)

**Comment by pulkitvyas08** [comment]
I think the issue must be that the same is not happening for small screens (mobiles and tablets) because I forgot to add the save function on clicking the tiles there. I will do that in this issue and then make a new one for removing the added feelings

**Comment by pulkitvyas08** [comment]
Also you can view the saved feelings by clicking the `My feelings` button on the dashboard, the rendering might not be fixed right now but I'll resolve that soon

**Comment by tijlleenders** [comment]
Yeah, it works, closed by #281
