### ISSUE TITLE
make design to ask the reason of selected feeling from user  

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#276]
When the user clicks on any feeling, a small pop-up should appear where the user can type about the moment or incident that made him/her feel that way.

**Comment by mallikarai05** [comment]
This is how presently the 'My Feelings' page looks, the additional plus button next to the feeling can be used to add the reason for a particular feeling
![image](https://user-images.githubusercontent.com/73054648/167775821-48ed0afc-a9a5-4480-95d8-9e493262fc5c.png)
After you click the plus button-
![image](https://user-images.githubusercontent.com/73054648/167776494-6866f3cc-3295-4627-9d3b-3805ba3aface.png)

**Comment by tijlleenders** [comment]
We could add a camera icon so you can take a picture - or attach from your gallery (technically possible using browser WebAPI)?

**Comment by mallikarai05** [comment]
That is a good idea. If we can attach an image I'll add an option for it to the design?
