### ISSUE TITLE
Make a collage of the feelings

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#277]
After hitting a certain threshold like having 20-30 feelings ( with **note** ), the homepage background should become editable where the user can change it to a collage of all those notes that were written while adding feelings.
For inspiration you can check this : http://2.bp.blogspot.com/-QHea4ARa6qQ/UEN74jG2l1I/AAAAAAAAg1o/U-oubAnLf_0/s1600/collage+quotes+(1).jpg

**Comment by tijlleenders** [comment]
Not a prio - cleaning up the backlog.
