### ISSUE TITLE
Make the explore page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#288]
Make the page as designed in #241

Per category think of a few titles of plans that will be liated when you click on a category. They don't have to be clickable yet. It is to demo the idea to people and get feedback.

**Comment by Tushar-4781** [comment]
@mallikarai05 can you share the dark theme design of the explore page?

**Comment by tijlleenders** [comment]
Aïe... I think we missed that one. @mallikarai05 #313 has priority. The explore page can wait...

@Tushar-4781 just merge with a placeholder theme for now and make an extra issue to correct it.
