### ISSUE TITLE
Add a new language

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#299]
If you speak a language that isn't represented yet this might be something for you...

This issue is reserved for newcomers to the project - not for current contributors.

**Comment by tijlleenders** [comment]
Arabic would be nice.

**Comment by tijlleenders** [comment]
Super nice @Sanket-Arekar ! 

What language will you be adding?

You've already got two issues on your name so let's keep this one one the backlog till you're finished with those ok?

**Comment by Sanket-Arekar** [comment]
I would add Marathi Language

**Comment by tijlleenders** [comment]
Wow, I learned something today. Marathi ranks 13th in the [list of languages with most native speakers in the world](https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers).  

Cool!

**Comment by lchauha** [comment]
Hello @tijlleenders I would like to work on this issue, Please assign this to me.

**Comment by tijlleenders** [comment]
Cool @lchauha !

Which language are you adding?

You can take previous PRs as reference of what you need to change ;).

**Comment by lchauha** [comment]
I would like to add Gujarati as a language.
