### ISSUE TITLE
Make the design for navigating hierarchy of goals

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#300]
We'll soon have a list of goals in the 'My goals' page.
We can add, delete, modify - but it'll still be a single list.
What is needed is a way to 'go into' a list and make sublists. Each item in a sublist can also be the start of a new sublist, etc.

So goals will be a ragged hierarchy:
![image](https://user-images.githubusercontent.com/44887755/167538642-5c44d332-b580-494e-8df9-de6a4d637230.png)

Some questions that need to be solved (provide details steps with UI interactions and designs) in the UI (mobile only):  
- #301 
- #302
- #303
- #304
- #305
- #306

This is a big issue and only meant to regroup the work in the (sub-issues).

**Comment by mallikarai05** [comment]
@tijlleenders 
I have an idea, can I hand draw the whole thing first and if that works I can start with the design?

**Comment by tijlleenders** [comment]
That is a great idea!
Handsketching saves a lot of time - and why not?

**Comment by tijlleenders** [comment]
Looks real good!

It's hard to find a perfect system. Double taps are impossible to do for some (older) people so I would suggest an icon that replaces the + when there is already a sublist. That way if you want to go into the sublist you can double tap - or tap once (expand menu below task) and then click the go into icon.

Also, when there are sublists, maybe we can show the goals as a stack of cards with only the top one visible? Then you have a visual clue on which ones are navigable and which ones don't have sublists.

**Comment by tijlleenders** [comment]
A back arrow top left, like on iPhones to navigate "up the breadcrumb"?
