### ISSUE TITLE
How do we edit an existing goal?

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#302]

**Comment by mallikarai05** [comment]
When you single tap on a particular goal it expands to give options (We can add more options if required)
![image](https://user-images.githubusercontent.com/73054648/167777552-2e50a84d-7161-40a3-b51e-128021f08da9.png)

**Comment by mallikarai05** [comment]
We can add an option to mark the goal as done too if required.

**Comment by tijlleenders** [comment]
I like it!
Adding a 'complete/achieved' option sound good.

**Comment by tijlleenders** [comment]
Maybe space out the three options so you don't accidentally hit the wrong one?  
That also allows to increase the reactive area of the button.  
A lot of older people have issues aiming / tapping with 'fat fingers'.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/168131637-4bde1cfd-48c0-4269-8eb0-d90643927397.png)

**Comment by tijlleenders** [comment]
Looks good.
Which one do you prefer? Spread out or grouped to one side?

**Comment by mallikarai05** [comment]
I think having them spread out will be easier for the users.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/170742471-b99c6922-316a-41cf-9e94-2f95590b59da.png)
@Tushar-4781 this is for your reference.

**Comment by tijlleenders** [comment]
@mallikarai05 We should name them Goals - not Tasks.
Goals get transformed into Tasks on a calendar.
