### ISSUE TITLE
How do we remove an existing goal?

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#303]

**Comment by mallikarai05** [comment]
When you single tap on a particular goal it expands to give options (We can add more options if required)
![image](https://user-images.githubusercontent.com/73054648/167777585-0fc15048-e0ca-4ff0-9cfd-f9a7b3d7fe4d.png)

**Comment by mallikarai05** [comment]
This is the design for now- also in this case deleting a goal will delete all the sublists it has if there are any.
Should there be a confirmation option before you delete a task? I'm not very sure. In some cases, I find it useful (if I am deleting the wrong goal by mistake but sometimes it can be bothering)
![image](https://user-images.githubusercontent.com/73054648/168122768-bd824b79-3401-4516-b6e9-020ac0c3a22d.png)

**Comment by tijlleenders** [comment]
Let's start with a delete that deletes everything including sublists without a confirmation. We can always add it later.
