### ISSUE TITLE
How do we navigate through the hierarchy?

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#305]

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/168463347-43864445-60a1-42a5-bd31-befb2edbd29c.png)

**Comment by tijlleenders** [comment]
All my testers say the right side is better.

**Comment by mallikarai05** [comment]
@tijlleenders I asked a few people too, and most of them said the same.
