### ISSUE TITLE
How do we search through the hierarchy?

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#306]

**Comment by tijlleenders** [comment]
How would search results be shown?

**Comment by mallikarai05** [comment]
If there is one search result- display the name of the search list
![image](https://user-images.githubusercontent.com/73054648/169651245-e48bb3d1-fb52-474c-a76a-58ff5aa184eb.png)

If there are multiple search results - display the main list i.e. My Goals only
![image](https://user-images.githubusercontent.com/73054648/169651460-88dcb447-3e4c-46a7-bbd6-4fe0ce021e92.png)

**Comment by tijlleenders** [comment]
Nice idea.

How would it work if there are multiple results and you click on the first when the search results is three levels down?

And what if there are multiple results multiple levels down? Do you go to the next "fork in the road" until you reach the actual result?

This could be pretty cool :)

**Comment by mallikarai05** [comment]
The idea was to display the results level-wise so 1st will be 'My Goals, and then the sublists. 
if the search is multiple levels down for example if you search milk you'll be directed to this page.
![image](https://user-images.githubusercontent.com/73054648/169661186-58bc3406-420d-4dbc-8d4d-35ca0829daba.png)
I think for multi-levels we can have a small line below the result, with the exact path of the sub-list. like this-
![image](https://user-images.githubusercontent.com/73054648/169661358-74a8b46d-d1db-451c-9ee1-bf5073cb0eb8.png)

**Comment by tijlleenders** [comment]
Yeah, let's try it this way!
