### ISSUE TITLE
UI Design landing page web and mobile (1st visit)

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#31]
Landing page, user authentication, dashboard, application components, etc. Finalizing color, themes, and patterns

**Comment by LebianWill** [comment]
Hi!!
When you will be done with the UI, let me know!

**Comment by mallikarai05** [comment]
Hi! I've started working on the color and theme, I will try and complete it by this Wednesday.

**Comment by mallikarai05** [comment]
This issue can be closed now.
