### ISSUE TITLE
Show saved feelings on My feelings page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#312]
Blocked by #313 

- Make a My feelings page as designed in #313
- The feelings get saved when you click on them on the Add feelings page.
- After the Feeling is saved, the user needs to be taken to the 'My feelings' page (where the Feeling is shown) so that it is clear that the Feeling has been added.

**Comment by pulkitvyas08** [comment]
> * After the Feeling is saved, the user needs to be taken to the 'My feelings' page (where the Feeling is shown) so that it is clear that the Feeling has been added.

I think a better way to achieve this would be by showing a toast message to the user that the feeling has been added or that the feeling already exists in today's logs. Attaching a sample image to show what I mean by this.

![image](https://user-images.githubusercontent.com/54947769/168674229-8238c183-fadb-4dfe-a1a0-00c218867abf.png)

**Comment by tijlleenders** [comment]
Blocked by #313 that still needs to be developed.

**Comment by tijlleenders** [comment]
Good suggestion.

Let's keep the current flow so we can ship a first "working" version. 
If we confirm that people find it confusing that they are taken to the My feelings page as confirmation after adding a feeling we can explore this further.

**Comment by tijlleenders** [comment]
Design in #313 is finalized.
