### ISSUE TITLE
Discuss formatting issues

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#315]
There are several recurring formatting requests that eat up valuable time and focus - when they could be automated.

These should be handled in the pre-commit hook - and the same config can be given to the Integrated Development Editor (IDE) like VSCode Prettier extension config.

Examples:
"And please add some space between the colon and the text" 
"Please add an empty line at the end of the file"
... ?

This issue is done when:
- it will be impossible to commit code with the above formatting mistakes (auto-format in pre-commit or in pipeline)
- There is a config explanation for the common IDEs (for now just VSCode) in the CONTRIBUTING.md

**Comment by pulkitvyas08** [comment]
> There are several recurring formatting requests that eat up valuable time and focus - when they could be automated.
> 
> These should be handled in the pre-commit hook - and the same config can be given to the Integrated Development Editor (IDE) like VSCode Prettier extension config.
> 
> Examples: "And please add some space between the colon and the text" "Please add an empty line at the end of the file" ... ?
> 
> This issue is done when:
> 
>     * it will be impossible to commit code with the above formatting mistakes (auto-format in pre-commit or in pipeline)
> 
>     * There is a config explanation for the common IDEs (for now just VSCode) in the CONTRIBUTING.md

I think this just got fixed in #419
