### ISSUE TITLE
Redesign theme choice

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#319]
Right now the theme choice has English text. This makes it confusing for users that choose a different language. They would expect to choose between two theme images in the language they just chose.

Even if the text is translated - some users think it is actually a menu with buttons they need to click on - and they then zoom in, click on something, and then get the the dashboard page - but all zoomed in...

A solution would be two buttons, just like the normal buttons:
- one in light theme with word "Light theme"
- one in dark theme with word "Dark theme"
(or the correct translations).

**Comment by tijlleenders** [comment]
This looks like it's nearly done:
![Screenshot_20220724-084836_DuckDuckGo.jpg](https://user-images.githubusercontent.com/44887755/180635934-eb148f52-1a18-4a4d-a089-7e196fd8add2.jpg)

@mallikarai05 Only questikn remaining is if we should have the same colors in the background or different ones. Right now there is no clear difference in the vertical color bars. They look quite similar.

**Comment by mallikarai05** [comment]
![Uploading image.png…]()

@tijlleenders if we are going forward with the new theme colors can we use this design?

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/194468615-37d14cd6-e330-4541-94c3-60214c3f6d12.png)

**Comment by tijlleenders** [comment]
I like the simplicity of this choice!
... and since the colors are the same in light and dark mode it woukd be confusing to add them now.

Would remove the text-background-block though...

**Comment by tijlleenders** [comment]
Is "What do you like?" a friendlier way of presenting the choice vs the more 'commanding' "Choose your preference." ?

**Comment by mallikarai05** [comment]
@tijlleenders I added the text-background box for adding the colors of the gradient so you get an idea when color the light theme has for the background but an illustration is a good idea
I'll change the text!

**Comment by mallikarai05** [comment]
Updated the text and added the new design to the roadmap

**Comment by tijlleenders** [comment]
I still don't see a clear design.
We should go for the white and dark in my opinion, but make the text background the same as the card background or it will look clumsy.

![Screenshot_20221009-145259_DuckDuckGo.jpg](https://user-images.githubusercontent.com/44887755/194757978-76b9d931-5083-4347-b811-e9bac2f0ea0a.jpg)

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/194764704-86a14145-97a2-42b8-bba6-697bb4208e55.png)
![image](https://user-images.githubusercontent.com/73054648/194764821-0e87ee86-d9c2-4c8e-a849-62ad2a90d387.png)
@tijlleenders what do you think?

**Comment by mallikarai05** [comment]
![Uploading image.png…]()
The three bars were part of the introduction pages only as a logo, we can remove it now

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/194764934-10daced4-da2a-48fd-92ca-6f78770645bf.png)


The three bars were part of the introduction pages only as a logo, we can remove it now

**Comment by tijlleenders** [comment]
Yeah this is good.

Center the text too?

Let's get it in the roadmap and finally close this issue!

**Comment by tijlleenders** [comment]
Correction on above design: 
- Text should be "Light colors" and "Dark colors"

**Comment by tijlleenders** [comment]
@mallikarai05 Can you update previous comment in the roadmap?

**Comment by mallikarai05** [comment]
@tijlleenders done!

**Comment by tijlleenders** [comment]
![image](https://user-images.githubusercontent.com/44887755/204487459-56d7fe03-4be9-495e-9617-d6895b481a57.png)

**Comment by tijlleenders** [comment]
![image](https://user-images.githubusercontent.com/44887755/204491286-c0e7dd5c-6ae2-44b0-80f9-9f19796cb430.png)
