### ISSUE TITLE
Make a proposal for CI/CD solution

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#32]

**Comment by tijlleenders** [comment]
I propose to configure TravisCI (commercial, but free for open source) + GitHub pages.
An alternative would be to use Jenkins, which is open source, but that requires more effort + money to setup and run.

**Comment by mallikarai05** [comment]
I think it would be better to use GitHub Actions since it's completely free
and better for open source.

**Comment by tijlleenders** [comment]
Sure, that looks good!
I was not aware of that option.
