### ISSUE TITLE
Make a 'Download my data' button/option

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#321]
No UI necessary.
For now just a function that can be called from the javascript web developer console to backup the whole repo to a file on the user's device.

The file is not encrypted at the moment - there will be a separate issue for that.

**Comment by GithinjiHans** [comment]
We can do this using a ShellScript

**Comment by tijlleenders** [comment]
What is wrong with this?
![image](https://user-images.githubusercontent.com/44887755/171099893-14a43929-a6f1-4617-86f8-ee311dea1503.png)

I don't see the added value of a shell script.


What happened here is that you misinterpreted the issue.
It is about making a file download of all registered feelings and goals.

**Comment by tijlleenders** [comment]
This issue is not a priority for now.

**Comment by tijlleenders** [comment]
It also needs a design (download button in settings menu) and a file format spec.
