### ISSUE TITLE
Redesign feeling sub choice

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#332]
Right now when clicking on a feeling a set of new buttons appears.

This is OK for certain users but others struggle with the fact that they expected something to happen and don't notice the change on screen.

Proposal:
When a feeling main category is tapped, a popup asks "You feel [feeling main category]. 
Can you be more specific?"

You can then select multiple, more specific feelings and tap 'Done'. If nothing more specific is chosen, you can tap 'Done' or click outside the popup, and the feeling will get saved as '[feeling main category]-unspecified'. Else it will get logged as several separate feelings - all with their own (and same) main category (ie happy-loved + happy-peaceful).

Since a popup is already used to confirm the choice (and ask if you want to add a note) maybe this should just be a new page with regular buttons?

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/170823131-14f2de6f-79d9-4564-a441-c7eccfb42a2d.png)
When you click on the expand arrow next to a feeling-Example: Happy 
![image](https://user-images.githubusercontent.com/73054648/170823161-3e8d9257-4b0d-4e55-8544-3baef2d25d54.png)

**Comment by tijlleenders** [comment]
Looking good!
