### ISSUE TITLE
Make a proposal for internationalization i18n

### ISSUE THREAD

**Issue by LebianWill** [tijlleenders/ZinZen#34]
Translate based on the location. For those who is usign the app for their first time, we need to ask the display language to be sure.

**Comment by tijlleenders** [comment]
@LebianWill Can you add your proposal so @mallikarai05 is updated - and close the issue?

**Comment by LebianWill** [comment]
@mallikarai05 Hi, for the internationalisation, i propose to use i18next.
Link for the docs: https://www.i18next.com/overview/getting-started
