### ISSUE TITLE
Investigate addition of a component library 

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#340]
As the number of components will increase in the coming weeks and months we might need a library for them that can:
- Make the process of finding and exploring components easier
- Document the component
- Let the developers experiment with them in isolation
- Test the components with automated cases

[StorybookJS](https://storybook.js.org/) and [Bit Dev](https://bit.dev/) are great examples of these that are free and open source too.

Here we first need to understand if we are at a stage and scale to integrate these or not and then choose the best among the options.

**Comment by tijlleenders** [comment]
I don't think the UI is so complex it requires a framework.
We basically have pages with lists - and we only do mobile.

The component frameworks are more for apps that require flexibility in complex pages, mostly for larger screen sizes.

**Comment by pulkitvyas08** [comment]
Even though I do see the project going into that direction it is fair to say that we are not at that stage right now, no issues.
