### ISSUE TITLE
Create unit test approach

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#342]
Do we need a framework to do unit tests?
Are unit tests run on commit, on push, on pull request?

**Comment by pulkitvyas08** [comment]
> Do we need a framework to do unit tests? 

Yes, we do. And urgently so as tests are now being written for multiple features.

>Are unit tests run on commit, on push, on pull request?

Not at the moment, neither the commit nor the build or run scripts have an `npm test` added as of now

**Comment by Tushar-4781** [comment]
Uh is #386 solving this issue ?

**Comment by pulkitvyas08** [comment]
> Uh is #386 solving this issue ?

Yes

**Comment by Tushar-4781** [comment]
Resolved in #386
