### ISSUE TITLE
Make TS checking stricter and fix errors / fulfil type requirements

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#347]
The whole purpose of integrating TS into the project was to block the commits/pushes of the app when the changes are not strongly typed. The current state of `tsconfig.json` doesn't show errors on the app but only displays the problems as `eslint` / `ts` warnings (an example is attached below).
There are two ways of doing this - 
1. Add TS compilation to the `npm run dev` script that starts the Vite server (This is the most used way)
2. Add a pre-commit hook that runs TS compilation (This is IMO better as it makes development smoother when commits have a small amount of code, but if the commits are big then you will have a ton of errors at the time of a commit and this might result in missed deadlines)

Please discuss below the preference for this and implement it ASAP. This was supposed to be done in #237.

Also attached below are the screencaps of various parts of the codebase showing that a lot of TS errors have been straight-up ignored. This is not good for the long run and we need to follow the convention and coding standards to make it easier for others to code and write efficient tests.

![Screenshot (10)](https://user-images.githubusercontent.com/54947769/169286083-f3e434e2-19fc-47ee-aa83-b9ec2b7d46c1.png)

![Screenshot (11)](https://user-images.githubusercontent.com/54947769/169287303-068ec083-55b8-4a9c-be10-cc1251cf0b30.png)

![Screenshot (12)](https://user-images.githubusercontent.com/54947769/169287442-166c1fde-6665-4c73-8e96-de8b42c92e50.png)

![Screenshot (13)](https://user-images.githubusercontent.com/54947769/169287613-0041285b-9d38-4cd4-a701-f2af881a0455.png)

![Screenshot (14)](https://user-images.githubusercontent.com/54947769/169288178-22ccd7bc-fe44-4dfe-9627-5ed7fdd25b25.png)

![Screenshot (15)](https://user-images.githubusercontent.com/54947769/169288236-663dd7a1-fa44-4eff-a841-e7d203cc346a.png)

**Comment by tijlleenders** [comment]
By large I prefer option 2 since option 1 does not prevent bad commits.
Also, option 2 encourages smaller atomic commits - which is good.

**Comment by Tushar-4781** [comment]
> The whole purpose of integrating TS into the project was to block the commits/pushes of the app when the changes are not strongly typed. The current state of `tsconfig.json` doesn't show errors on the app but only displays the problems as `eslint` / `ts` warnings (an example is attached below). There are two ways of doing this -
> 
> 1. Add TS compilation to the `npm run dev` script that starts the Vite server (This is the most used way)
> 2. Add a pre-commit hook that runs TS compilation (This is IMO better as it makes development smoother when commits have a small amount of code, but if the commits are big then you will have a ton of errors at the time of a commit and this might result in missed deadlines)
> 
> Please discuss below the preference for this and implement it ASAP. This was supposed to be done in #237.
> 
> Also attached below are the screencaps of various parts of the codebase showing that a lot of TS errors have been straight-up ignored. This is not good for the long run and we need to follow the convention and coding standards to make it easier for others to code and write efficient tests.
> 
> ![Screenshot (10)](https://user-images.githubusercontent.com/54947769/169286083-f3e434e2-19fc-47ee-aa83-b9ec2b7d46c1.png)
> 
> ![Screenshot (11)](https://user-images.githubusercontent.com/54947769/169287303-068ec083-55b8-4a9c-be10-cc1251cf0b30.png)
> 
> ![Screenshot (12)](https://user-images.githubusercontent.com/54947769/169287442-166c1fde-6665-4c73-8e96-de8b42c92e50.png)
> 
> ![Screenshot (13)](https://user-images.githubusercontent.com/54947769/169287613-0041285b-9d38-4cd4-a701-f2af881a0455.png)
> 
> ![Screenshot (14)](https://user-images.githubusercontent.com/54947769/169288178-22ccd7bc-fe44-4dfe-9627-5ed7fdd25b25.png)
> 
> ![Screenshot (15)](https://user-images.githubusercontent.com/54947769/169288236-663dd7a1-fa44-4eff-a841-e7d203cc346a.png)

You mentioned in #237 that you will be coding the myFeelings page and dexi setup in TS ( #117 ).

**Comment by pulkitvyas08** [comment]
> You mentioned in #237 that you will be coding the myFeelings page and dexi setup in TS ( #117 ).

Yes, what I'm referring to here is everything else besides the myFeelings stuff

**Comment by Tushar-4781** [comment]
> > You mentioned in #237 that you will be coding the myFeelings page and dexi setup in TS ( #117 ).
> 
> Yes, what I'm referring to here is everything else besides the myFeelings stuff

Oh ok. Actually, the above screenshots contain myFeelings as well. It created confusion. Anyways I have solved other TS warnings. Have a look at #381 and review it as per your convenience
