### ISSUE TITLE
Errors in UserChoice.test.ts

### ISSUE THREAD

**Issue by pulkitvyas08** [tijlleenders/ZinZen#349]
1. There are eslint errors

![Screenshot (16)](https://user-images.githubusercontent.com/54947769/169290281-576a1298-5fa3-4cc8-99bc-10661cbed4fb.png)

&nbsp;

2. There are TS errors (#347)

![Screenshot (16)](https://user-images.githubusercontent.com/54947769/169290350-dcd57c61-23a6-4506-bfae-6e997089517a.png)

&nbsp;

3. Running the test doesn't even do anything

&nbsp;

![Screenshot (18)](https://user-images.githubusercontent.com/54947769/169290489-f1385a8f-d777-4b2f-9dc1-4c62db9a608d.png)

&nbsp;

4. Not sure about what the test is about. Please give a description.

Assigning the people who worked on this.

**Comment by Tushar-4781** [comment]
@pulkitvyas08 i left db and test files because they weren't made by me. It would have consumed extra time by me so I left these 2. 
I might have misunderstood the discussion i guess because I thought you are taking the dexie setup and tests into the account.

**Comment by pulkitvyas08** [comment]
> @pulkitvyas08 i left db and test files because they weren't made by me. It would have consumed extra time by me so I left these 2. I might have misunderstood the discussion i guess because I thought you are taking the dexie setup and tests into the account.

This is not a discussion about DexieJS or DB or tests related to them (there are none at the moment)

**Comment by pulkitvyas08** [comment]
I tagged you because you were the last one to modify `UserChoice.test.ts`. Check the git blame below

```
(base) PS D:\Workspace\Git-Repos\ZinZen> git blame .\UserChoice.test.ts
c57b7ddd UserChoice.test.ts (Tushar-4781 2022-05-07 12:12:25 +0530  1) const lang = localStorage.getItem('language');
c57b7ddd UserChoice.test.ts (Tushar-4781 2022-05-07 12:12:25 +0530  2) const theme = localStorage.getItem('theme');
157d1498 UserChoice.test.js (Mallika Rai 2022-03-03 23:47:38 +0530  3)
157d1498 UserChoice.test.js (Mallika Rai 2022-03-03 23:47:38 +0530  4) test('No language or theme chosen', () => {
c57b7ddd UserChoice.test.ts (Tushar-4781 2022-05-07 12:12:25 +0530  5)   expect(lang).toBe('No language chosen.') && expect(theme).toBe('No theme chosen.');   
c57b7ddd UserChoice.test.ts (Tushar-4781 2022-05-07 12:12:25 +0530  6) });
157d1498 UserChoice.test.js (Mallika Rai 2022-03-03 23:47:38 +0530  7)
157d1498 UserChoice.test.js (Mallika Rai 2022-03-03 23:47:38 +0530  8) test('Language is saved, theme choice page', () => {
c57b7ddd UserChoice.test.ts (Tushar-4781 2022-05-07 12:12:25 +0530  9)   expect(lang).not.toBe('No language chosen.') && expect(theme).toBe('No theme chosen.');
c57b7ddd UserChoice.test.ts (Tushar-4781 2022-05-07 12:12:25 +0530 10) });
157d1498 UserChoice.test.js (Mallika Rai 2022-03-03 23:47:38 +0530 11)
c57b7ddd UserChoice.test.ts (Tushar-4781 2022-05-07 12:12:25 +0530 12) test('Language and Theme saved', () => {
c57b7ddd UserChoice.test.ts (Tushar-4781 2022-05-07 12:12:25 +0530 13)   expect(theme).not.toBe('No theme chosen.');
c57b7ddd UserChoice.test.ts (Tushar-4781 2022-05-07 12:12:25 +0530 14) });
```
