### ISSUE TITLE
Resize images for 'Explore'

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#354]
Every image is now a few MB.
This causes the page to take forever on slow connections - and even on fast connections there is a noticeable lag.

The images need to be resized to a smaller format - without losing sharpness on mobile.

**Comment by Tushar-4781** [comment]
Or maybe we can look for some other images which are taken in portrait.

**Comment by tijlleenders** [comment]
Portrait or landscape does not really make a difference for the size. Landscape should be possible (also later when people add their own photos to items) - it'll just look smaller compared to the portrait ones when viewing on mobile non-sideways.

Size is more about the resolution.
