### ISSUE TITLE
Make design for 'Anonymous' setting

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#355]
On first use of ZinZen, after language and dark/light mode setting, you see the following text, possibly with a peaceful/safe illustration: 
"ZinZen respects your privacy.

ZinZen does not know you name, email, address or phone number. All your data will be kept on this device only, so ZinZen can't see it.

You can help other people anonymously.  
Would you like to?"

The answers are:
"Yes - but ask me to confirm each time before sharing anonymously."

"No - and never ask me again."

Your choice can always be changed later in 'My settings'.

**Comment by mallikarai05** [comment]
@tijlleenders will this be a different page entirely or can we include it with the FAQ page #239

**Comment by tijlleenders** [comment]
#239 has nothing to do with this page.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/174048028-a269738e-3ab2-448b-8144-2e9c89339b89.png)

**Comment by tijlleenders** [comment]
Maybe we can take the top text + picture and include it as an intro page on first startup.
Would require a dark version too though.

**Comment by mallikarai05** [comment]
@tijlleenders I tried making the dark version for it
![image](https://user-images.githubusercontent.com/73054648/174486431-36dd506c-d5a6-477a-b263-49ff7b0beb9c.png)

**Comment by tijlleenders** [comment]
Love it!
