### ISSUE TITLE
Avoid empty 'My goals' page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#356]
If someone opens the My goals page without any registered goala it should open the Add goals page instead.

**Comment by Tushar-4781** [comment]
> If someone opens the My goals page without any registered goals it should open the Add goals page instead.

Suggestion:

Or we can show an SVG in the center containing a text like "Hurray, It looks like you don't have any goals for today" or something like that and there we can add a button that redirects to add goals page.

**Comment by tijlleenders** [comment]
Yeah the hooray thing is what a lot of apps do when you clear your inbox or todos for the day - but I'm not sure if we should celebrate someone having no goals..
 :)

Definitely something to think about. Positive feedback for the calendar/task view when you complete x tasks or the morning or the whole day.

I do like the idea of taking the opportunity to communicate something on the empty My Goals page. Maybe it a good place to give some suggestions?... 

Picture of a winding road + "Always enjoy the ride - but does your road also have a destination?"

"Add a goal now" or "Explore some options"

**Comment by pulkitvyas08** [comment]
> Yeah the hooray thing is what a lot of apps do when you clear your inbox or todos for the day - but I'm not sure if we should celebrate someone having no goals.. :)
> 
> Definitely something to think about. Positive feedback for the calendar/task view when you complete x tasks or the morning or the whole day.
> 
> I do like the idea of taking the opportunity to communicate something on the empty My Goals page. Maybe it a good place to give some suggestions?...
> 
> Picture of a winding road + "Always enjoy the ride - but does your road also have a destination?"
> 
> "Add a goal now" or "Explore some options"

How about we treat this like the empty 'My Feelings' page? Redirect the user to 'Add Goals' if the list of goals is empty

**Comment by tijlleenders** [comment]
Sounds logical - no goals in life is a little sad... :)

**Comment by tijlleenders** [comment]
@mallikarai05 Please decide from UX perspective so we can start making this.
