### ISSUE TITLE
How to integrate the wasm in the app CI?

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#361]
This issue is foe the diacussion on how to integrate the wasm module to the frontend.

The wasm is being built in a different repo.
We need a place where the app CI can pull the latest version of the WASM module.

@sokorototo For now we can copy manually when a new version is available.

See comment https://github.com/tijlleenders/ZinZen/issues/361#issuecomment-1193251470

**Comment by sokorototo** [comment]
We probably need to get git submodules working

**Comment by tijlleenders** [comment]
Submodules doesn't look like a good fit.
Reasons on [this GitHub blogpost](https://github.blog/2016-02-01-working-with-submodules/)

What about semantic versioning on crates.io and then pulling it from there?

**Comment by sokorototo** [comment]
You can't pull binaries from crates.io and publishing a module to npm is overkill. Instead one can just use Github's CDN based on repos. Eg the link to the raw wasm file would be: <https://github.com/tijlleenders/ZinZen-scheduler/blob/main/ts/scheduler.wasm?raw=true>

**Comment by tijlleenders** [comment]
Yeah, if that works it is a lot simpler!

**Comment by sokorototo** [comment]
A problem is that always links to the latest development version, we can't just ship code in testing to users. We have to make a release branch then link the wasm from there

**Comment by tijlleenders** [comment]
For now it's important to get a workinf integration. So copy the files manually for each new wasm release. 

Then we can think about automating the integration.

The files can be generated/integrated in several ways. @xy2iii gave us a nice explanation in https://github.com/tijlleenders/ZinZen-scheduler/issues/24

There are a few experimental Vite plugins for output 'bundler'. If that doesn't work we can switch to web, nodejs or no-bundler if that does work (https://rustwasm.github.io/wasm-bindgen/reference/deployment.html).

**Comment by sokorototo** [comment]
Do git submodules work with CI? Because we can just link the js-api folder during building, and webpack takes it from there

**Comment by tijlleenders** [comment]
GitHub is [quite negative](https://github.blog/2016-02-01-working-with-submodules/)on using Git submodules - it's a "last resort". This was in 2016 so might have improved since.

My first impression is that a git submodule would not be a good choice because:
- incorporate the whole ZZ-scheduler repo as a subdirectory - not just the js-api dir
- you have to issue a command to update it - so then we might as well have a script that doeals a raw download of the required files from zz-scheduker into the ZZ repo and adds a commit

PS: we're not using webpack as a bundler but Vite (which uses esbuild under the hood) because it's a lot faster.

**Comment by sokorototo** [comment]
I think just copying and pasting the `js-api` folder into the main repo as `scheduler`, whenever there is a new release, is the best solution as of now

**Comment by tijlleenders** [comment]
In the ZinZen-scheduler repo:
```
cargo build --target wasm32-unknown-unknown
wasm-bindgen ./target/wasm32-unknown-unknown/debug/scheduler.wasm --reference-types --typescript --debug --keep-debug --out-dir pkg --target web
```
Then copy the /pkg to /pkg in the ZinZen repo and build the React app.

PS: cargo build can be optimized by using --release - but for now we like the debugging.

We can make a commit with new files to /pkg every time there is a new scheduler release.
