### ISSUE TITLE
Make default list of suggested habits

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#365]
For each main category in the Explore page make a list of 10-15 habits that most people can start doing... with a few challenging ones.

Examples

Health and fitness:
Walk 1h daily
Drink water 5 times a day
Go to bed at 22h
Run 5km twice a week
...

**Comment by mallikarai05** [comment]
@tijlleenders do we only need to make the list here right now?

**Comment by tijlleenders** [comment]
Yeah, everyone that wants can contribute to the list in this issue. It's a dry run. An experiment to see where it goes before we make it for real.

**Comment by tijlleenders** [comment]
Superceded by #635
