### ISSUE TITLE
Design a roadmap for the app and navigation between different pages

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#371]
Right now there is a lot of confusion regarding the navigation and how different pages and features function. As suggested by @Tushar-4781 it will be easier if there was some sort of map to explain what each button or option does.

**Comment by tijlleenders** [comment]
@mallikarai05 Should there be an > when there are no sublists?

**Comment by mallikarai05** [comment]
I think so, in case there is no sublist a blank page will show up?

**Comment by tijlleenders** [comment]
My issue with that is that while navigating - it will give the impression there are sublists - when there are not.
A different approach could be to visually change the button when there are multiple sublists, ie by showing the button as stacked ( as mentionend in https://github.com/tijlleenders/ZinZen/issues/331#issuecomment-1139345968 )
