### ISSUE TITLE
Make design for a 'completed' goal

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#376]
There is a checkmark button now in the buttons that appear below a goal when it is clicked.

This checkmark is not to save edits to the title - but to complete and archive the goal. Maybe we should rethink the icon as it is confusing with the complete task button. It does not really make sense for repeating goals. Maybe we should only show it for non-repeating goals?

Goal "Walk 1h daily" => check => the goal will not schedule any tasks on your calendar again.

Calendar Task "Walk 1h" => check => I've completed the walk for today only. Tomorrow and following days will still have a Task "Walk 1h".

For a Goal like "Get my driver's license" - it does make sense to have a complete button - which will automatically remove any underlying Tasks from the calendar.

**Comment by mallikarai05** [comment]
I was thinking of having the check button to mark the things done.
For repeating goals-
"Walk 1h daily" => check => I've completed the walk for today only.
(So the calendar knows it's only done for the day and will be scheduled for the next day as well)
For others-
"Pay electricity bill" => check => the goal will be marked as done with no changes in the calendar.
(As while adding the goal there will be no frequency set as it is a one-time goal so the check will only mark it as complete)

I am unsure if there should be a way to see archived/completed goals?
I would want to see the things I've done/accomplished past weeks or months. So once the check button is clicked the particular goal should be saved somewhere along with the date maybe?

**Comment by tijlleenders** [comment]
Don't worry about how/where it's saved.
Focus on what the design / interactions should / feel like.

I do think it is nice to see the completed goals somewhere - but you also don't want to clutter op the 'open goals' with that...

**Comment by tijlleenders** [comment]
How about showing all goals completed today by defaukt - and showing all completed before today with a search for "done" or "done this week"?

Or showing completed goal events in the timeline? ...but then how to get to the timeline of stuff i  the past (default is from today onwards)?

**Comment by tijlleenders** [comment]
... or another high level section "My accomplishments" - it can also feature events like "streaks" on repeating tasks.

Maybe mix it with the My feelings timeline - which is always today + past?

**Comment by tijlleenders** [comment]
Group decision :  
- Delete => gone forever
- Check (always shown whether repeating or not) => marked done including all subGoals + not shown anymore since moved to archive page (to be designed)
