### ISSUE TITLE
Make new design for header

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#385]
On all pages the ZinZen icon (three bars) should be in the top right.

The light/dark theme changer should only appear on the main page.

The ZinZen text should be present in the middle on all pages. On the main page it will share the middle position with the light/dark theme switcher to its right.

On the main page there is nothing in the top left. On allnother pages there is a back arrow to return to previous page in the top left.

**Comment by mallikarai05** [comment]
The header for the home page/main page-
![image](https://user-images.githubusercontent.com/73054648/171464308-d5be45a1-99df-45da-8120-17ed83c1bfd7.png)
The header for all the other pages-
![image](https://user-images.githubusercontent.com/73054648/171464412-ae1586b7-8255-4cb8-bf4a-9e7d7f715edc.png)

**Comment by tijlleenders** [comment]
@mallikarai05 Can you attach the asset (svg?) for the arrow?
