### ISSUE TITLE
Adjust AddFeelings page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#393]
There were some changes in the design so the AddFeelings page needs to be modified.
NB: This is not the MyFeelings page, but the page you get after clicking + Feeling.

No longer blocked by #384

Old:
![image](https://user-images.githubusercontent.com/44887755/172058895-9fc955d9-4f96-4d78-8cd1-2a96379dd15f.png)

New:
![image](https://user-images.githubusercontent.com/44887755/172058909-e9d9ad59-ea2c-423d-bb00-40c04f716f14.png)

\+ at bottom of page:
![image](https://user-images.githubusercontent.com/44887755/172059014-1bd4beec-9aa6-4c20-8fbc-611f108c91bb.png)
@mallikarai05 Personally I don't think this is necessary. If we change our mind (don't want to enter any feeling there is always the back arrow top-left). Do you agree?

Clicking on the left side of a feeling option logs the main feeling (ie Happy, Sad, etc).
Clicking on the arrow gives a popup where you can select 0, 1 or multiple sub-feelings:
![image](https://user-images.githubusercontent.com/44887755/172059085-11a2808b-df56-4e90-b882-1a0770cb1e14.png)

The custom feeling "I feel ..." does not have to be implemented for this issue to be closed.

**Comment by mallikarai05** [comment]
@tijlleenders yes but if we have logged something and we want to view it from the 'Add Feelings' page we have to go back first to the dashboard. Can we take everyone's opinion on this?

**Comment by tijlleenders** [comment]
Maybe you can show it on the "overview" and we can discuss it Friday?

**Comment by mallikarai05** [comment]
Good idea, yes!

**Comment by tijlleenders** [comment]
Group decision: Keep the 'Show my feelings' button since it is handy when coming directly from the + in the dashboard in which case the return button would take you back to the dashboard, not My Feelings.
