### ISSUE TITLE
Remove the scrolling from FAQ page

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#399]
FAQPageUserPanel component should not be scrollable. Refer to the Snapshots attached.
![image](https://user-images.githubusercontent.com/39093015/172172278-05545b62-f0de-43fa-8987-de2b256a2656.png)
![image](https://user-images.githubusercontent.com/39093015/172172550-eac91a4b-fe2d-48d5-a3ed-5069766429a2.png)

**Comment by tijlleenders** [comment]
@Tushar-4781 does this happennon mobile too? If not this issue is low priority.

To save time we design and build for mobile only - for now.

**Comment by Tushar-4781** [comment]
> @Tushar-4781 does this happennon mobile too? If not this issue is low priority.
> 
> To save time we design and build for mobile only - for now.

@tijlleenders its not scrolling but half of the space is empty

![image](https://user-images.githubusercontent.com/39093015/172290766-fe582f5c-a4a6-4117-9b97-0130c2342c8b.png)
