### ISSUE TITLE
Fetch explore page images from URL

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#427]
Right now the explore page images are included in the bundle. This increases the bundle size unnecessarily.
The images should not be in the bundle but fetched from a URL.

**Comment by tijlleenders** [comment]
@pulkitvyas08 the images should be included as separate files in the /dist right?
This gets copied to the domain serving the webapp.

**Comment by tijlleenders** [comment]
Or do you mean the /dist folder when you say 'bundle'?

**Comment by pulkitvyas08** [comment]
Yeah I think I used those words interchangeably. Those images in the `/src/assets` folder end up in `/dist`, we don't want that. Fetching from URL is the best way to go

**Comment by pulkitvyas08** [comment]
> 

Yes, that's the gist of it. If we are loading it as an asset of the project then it will increase the first time loading period

**Comment by tijlleenders** [comment]
Explore implemented using hints now.
