### ISSUE TITLE
Make basic My Time page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#432]
Broken down into the following issues:
- #474 
- #475
- #476
- #477
- #478
- #479

**Comment by Tushar-4781** [comment]
![image](https://user-images.githubusercontent.com/39093015/175335835-8d5182cc-7b64-49b0-a045-848876ab1502.png)

@mallikarai05 @tijlleenders these are not just random colors, right? the number of colors == the number of goals on that particular day correct?

**Comment by tijlleenders** [comment]
Yeah you're right.
They will be calculated based on colors and durations of the tasks of that day with free time being calculated as 'light grey'.

For now just use dummy data.

**Comment by tijlleenders** [comment]
Could you maybe start by breaking this down into multiple issues.
I agree this one is too big...

**Comment by tijlleenders** [comment]
I think #474 can be excluded from this.
The basic My Time page is done.

Next up is integrating it to the scheduler!

**Comment by Tushar-4781** [comment]
since Scheduler is ready. #474 can be included now

**Comment by tijlleenders** [comment]
Only remaining issue to close this is #474 
However, this is not part of the basic MyTime page as we don't need the collection to show the Tasks returned from the scheduler. This will only be important when we start storing state about Tasks - and that will probably be appended to the Goal schema - so that it can be fed back into the scheduler.
