### ISSUE TITLE
Design way of sharing and getting suggestions

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#440]
How to integrate below into the UI?

You can share your idea's anonymously. Technically you can share a list-subList combination.

From the pool of anonymously shared idea's from other people - you can get suggestions. Technically you submit a list title and you get suggestions for subLists. You could also submit a list title and you get suggestions for parent list titles.

**Comment by tijlleenders** [comment]
![image](https://user-images.githubusercontent.com/44887755/174472539-d9c1d3fe-deb7-4486-a1df-6565e8d9bcfa.png)

**Comment by tijlleenders** [comment]
Functionally there are three ways of sharing:
- Anonymous
- Public
- Selective (choose individuals)

Technically there are a few ways to share:
- via ZinZen server
- via a URL shared with app of choice
- via decentralized system

We'll focus on sharing via ZinZen server first as this is the most user friendly (if you're not super privacy minded / trust ZinZen) and easiest to implement and learn from.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/177008447-7b5649d5-003f-445e-b982-f4e0594b73df.png)
![image](https://user-images.githubusercontent.com/73054648/177008467-8271f70d-04e2-432c-b438-c0dca335c461.png)

**Comment by mallikarai05** [comment]
@tijlleenders will these be okay for now?

**Comment by tijlleenders** [comment]
Yeah, great!
