### ISSUE TITLE
Design way of showing magic text

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#441]
In a goal/list title, design a way of visually distinguishing magic words from normal words.

Magic words are words in the title of a list that trigger extra functionality. For example, "walk 1h daily" has two magic words: "1h" and "daily". "1h" is interpreted as "duration:1h" and "daily" is interpreted as "repeat:daily".

For ease of use, the default interpretation of a magic word is that it was intended. So you could add "walk 1h daily" to your goals without even going to the Add goal page and selecting the suggestions. (agree?)

To undo magic application of the word, one needs to preface the word with an underscore - or go to the Add Goal page to unselect the badge corresponding to the word.

**Comment by mallikarai05** [comment]
While typing the text-
![image](https://user-images.githubusercontent.com/73054648/175096253-a037ea21-5cde-4b85-aef4-acd07b08cff6.png)

**Comment by tijlleenders** [comment]
Nice!

And the dark theme?

For not-while-editing only italics then?

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/175771562-b97be523-b541-46db-880e-b5d46d180935.png)
After editing the text would appear in italic and a little smaller. 
As discussed yesterday, the duration and frequency of each goal will be visible in the list.
I'll add the design for the dark theme along with the design for URLs

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/175772035-8c092c33-05cc-42ff-a450-6bb97bf01761.png)
In case of a URL - it will be treated as a goal only but when you click on the text it with give the above 2 options

**Comment by tijlleenders** [comment]
Let's try that!

The link design is a different issue ... but also looks good. I was actually thinking of having the link being recognized as magic text - replaced by URL in italics when you add it + space or enter. That way you can add it next to a goal like "Enroll for exams on Monday _URL_".

Can you do a dark version - or is that not needed for the dev side (standard light=>dark translation pattern)?

**Comment by mallikarai05** [comment]
I think to add a URL like that it will be better if we provide an additional input field on the Add Goal page and if the URL is added directly as the goal title it can appear as above?

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/175806263-90b9c499-a1c1-4e1c-8af7-d9aedc48e33c.png)
Though the Light and Dark theme colors are already fixed for the magic text while editing the hex code will be #E490AC
I'll add it to the roadmap as well

**Comment by tijlleenders** [comment]
> I think to add a URL like that it will be better if we provide an additional input field on the Add Goal page and if the URL is added directly as the goal title it can appear as above? 

Strongly against creating extra input fields. We already have an extra button to change the color. Then we add one for the URL. What's next? In a gew weeks we'll have a cockpit page full of buttons...

The interface should be one text field only. We can discuss with team on Friday if you like.

**Comment by mallikarai05** [comment]
Okay agreed, so it is best to have only one input field and you add the URL there and it is recognized. I'll add the final design to the URL issue.
