### ISSUE TITLE
Add Tests for MyFeelingsPage & AddFeelingsPage

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#443]
Cypress and Jest tests have to be written for this page.

**Comment by Tushar-4781** [comment]
I plan to follow these docs written here https://npm.io/package/fake-indexeddb for writing the jest test cases. @pulkitvyas08 @tijlleenders  what are your thoughts on this. we need to mock the indexDB so plz comment down your opinions if you have any.
PS: Hoping for an early response XD

**Comment by tijlleenders** [comment]
Isn't this getting complicated?

Can't we have an end-to-end Cypress test go through a scenario? If it fails we just have to check the db state to see if it is a UI problem or db problem.

**Comment by Tushar-4781** [comment]
> Isn't this getting complicated?
> 
> Can't we have an end-to-end Cypress test go through a scenario? If it fails we just have to check the db state to see if it is a UI problem or db problem.

yup cypress can be used for end-to-end testing. we can test the functionalities/ApiCalls indirectly by checking UI is updated or not. Checkout #541

**Comment by pulkitvyas08** [comment]
> I plan to follow these docs written here https://npm.io/package/fake-indexeddb for writing the jest test cases. @pulkitvyas08 @tijlleenders what are your thoughts on this. we need to mock the indexDB so plz comment down your opinions if you have any. PS: Hoping for an early response XD

Yeah this is good. Browser coverage is not much but hopefully, it will run everywhere for the devs
