### ISSUE TITLE
Make the menu for clicking ZinZen like on https://zinzen.me/ using relationships

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#46]
After clicking ZinZen, the user should see this, but in the new UI style:
![image](https://user-images.githubusercontent.com/44887755/152559033-98fb363a-ce50-48da-9d22-64dde7034117.png)

This data is hardcoded but allows for multiple languages.  
We should add the GitHub repo link and a Donate option.

Also include 'Donate' and 'Feedback' button.

Clicking on the three bar ZinZen logo should redirect to the home (the one with my goals)

**Comment by mallikarai05** [comment]
@tijlleenders can you please add a description for this issue.

**Comment by tijlleenders** [comment]
This one is hardcoded - so not using the local 'goal' and 'relationships' repository.

**Comment by tijlleenders** [comment]
Still some formatting to be done for the dark theme:  
![image](https://user-images.githubusercontent.com/44887755/164376219-e75ce64c-dbf7-4be8-b8ce-f7f2c8af1fe1.png)
