### ISSUE TITLE
Rethink Add Feelings popup layout

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#463]
Can you update the design of the Add Feelings Popup.

I made the decisiom to move the "I feel..." to above the buttons. This is merged into main already.

New design:
![image-1.png](https://user-images.githubusercontent.com/44887755/175341295-4abb265d-eec8-4c84-b72e-e5d2cf7e3797.png)

Old design:
![image.png](https://user-images.githubusercontent.com/44887755/175341107-b56998aa-e679-4e27-a644-c4beb2dc7d56.png)

**Comment by Tushar-4781** [comment]
1st Suggestion: I was thinking of adding a + button with a dotted round border at the end of btns so if the user has a custom feeling he will click and the field will appear else not. here it looks like a mandatory  field cuz first time it confused me cuz *i feel* can mean different meanings 

 2nd Suggestion: we could write helper text "Couldn't find the feeling?" or "Is your feeling not listed. Type here" and we can store that feeling like a custom in the DB so later that feeling is there. In the future users could choose via tabs like the feelings which we give and the collection of his/her custom feelings. just like favorites tab in whatsapp

**Comment by mallikarai05** [comment]
The design is updated for now.
@Tushar-4781 I agree with the first one, I think if something is added with the + button it\ should directly get saved in the database then? (but I think it will be better to have both the input box and the plus button)

**Comment by tijlleenders** [comment]
Thanks for updating @mallikarai05 !

Let's keep this issue open in the backlog.
Low prio as this is fine tuning features - not adding them.

**Comment by tijlleenders** [comment]
Discussion closed. Made #1977 to implement conclusion.
