### ISSUE TITLE
Make goal magic optional

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#467]
Right now it is compulsory to add "1h" and "daily" to a goal.
It should be optional.

So "Walk" and "Walk 1h" are valid goals and should be stored.
It is not compulsory to enter "Walk 1h daily".

**Comment by pulkitvyas08** [comment]
@tijlleenders so is "Walk daily" a valid input?

The issue here is that the user can type "daily" and not want the task to repeat every day. What is the assumption we are taking here?

**Comment by pulkitvyas08** [comment]
IMO for now, I'm making a PR that does both - adds the frequency in the database and also shows the user what they have written as the title. I'll update the PR if that's not what you want
