### ISSUE TITLE
[BUG] addGoal btn isn't at bottom right 

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#482]
On MyGoalsPage, addGoal btn should at bottom right 
![image](https://user-images.githubusercontent.com/39093015/175782264-3701a549-5c47-472c-a19e-bd95b9cf4dc1.png)

**Comment by nishant-666** [comment]
How to get added as a collaborator?

**Comment by tijlleenders** [comment]
> How to get added as a collaborator?

Hi Nishant, thanks for your interest.

You don't have to be an official collaborator to contribute. You can always fork the repo and submit a PR to this repo.

Instructions can be found here: https://docs.github.com/en/get-started/quickstart/contributing-to-projects

I'll email you some info on the project.

**Comment by nishant-666** [comment]
I have opened a pull request. Please check once.

**Comment by tijlleenders** [comment]
Closed by #484

Thanks a lot Nishant!
