### ISSUE TITLE
Create A toggle button to compare the changes of normalization on MyTimePage

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#490]
#481 was resolved by #488, a normalization feature was introduced. But to compare the changes which are made by the feature we need to have a toggle button that can flip the changes btw normalized and non-normalized color of widths. the toggle button can help us to test multiple scenarios ( by altering or changing the order of our task durations )

**Comment by tijlleenders** [comment]
We're talking a toggle function that can be called from browser dev tools right?
Nat an actual button in the UI.

**Comment by Tushar-4781** [comment]
@tijlleenders I have created it on UI but don't worry it can be removed very easily. I just created it temporarily it can also be hidden.
