### ISSUE TITLE
Decide color palette for My Time

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#492]
We need a few distinct colors for the Tasks in My Time which can be used to categories tasks

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/177034210-4f06e0b9-c0a7-4fea-83b0-feadd9d69942.png)
I tried these colors which are different and can be used for now, most of them can be used for both dark and light settings

**Comment by tijlleenders** [comment]
Cool, let's try them!
Can you add the codes?

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/177036741-97896646-c912-4e06-9f5d-b111233d981a.png)
I'll add it to the roadmap.
