### ISSUE TITLE
Improve contrast design / guidelines

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#499]
Now that we have the option to change the color of a Goal we're runnong into readability issues due to low contrast.

Please find existing guidelines we can follow to avoid this.
For example https://webaim.org/resources/contrastchecker

![Screenshot_20220628-174134_Gallery.jpg](https://user-images.githubusercontent.com/44887755/176222469-5bc199bf-425d-43a9-ab85-4097fda9ea56.jpg)

**Comment by mallikarai05** [comment]
I read a few articles and went through some resources for dark UI colors, usually, there is one primary color or 2 for dark UI, in our case, we might need a lot of them. I tried a few shades that went well according to the guidelines and are popular on the dribble.
![image](https://user-images.githubusercontent.com/73054648/191804766-5c60fca7-7a1b-4d5c-b46d-bbaa9bc53139.png)

**Comment by mallikarai05** [comment]
I tried a few colors and found consistent ones for both light and dark themes. We can work around them!
![image](https://user-images.githubusercontent.com/73054648/191805001-0e6afbcb-df92-409e-91b1-1602c640ec6a.png)
![image](https://user-images.githubusercontent.com/73054648/191805084-cfe57990-de8c-4970-811f-be50053b02cf.png)

**Comment by tijlleenders** [comment]
Nice work!

**Comment by tijlleenders** [comment]
@mallikarai05 Could you also add the codes of these colors aa text?

**Comment by mallikarai05** [comment]
#D95946
#A963B9
#7879CB
#509167
#E91E63
