### ISSUE TITLE
Show Goal color for subGoals too

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#500]
We now show the custom Goal color ... but it doesn't work for subGoals yet.

Technically in the previous version of the app I used to not make a difference between Goals and subGoals. It's just a oage where you render the list + the corresponding breadcrumb. Maybe that's something that can be refined here too. Would probably require to be broken down into several issues.

...or just add it to the subGoals page!

**Comment by pulkitvyas08** [comment]
Yeah my bad, I should've checked it out. Subgoals and goals use different components as some functionalities are different (like sub-goals cannot have a sublist at the moment) so changing one did not affect the other
