### ISSUE TITLE
Assets should get served from cache

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#504]
The following svg assets and the font should get served from cache:
![image](https://user-images.githubusercontent.com/44887755/176261111-6ad166a4-feaa-4646-9561-12d248be1991.png)

Now they're slowing the page by 2 seconds on a slow 3G connection.
If they were served from cache this would be milliseconds.

**Comment by GithinjiHans** [comment]
In my PR they're being served from cache...I think we should now work on precaching the assets to increase the speed of the assets rendering from cahe.

**Comment by tijlleenders** [comment]
@GithinjiHans I'm a little lost. Are you responding to the PR Review comment?
If so, can you reply to the comment in the PR, not in the issue?
