### ISSUE TITLE
Change what clicking on a goal does

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#505]
Right now:
Click on a Goal opens sub icons.
Click on > goes to subGoal.

Wanted:
Click on a Goal goes to subGoal.
Click on > opens sub icons.

**Comment by pulkitvyas08** [comment]
Isn't this conflicting with #469 and #489?

> Wanted:
Click on a Goal goes to subGoal.
Click on > opens sub icons.

If clicking on the goal sends you to subgoal then you won't have the option to edit the title by clicking twice. What exactly is the expected behavior here?

**Comment by tijlleenders** [comment]
Hi Pulkit, good catch.
This is indeed a new direction.
I closed the referenced issues (as not planned).
