### ISSUE TITLE
SubGoals should inherit all properties except duration+repetition

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#507]
SubGoals shpuld inherit all properties except duration+repetition:
- color
- language
- ... future properties as start and deadline

Duration and repetition are the exceptions and  are not inherited. 

Duration is not inherited so that you can subdivide a time budget into smaller parts. If you have a Gym workout of an hour and you put in subGoals - not all the subGoals should be an hour too, right. 
Repetition is not inherited. If you repeat your Gym workout daily, the repetition only has to be on the goal - not the subGoals. The prepocessor of the scheduler will handle repeating the tree as a whole.

**Comment by pulkitvyas08** [comment]
I'm a bit confused about the tasks that will be used by the My Time page, the schedule for which will be generated by the pre-processor + scheduler. Initially, I thought the goals from the MyGoals page will double as tasks for the My Time page. Then I saw #474 which indicates that there needs to be a different collection (than the "Goals" collection) for these tasks. But now this issue seems to convey that the goals are indeed what will be used by the My Time page. 

Can you please clarify this

**Comment by tijlleenders** [comment]
Hi @pulkitvyas08 ,

You're absolutely right to bring this up. Tasks are indeed a different collection than Goals. Since the scheduler is not ready @Tushar-4781 took the shortcut of using them as Tasks. The 'pretty' way would be to have a function that doubles as the scheduler and creates the Tasks from Goals locally - not using the Goals directly. This might become necessary if we get too far ahead of the scheduler. I don't expect it for before another week or two.

**Comment by pulkitvyas08** [comment]
Okay makes sense, As we don't inherit every property of a parent goal in a subgoal, spreading the properties of the parent goal is not an option. So I'll just add code to inherit the color of the parent and leave comments in the schema and code to make sure that when other properties are added to goals we decide on inheriting them or not

**Comment by tijlleenders** [comment]
@Tushar-4781 This has been in progress for a while.
Move it back to backlog or is it implemented?

**Comment by tijlleenders** [comment]
@Tushar-4781 
So it looks like the tags get copied over correctly - only there is a moment where you don't see them.
Immediately after pressing + the tags are not visible.

![copied_tags_dont_appear_immediately](https://user-images.githubusercontent.com/44887755/212410502-fe07f778-a0c5-4abf-81f2-9099e770452b.gif)

**Comment by Tushar-4781** [comment]
oh i didn't knew you were looking for the tags while adding, i thought if tags are not passed by user then we have to use the one from parent.

**Comment by Tushar-4781** [comment]
@tijlleenders  But if tag appeared before title it would not look good as appearance of tag means they appear in field too and in this case they would appear without title. lets take this case in next version of goal parser

**Comment by tijlleenders** [comment]
@Tushar-4781 Yes, you are right - if we auto-add the tags then they should also appear in the title - which can be confusing if we're adding a brand new one - and see a bunch of text before we even enter the title.

Let's keep it the way you propose and solve this problem in #936 
**This issue will be closed by #934 .**

**Comment by tijlleenders** [comment]
It's working for lower levels, but not for subGoals of the root goal:
![root_level_subgoal_not_getting_color_of_rootgoal](https://user-images.githubusercontent.com/44887755/213094979-db3e5b28-7656-4f7d-877e-af3c5b19328d.gif)

**Comment by Tushar-4781** [comment]
@tijlleenders  hi, i think as per our discussion we concluded that parent tags will be added if the same tags are not added while creating a goal right ?. because in current state adding tags means editing title. I think we created #936 to resolve this issue
