### ISSUE TITLE
Roadmap: Make MyTime the default entry page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#509]
In general, the MyTime page will be the most frequented page - so it makes sense to make this the default entry point of the app.

Please adapt the roadmap and navigation to reflect this choice.

When a user first starts, we'll have to put in some default Goals/Tasks (like "Sleep daily 8h @22") but that will be a different issue.

**Comment by mallikarai05** [comment]
@tijlleenders agreed but for first-time users, there should be a way to know all the features hence dashboard should be visible, after that my time can be the default page?

**Comment by tijlleenders** [comment]
The idea is to logically branch out from MyTime to the other pages - so dashboard page would not be needed at all.

Example: 
- There would be a way to go fron a Task to view/edit the corresponding Goal
- When you have a free time block the can be a way to add a Task/Goal or Explore
- ZinZen menu/options/Explore might also be reached through the Menu button

**Comment by tijlleenders** [comment]
For now we can put the dashboard page behind the 'three bars logo' topright on the MyTime page?

That way we don't have to do too much work (re-use dashboard) - but we can experience the way it 'feels' to have the MyTime as entry point?

**Comment by mallikarai05** [comment]
This makes sense! Good call
I'll update the roadmap

**Comment by mallikarai05** [comment]
Updated!
