### ISSUE TITLE
Make Goals with URL property open URL

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#513]
Whenever a Goal has a Link/URL property and it gets clicked in MyGoals it should copy to clipboard or open as shown in roadmap:

![Screenshot_20220702-135130_DuckDuckGo.jpg](https://user-images.githubusercontent.com/44887755/176999611-81c5629c-bbd7-4e13-8ae0-71e9137240d3.jpg)

Blocked by #433 and #434

**Comment by tijlleenders** [comment]
@Tushar-4781 I think this can be worked on as design and link property are done  now:
![Screenshot_20220724-075711_Chrome.jpg](https://user-images.githubusercontent.com/44887755/180634475-186be730-ac07-405e-aff1-0401d5766871.jpg)

If you want to implement a simpler/different design that is also fine - as long as we get a choice to copy or goto the URL/link.

**Comment by tijlleenders** [comment]
#434 is not really blocking as Link property can also be removed by removing the link text.

**Comment by Tushar-4781** [comment]
Blocked by #576
