### ISSUE TITLE
Design 'empty' MyTime slots

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#521]
Now:
Only scheduled Tasks are shown on the MyTime timeline.

Wanted:
Add a greyed out/dotted line/empty circle with a little + and the number of hours of free time in between tasks - bit only if there is free time in between the Tasks.

This allows you to:
- see how much feee time slots you have per day
- see how big each of them are (x hours)
- click the + to add a Task/Goal from the MyTime page

**Comment by mallikarai05** [comment]
@tijlleenders when you expand the tab for a day can there be small plus for each interval (maybe 1 hour) between scheduled tasks so you can add Tasks accordingly. Here the lower limit will be the end of the previous task so you and the upper limit the start of the next one (like in Upwork) so you can only schedule in the given interval?
![image](https://user-images.githubusercontent.com/73054648/177024867-9d598556-7161-4994-92c4-391aad09d8e1.png)
Like in the image a small '10:00' and a plus next to it?

**Comment by tijlleenders** [comment]
Yes, ok to put the starting time next to the +.

I think we should have only one + per period of free time. So if there are three hours of free time there is only one + with text "3h" instead of three +es with "1h" each.
If you don't want to use up the blick you can always add a duration yourself.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/177027907-1c67b1d4-6470-4cb4-ad3c-a70351fef5a2.png)
If there are multiple slots between 2 tasks I don't think the start time will be useful
Will this design work then?

**Comment by tijlleenders** [comment]
Good idea to leave out the time.

The design above is good. 

Can you change the outline of the circle to match the line size and color of the line between Tasks? Maybe also do the + in that format. The + will distract / attract too much attention if not very quiet/discreet...

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/177031269-00552f49-58b5-4bec-905f-4708614bfd1c.png)
Which of these 2 would look better?

**Comment by Tushar-4781** [comment]
@mallikarai05 can you provide the full image because i can't see these changes on figma board

**Comment by mallikarai05** [comment]
@tijlleenders I'll confirm the final design and then add it to the board. The last design for MyTime is on the board though, I think you need to check #509

**Comment by Tushar-4781** [comment]
actually, i was asking for this one.

> ![image](https://user-images.githubusercontent.com/73054648/177031269-00552f49-58b5-4bec-905f-4708614bfd1c.png) Which of these 2 would look better?
> 
> Also, with the time next to it ![image](https://user-images.githubusercontent.com/73054648/177031345-6a564a2b-309f-4a6e-855d-e8046e15e11b.png)






Cool
> @tijlleenders I'll confirm the final design and then add it to the board. The last design for MyTime is on the board though, I think you need to check #509

**Comment by tijlleenders** [comment]
This is probably much better already.
I was thinking a hollow circle with the + in the same color as the line, but let's try this and see if it is still too distracting.

**Comment by mallikarai05** [comment]
@Tushar-4781 I'll update the roadmap
