### ISSUE TITLE
Add new color pallette to Add/Edit Goal page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#524]
In the roadmap there are now a lot more colors available for the color of a Goal. These need to be 'hooked' to the function that changes the color of the goal.

![image](https://user-images.githubusercontent.com/44887755/177036724-72e9d0f7-95cf-42b5-b89a-c2df0651eff3.png)

**Comment by Tushar-4781** [comment]
@tijlleenders @mallikarai05 all of the colors would be available for use, or only the colors chosen for the theme would be displayed.
