### ISSUE TITLE
Provide the source of all icons used in ZinZen

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#528]
Currently, we are not using some of the icons that are there in the designs. We need all the icons from one place ( icons library ) or maybe store them as svg in our assets.

**Comment by mallikarai05** [comment]
https://drive.google.com/drive/folders/1V0FDHTqNUupFyOTtHc8C-N22P0C_rGs9?usp=sharing

**Comment by tijlleenders** [comment]
Perfect!
We can just add them to the repo right?

**Comment by mallikarai05** [comment]
Yes, I'll make an issue for it and add them.

**Comment by tijlleenders** [comment]
> Yes, I'll make an issue for it and add them. 

@mallikarai05 What is the issue for adding the icons to the repo?
