### ISSUE TITLE
Improve 'share anonymous' icon

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#531]
The current share anonymous icon needs to be redesigned:
![image](https://user-images.githubusercontent.com/44887755/178134480-77a18cf1-3a97-4151-bd87-eeeaccc21f4e.png)

Maybe put a diagonal bar through it?

**Comment by GithinjiHans** [comment]
![Screenshot from 2022-07-16 23-37-49](https://user-images.githubusercontent.com/92337850/179371288-0ed437b6-4897-4f0f-9909-f5f4641ee91b.png)
I gues this gestures enough that one is anonymous

**Comment by tijlleenders** [comment]
@mallikarai05 Can you work with this?

@GithinjiHans Is this something you found on the net or something you made? If you find it, can you provide the reference so we can chexk the license?

**Comment by GithinjiHans** [comment]
I found it on the net. I'll share the link in a few.

**Comment by GithinjiHans** [comment]
My bad. Unfortunately, we can't use it (subject to copyright). Next time I'll check any asset's license before proposing its use in ZinZen.

**Comment by tijlleenders** [comment]
Superceded by #630
