### ISSUE TITLE
Design suggestions page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#532]
After pressing on the ? button (above the + button) while browsing on the MyGoals - archived goals should appear at the bottom of the goal list with a clearly distinguishable look&feel, ie semi-transparent, crossed out, dotted outline.

When pressed, the archived goal becomes part of the 'real' list again.

Example use case:
A packing list where if you go on a trip again you'd use the suggestion button to see if you haven't forgotten to take anything that you usually take on such a trip:
![Screenshot_20220801-074015_Chrome.jpg](https://user-images.githubusercontent.com/44887755/182082001-58401aef-2707-4dcb-a413-461bd2e2eda3.jpg)

**Comment by mallikarai05** [comment]
@tijlleenders is the question mark only available on My goals or the Sub goals too. 
In case of My Goals: 
Will it then display all the archived goals
In case of Sub goals/lists:
It can display the ones which match the goals (A packing list is a goal so if we are looking for archived goals in it, it can look for the keyword 'packing' in the archives)

**Comment by tijlleenders** [comment]
Hi Mallika,
The logic of how we make the suggestions is not a concern here - it's just about how we show them. Can you make a design for that?

...

But to answer your question: 
any Goal has the suggestion button. It will suggest 
- anything from the archive
- anything from the internet anonymous community (if you agree to sending the parent title to ZinZen to execute that query).

So if I have a packing list called "camping packing list" and I previously had a few goals on there that I've archived, tapping the ? will suggest anything I've archived/completed previously".
If I choose to enable anonymous internet queries, I'll also see what other people in the world have put directly under "camping packing list".

The matches on parent are exact for now.

If you then have a sublist "cooking stuff" you can get suggestions "pots", "pans", "camping gas" etc for that too by pressing ?.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/183288310-baf3617e-923c-4239-8214-fa280fba7dd9.png)
I'm not sure where exactly we should add the '?' button, as @Tushar-4781  suggested last time if we have it at the bottom-right corner of the page it can be a problem in case of too many goals (as it was for the plus) but having it at the top is too much traffic 
I tried it placing it next to My Goals 
![image](https://user-images.githubusercontent.com/73054648/183288401-3d40dc39-9a71-43ce-bd5f-4502446b51fa.png)

**Comment by tijlleenders** [comment]
I really like the ? design!

Now the + looks a lot less 'zen'...

Also wonder about the positioning. My feelong is that all general 'action' buttons should be in the same place, either on top right or bottom right. We chose top - but then the header gets a little crowded. Maybe drop the 'ZinZen&reg;' altogether? You can get back to My Time by tapping <- a few times anyway...

**Comment by tijlleenders** [comment]
... or ? can only appear once on the Add Goal screen, so after you press + to signal the intention to add something.

If you have something to add in mind, you can. If not you press a second time in the same place - essentially a slow double tap.

**Comment by mallikarai05** [comment]
> ... or ? can only appear once on the Add Goal screen, so after you press + to signal the intention to add something.
> 
> If you have something to add in mind, you can. If not you press a second time in the same place - essentially a slow double tap.

So should we drop the '?' and double-tap the + for suggestions?

**Comment by tijlleenders** [comment]
No, that's not what I meant.

My proposition is:  
- show the + on My Goals page top right
- show ? On Add Goal page top right

**Comment by mallikarai05** [comment]
This can work!
It will also help with keeping the header less crowded.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/183306081-7e332b99-75a4-4731-aba9-e2790b2ab8db.png)
I think having the '?' on the Add Goal Page is a good idea!

**Comment by Tushar-4781** [comment]
ummm.... @tijlleenders @mallikarai05 why don't we put all those icons in one menu? something like this
![image](https://user-images.githubusercontent.com/39093015/183341962-eebac0f8-f790-4191-b1af-80dbfdaf5ea8.png)

**Comment by tijlleenders** [comment]
I've thought about @Tushar-4781 suggestion but think it is less suitable for two reasons:
- from the list of things in the picture, only Goal is relevant for us. Tasks are auto-created via a Goal. We don't create Events or Reminders etc. @Tushar-4781 What woukd be the list of things that appears?
- the expected most recurring action is add Goal. We should enable that as a single tap.

**Comment by Tushar-4781** [comment]
@tijlleenders umm i was hoping that list will only appear if u hold for 2 secs

**Comment by tijlleenders** [comment]
Ok, long press on a + button seems a little hidden like 'unlock dev options' - not sure how many people would discover/use that.

What would be the options once long-pressed?

**Comment by mallikarai05** [comment]
If we have a menu button that on a single tap expands to give options- that might work.
But we only have '+' and '?' at the moment. It does not make sense to have an entire menu for it.

**Comment by tijlleenders** [comment]
Yeah so let's go with the two-step process. + on My Goals and ? on Add Goals.

@mallikarai05 We need a simpler 'add to my Goals' icon. I really don't understand this one:
![image](https://user-images.githubusercontent.com/44887755/183733899-bb8be5ec-bbe7-4dab-9e57-0252a04f1111.png)

**Comment by tijlleenders** [comment]
@mallikarai05 since this issue is hanging we went ahead and decided something in #589 :

1. 
There will be two tabs in the Suggestions view that shows at the bottom:
- My archives (shows archived subGoals for the Goal we're adding to)
- Anonymous suggestions (shows what other people have added as subGoals for the Goal we're adding to)

If there are no results, don't show the tab.

In the future, if there are no archives and no anonymous suggestions - we might implement a feature to ask 'the world' for suggestions - but that's way down the road...

2.
We'll replace the current 'zipper with an x' icon with a simple +.

**Comment by tijlleenders** [comment]
This is the implemented design, so without + buttons - they'll just clutter in my opinion.
Catch/up and add any improvements whenever you have time.

![image](https://user-images.githubusercontent.com/44887755/185556278-a0cc1d7c-4429-4788-9b5e-3d12b8cb818e.png)

**Comment by tijlleenders** [comment]
Superceded by #634 
@mallikarai05 The roadmap needs to be updated accordingly.
