### ISSUE TITLE
Call the scheduler on MyTime page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#533]
Blocked by #572 

On the MyTime page, convert the default goals (see #572) to call the scheduler and use the answer to create the MyTime Tasks for the day.

How we integrate is discussed in #361

**Comment by tijlleenders** [comment]
Adding @Tushar-4781 and @pulkitvyas08 to help out as this is on the critical path for the app's killer feature) and not moving.

**Comment by Tushar-4781** [comment]
@tijlleenders i think #585 can unblock it now ?
