### ISSUE TITLE
[Discussion] "Agree on API" for sharing goal anonymously

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#534]
In the MyGoals Page, we are allowing user to share their goals anonymously. For that, @tijlleenders suggested to use documentDB. For that we need to implement an POST api call and its request body will be having the type mentioned below. 
{
    "createdAt": "Tue Jun 28 2022 00:00:00 GMT+0530 (India Standard Time)",
    "duration": 3,
    "finish": "Tue Jun 28 2022 07:00:00 GMT+0530 (India Standard Time)",
    "goalColor": "#443027",
    "parentGoalId": -1,
    "repeat": "Daily",
    "start": "Tue Jun 28 2022 04:00:00 GMT+0530 (India Standard Time)",
    "status": 0, 
    "title": "Gym"
}

I request @pulkitvyas08 @mallikarai05 @GithinjiHans to comment below your thoughts. if you have any before we move ahead with the implementation of the same

**Comment by pulkitvyas08** [comment]
This is not a type, this is an example of a post body. Provide a type definition for a fruitful discussion

**Comment by Tushar-4781** [comment]
> This is not a type, this is an example of a post body. Provide a type definition for a fruitful discussion

my bad accidentally wrote **type**. this req body will be inserted in the document DB .

**Comment by GithinjiHans** [comment]
I think the req body is good but about the "status"...what does it do?
In the scheduler it's not defined but maybe we might need it

**Comment by tijlleenders** [comment]
> I think the req body is good but about the "status"...what does it do?
> In the scheduler it's not defined but maybe we might need it

This is (amongst other things) why we want ValueTypes in #535

**Comment by tijlleenders** [comment]
The parentGoal should not be shared by ID (those are internal to the app install) - but by title. Only sharing a title has no use for others as there will be no way to suggest it; we need to search on parent title to then suggest the subGoal title.

**Comment by tijlleenders** [comment]
If there are no more comments we shoukd move ahead with this. We can always change the implementation later.
