### ISSUE TITLE
GoalParser not detection the duration and frequency

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#551]
The integrated GoalParser only detects duration and frequency if all letters are written in lowercase. But if we write starting letter in uppercase or all the letters in uppercase. It fails to extract. 
Issue: 
![image](https://user-images.githubusercontent.com/39093015/179693927-df171a94-dede-446c-9557-4de8b8e0cd4f.png)

**Comment by Tushar-4781** [comment]
only if you type Daily it work but in other cases like if we type once it does not work.

**Comment by GithinjiHans** [comment]
I'll handle that today

**Comment by tijlleenders** [comment]
@GithinjiHans there's usually a global case insensitive flag in regex libraries.
