### ISSUE TITLE
SubIcons not showing on simulated mobile in Chrome/DuckDuckGo

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#556]
Wanted:
SubIcons accessible in Chrome / FireFox / DuckDuckGo simulated mobile and real mobile

Current:
Only works in FireFox simulated mobile (haven't tried the real mobile FireFox)

**Comment by tijlleenders** [comment]
![2022-07-22 no sub icons](https://user-images.githubusercontent.com/44887755/180384023-2b17a6da-d8b9-4b6f-a02b-7a8bf2156a09.gif)

**Comment by Tushar-4781** [comment]
It's happening because the area of the div containing the icon is very small.
