### ISSUE TITLE
Complete discussion on the my time design

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#560]
Right now the design is this:
![image](https://user-images.githubusercontent.com/44887755/180402167-a2cccf91-a30a-46fb-a84e-01c51919ae67.png)

There are some possible concerns raised:
1. How will we know the 'grey circles' are clickable free time?
2. How will we be able to easily click on them as they are quite small?
3. How will we see how long a certain task takes?
4. ... feel free to supplement @mallikarai05 @Tushar-4781 @pulkitvyas08 @GithinjiHans

**Comment by tijlleenders** [comment]
@mallikarai05 mentioned :
If when we expand 'Today' and we can have a little text at the top which says- "You have X(X is the total number of dots in between tasks)hours free today" or something so can know how many hours are there and then the dots will make more sense- and every time you schedule something it would change- So if I had 8 hours free and I used 1 hour by clicking on the line/dots- next time it'll say You have 7 hours free

Something like this?
![image](https://user-images.githubusercontent.com/44887755/180404592-faa76910-87a7-43fd-9b01-d9a7cea64547.png)

**Comment by tijlleenders** [comment]
Also suggested, the total number of free hours (or other hints) we build in to explain the 'grey balls' could disappear after a set period (ie week) or after it has been used x times.

**Comment by tijlleenders** [comment]
@mallikarai05 Can you add some of your new idea's here?

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/180837922-1422ae41-506a-47ba-8dbe-4d982467a841.png)

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/180838186-69e42b83-ffb2-4103-b63d-04014bc933db.png)

**Comment by tijlleenders** [comment]
@Tushar-4781 suggested we should only have one grey + ball, ie to the left of 9h free.

**Comment by Tushar-4781** [comment]
We can make it a 2-step process. Initially, the timeline will appear as it was designed at the beginning. Now we can add a rectangular shape button that says "Add Task". As the user clicks on it the (+) button will appear on the btw edges and right adjacent to it will be the hours so that users can see how much time gap is there between different tasks now they will simply choose among those as per their convinience.

PS: 
Even if a very busy person uses our app he/she will choose any free slot because that person values his time. And since we are showing hrs available adjacent to (+) btn that indication is sufficient.
As far as people having a normal routine is concerned they will have the timeline in their mind once they start following the MyTime page. Therefore (+) btn _duration_   is sufficient acc to me. @tijlleenders @mallikarai05 what are your thoughts on this

**Comment by Tushar-4781** [comment]
Moreover, I think Let's go from simple design because as our users will shoot feedback we can add more details step by step. 
PS: save some updates for the future. Can't give everything at once aye ? XD

**Comment by tijlleenders** [comment]
OK Let's go for the last design then.
We can even leave out the +'s as that is not needed if we use a central button.

@mallikarai05 Can you make the final version with the add button?
Probably similar to the + button to the bottom right on the My Goals page?

**Comment by tijlleenders** [comment]
@mallikarai05 @Tushar-4781 The more I think about it ... the more I think that the add button on MyTime bottom right should add a Goal, not a Task.
1:1 mapping is OK, but there are a few reasons for always creating Tasks via Goals:
- Task are auto-generated by the scheduler ; don't mess with that by allowing manual creation too
- Things might grow or get more complex ; what starts out as a Task might become a project / Goal with many Tasks
- The button is also present on the Goals page, so having identical functionality is good ; it would be confusing otherwise

**Comment by mallikarai05** [comment]
> @mallikarai05 @Tushar-4781 The more I think about it ... the more I think that the add button on MyTime bottom right should add a Goal, not a Task. 1:1 mapping is OK, but there are a few reasons for always creating Tasks via Goals:
> 
> * Task are auto-generated by the scheduler ; don't mess with that and add complexity by allowing manual creation too
> * Things might grow or get more complex ; what starts out as a Task might become a project / Goal with many Tasks
> * The button is also present on the Goals page, so having identical functionality is good ; it would be confusing otherwise
> 
> What do you think?

I agree. 
Should we eliminate the +'s from My Time? And add one at the bottom right corner only? 
But in that case we need a separate page to add the time for the task?

**Comment by tijlleenders** [comment]
No need for a new page, we can reuse the addGoal page.

**Comment by mallikarai05** [comment]
But in this case, don't we need to mention the start and end times if we are manually adding a task?

**Comment by tijlleenders** [comment]
Good point, 

If you have free time today and the Task length fits, the scheduler find the first compatible slot automatically - so no need to add a time constraint.

Once the Task is scheduled, we could also add a 'pin/fix' feature for if you don't want the automatically chosen placement/time for the Task to move anymore. It would be an addition sub choice next to Forget / Reschedule / Done.

**Comment by tijlleenders** [comment]
...if you do have a preference for a certain time just type @11 (or the time you prefer).

**Comment by mallikarai05** [comment]
That is a good idea! We can also add **'by 16'** if there is something I want to do before a particular time.

**Comment by tijlleenders** [comment]
Discussed on Friday and roadmap is updated.
