### ISSUE TITLE
Design checkmark for completing Tasks

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#574]
Completing Tasks is a central part of the experience.
It should be fun and beautiful.
A nice looking checkmark is part of that.

We can keep it simple, but why not add a little character?

**Comment by tijlleenders** [comment]
![image](https://user-images.githubusercontent.com/44887755/181872612-76c34040-0efc-48b0-ba86-cec14417b267.png)

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/182433322-3eb3f3c6-2147-46f8-ad10-87956428ec1b.png)
I tried it roughly. This also gave me the idea oh having something like a thunder icon + check kind of symbol (if that was what you had in mind)

**Comment by tijlleenders** [comment]
I wasn't thinking about lightning really - thide came fpm havingt two letters 'Z'. 

The tunderbolt could be an idea, especially because I would like an animated completion action, but in my view it doesn't really fit the overall look & feel.

**Comment by mallikarai05** [comment]
You might be right.
What do you think about the design above?
Can we work around it?

**Comment by tijlleenders** [comment]
Good for now, is there a svg version?
Then you can do CSS magic like draw the path little by little.

**Comment by mallikarai05** [comment]
Yes, I'll add it to the roadmap, it can be exported from there
