### ISSUE TITLE
Move update goal button

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#577]
The layout of the Add and Edit Goal screens can be improved by moving the action buttons together and getting rid of duplicate text:
![Screenshot_20220801-072527_Chrome.jpg](https://user-images.githubusercontent.com/44887755/182078128-ace5c09c-cda5-4cb5-b3d8-b22b625e825b.jpg)

**Comment by tijlleenders** [comment]
Also the 'Add your task...' text can disappear as it is already in the input box prompt.

**Comment by tijlleenders** [comment]
@GithinjiHans can you mark this as draft until it is ready for review?

**Comment by tijlleenders** [comment]
@GithinjiHans
Good thing from the delay in implementing this is that it gave us reason to think about the necessity of the button itself.  
It is actually not required. I've made #621 to remove it and save after every edit.

**Comment by GithinjiHans** [comment]
We'll close this one and focus on other issues that matter instead.
