### ISSUE TITLE
Make URL part of title, whole Goal title is a link

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#582]
When adding a longer title and a URL it is clear that these are implemented as two divs:
![Screenshot_20220807-203830_Chrome.jpg](https://user-images.githubusercontent.com/44887755/183306111-544e6136-3749-4fea-87f1-2deb16eaff64.jpg)

Wanted:
The URL get added to the Goal title as text. No underline. Whenever the Goal is clicked you don't go to subGoal level but are taken to the link in a new window (same as clicking - on <u>URL</u> now).

**Comment by Tushar-4781** [comment]
@tijlleenders then how we we will go to the sublevel

**Comment by tijlleenders** [comment]
Good point, let's keep this for now.
