### ISSUE TITLE
Filter goals to be sent to scheduler

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#619]
To allow using the app for normal lists (ie shopping list, packing list, todo list, bookmarks) the scheduler should not be sent all goals but a filtered list of goals:
- hasDuration == true
- is part of the chain that leads to a leaf goal that has a duration

For each goal that has a duration, the chain of parent goals leading to root needs  to be sent too, even if the intermediate goals don't have a duration.

Otherwise the My Time screen will fail to show anything - and we can't play around with the sheduler while also using (hierarchical) lists.
![image](https://user-images.githubusercontent.com/44887755/185840244-00662a46-19e8-4333-88a6-2c1a83eb43fa.png)

**Comment by Tushar-4781** [comment]
To close this issue, we need the latest build the of scheduler which can handle allow option fields i.e. Repeat, Start, Due, startTime, endTime.

**Comment by Tushar-4781** [comment]
Blocked by https://github.com/tijlleenders/ZinZen-scheduler/issues/71

**Comment by tijlleenders** [comment]
Unblocked.
Notice that the rule to only send root goals has been removed. The scheduler will figyre it out (not implemented yet) so scheduler will fail for now.

So only filter condition is that goals sent to the scheduler should have a duration.

**Comment by tijlleenders** [comment]
Will reschedule this in a new, clean issue #918
