### ISSUE TITLE
Revamp AddGoal and suggestions

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#634]
How this all started:
===============
When I'm in Shopping list and ask for suggestions I might get: 
- Bananas
- Pears
- Apples

If Apples are already on the list - I don't want that to show.

Similarly, if Pears was not present on the list, it should show. But after I select Pears to add it to Shopping I want the Pears to visually change on the suggestion list (for example lighter tone text / + ). This will show it was not on your list when you opened the suggestion menu, but you've now added it.

I'm hesitant to say remove completely from the suggestion list as for things like shopping lists you might want to add something multiple times...

Maybe this needs some discussion around design. 

Current idea:
=============
Not make a separate popup screen but to show suggestions 'in/below' your list as semi-transparent - and you just click them to make them 'real'.

Continuing on that trend, a separate AddGoal screen might not be ideal either. After pressing + one could scroll to the top of the list so any pre existing items (if any) would scroll down and nearly disappear - showing the new one with blinking input and placeholder text "Type your goal + 1h + daily". The search bar would disappear too. While typing you would get the same tags as on the AddGoal page. They show below - and the English tag would already be present. If you click away it or top right check - it would be saved and you can see any pre-existing items + scroll again.

If you tap the ? after tapping the + you then scroll to the bottom and see the suggestions added semi-tramsparently and you can scroll/tap them.

This avoids having to navigate to a separate AddGoal/Suggestions page from which you have to navigate back - which is confusing.

Only problem is how to show/signal impossible scheduling asks - as that will refuse to save. If you click away with a goal the scheduler shows a red tag 'impossible' and it refuses to save.

Another issue: how to change colors?
Use a color tag. Tag wpuld not disappear when clicked but cycle through the colors - and update the Goal under edit.

**Comment by tijlleenders** [comment]
![20220911_145500.jpg](https://user-images.githubusercontent.com/44887755/189528719-5b10d1f3-4bbc-4071-93ac-f7ca9c7cc9d8.jpg)

@Tushar-4781 is this enough guidance for a first implementation?

**Comment by Tushar-4781** [comment]
@tijlleenders, yup, it's more than sufficient. Thnx

**Comment by mallikarai05** [comment]
The final design for this has been added to the roadmap.

**Comment by tijlleenders** [comment]
Shouldn't a public goal first expand when clicked - so you can check the properties?
![image](https://user-images.githubusercontent.com/44887755/191920407-4c111f6c-f320-4e5f-88e2-4098db1d335c.png)

**Comment by mallikarai05** [comment]
The tags somehow went missing, I had a discussion about this with @Tushar-4781 he suggested that-
If we click on the + the goal will directly be added to my goals but when we click anywhere else it would expand and show tags
![image](https://user-images.githubusercontent.com/73054648/191964683-eb36bc47-7d90-44a8-8c94-367284fd10c9.png)

**Comment by tijlleenders** [comment]
Huh that could be an idea but how would the user find out? The only option would be to have both icons.

**Comment by mallikarai05** [comment]
The problem with the < icon is that when we click on it for a pre-existing goal it expands to give these options
![image](https://user-images.githubusercontent.com/73054648/191966882-033ff9ce-b710-477b-860b-0329d979028e.png)
If clicking on < displays tags for public goals it might be confusing for the user

**Comment by tijlleenders** [comment]
Ok so we keep only the +.

If we click the +, it gets added directly.
If we click anywhere else on the goal, it expands to show tags.

It's not super intuitive (how do you find out you can also NOT click the + ... but at least the + icon does as expected, and we don't use < in unexpected ways.
