### ISSUE TITLE
Pre-fill goals for new user

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#635]
We need to make the My Time page look nice for a first time user by filling in some standard goals before first use.  
**These are also the things we would minimally need to start using it ourselves.**

- Nice and different colors
- Following goals
  - "Sleep daily 22-8 8h" OK on scheduler side, UI todo
  - "Breakfast daily 6-9 1h"
  - "Lunch daily 12-14 1h"
  - "Dinner daily 18-21 1h"
  - "Walk daily 1h 14-20"
  - "Water the plants indoors 1h every 3 days"
  - "Drink water every 4 hours daytime"
  - "Run 5km 1-3x/w 1h"
  - "Me time 1h daily"
  - "Work 35-40h weekdays daytime"
  - ... Anything else you think is nice to add for a first user

**Comment by Tushar-4781** [comment]
"Work 35-40h weekdays daytime"
"Drink water every 4 hours daytime"

"Run 5km 1-3x/w 1h"

Have to exclude these 3 as the patterns used in these are not ready.
