### ISSUE TITLE
Design screens for sharing 1:1

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#643]
Based on initial sketch - think through / improve the screens for sharing 1:1 and add this to the roadmap
![signal-2022-09-09-093005_002](https://user-images.githubusercontent.com/44887755/189813836-5c445502-0a12-4e60-9708-d4e13b8cee99.jpeg)

**Comment by mallikarai05** [comment]
I am almost done with a few things, there are a few screens I need to discuss. @Tushar-4781 let me know when you are free to connect!

**Comment by mallikarai05** [comment]
I have added all the final screens to the roadmap with the new theme.
