### ISSUE TITLE
Design UI for syncing on different device

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#644]
What are the steps to setup sync on different device?
- Create a share with link for a contact named device2 or whatever you want to name the device to share with
- Open the ZinZen link on the new device
- Open the partner mode and go to the original device actions
- Choose accept all changes automatically

Alternatives considered:  
- Use a QR code to authorize or a magic one-time link?
QR code is basically a link underwater...
A QR code requires extra step with camera (authorizations)

**Comment by mallikarai05** [comment]
I think using a QR code is a good idea! or when the user first opens it on a device if we have a screen where you can choose if you are already a ZinZen user and then login (if possible and if you want to)?

**Comment by tijlleenders** [comment]
Well, we need a way to get to the QR screen from settings too just in case you 'miss' it in the initial setup so I'm not sure if we have to bother with it in the initial intro screens as it will confuse first-time users...
Maybe add sync as a less visible third option on the intro/skip intro screen?

Can you do a sync without resetting the existing goals - allowing you to 'merge' accounts?

**Comment by mallikarai05** [comment]
@tijlleenders I think if you sync up 2 devices the existing goals should merge, there might be a few conflicting goals but we can let the user work through that
