### ISSUE TITLE
Design for background gradient

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#648]

**Comment by mallikarai05** [comment]
I have tried these gradient effects for the background for far.
![image](https://user-images.githubusercontent.com/73054648/191805244-8838c161-7e3a-47d6-bd66-bc3e32401fc7.png)
![image](https://user-images.githubusercontent.com/73054648/191805278-b5ccf8d0-fe8e-43e8-bf97-eae54549d18b.png)

**Comment by tijlleenders** [comment]
Looks good!
Can you add the two other patterns too?

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/191918504-8b6218e2-a43b-4a0f-8742-79f916bd831c.png)
![image](https://user-images.githubusercontent.com/73054648/191918558-7fbfbdc3-4a80-4640-8288-09f19f703a1b.png)
These?

**Comment by tijlleenders** [comment]
Yes, thanks!

They're a little to 'present' vs the foreground - but the principle is sound.

**Comment by mallikarai05** [comment]
I tried a few more gradient colors for the background
![image](https://user-images.githubusercontent.com/73054648/192044881-0f8cfb4f-87a9-43b4-be8e-cabf15719362.png)
![image](https://user-images.githubusercontent.com/73054648/192044946-be90cdca-b00d-4eed-ba67-0fda301fb8da.png)
