### ISSUE TITLE
Make final list of light / dark theme compatible colors

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#651]
There were some colors on the roadmap and there are some new colors in #499 

We need a final list in the roadmap.

**Comment by tijlleenders** [comment]
The current ones are not bad, right?
![signal-2022-09-23-103600](https://user-images.githubusercontent.com/44887755/191922443-f1591018-008c-4c1d-a3c7-998e13b0c950.jpeg)

**Comment by mallikarai05** [comment]
I removed the colors that were too similar--These colors are for My Goals only(when you want to associate a color for each goal, I'll update the new theme colors in a separate issue)
The hex code for all these colors is there along with the color (It's also available on the roadmap)
![image](https://user-images.githubusercontent.com/73054648/192042132-80724687-9dee-4ca0-9434-2337ca3dc0b1.png)
