### ISSUE TITLE
Add illustration sources

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#652]
@mallikarai05 

Can you add a directory with the image sources for relevant images - I suppose you made them in inkscape, illustrator or similar app and there is an editable format other than PNG?

Please also make sure it doesn't get included in the app build.

**Comment by mallikarai05** [comment]
I have added the illustration in SVG format and made a PR

**Comment by tijlleenders** [comment]
Can you request a review on the PR when it is ready?

Did you check if the illustrations don't get included in the build?

**Comment by mallikarai05** [comment]
Yes, I did. It's not getting included.
