### ISSUE TITLE
Expand goal when clicking on public suggestion instead of + in roadmap

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#659]
When adding goals from public there should be an option to see the tags associated before adding.

This is missing from the roadmap:
![Screenshot_20220925_073900.jpg](https://user-images.githubusercontent.com/44887755/192430570-cb46d2b0-ec70-4c77-b4f8-a618d0bfe17a.jpg)

**Comment by mallikarai05** [comment]
I have updated the roadmap.
