### ISSUE TITLE
Fix the element container line heights and alignments 

### ISSUE THREAD

**Issue by Tushar-4781** [tijlleenders/ZinZen#669]
![image](https://user-images.githubusercontent.com/39093015/192825086-a0f4f4b6-0de4-41a7-b944-432c8b94922d.png)
![image](https://user-images.githubusercontent.com/39093015/192825130-5646d390-2dce-47b5-9b7c-1db2c1bef8fd.png)

**Comment by mallikarai05** [comment]
@Tushar-4781 yes I came across this, I fixed a few screens. This might be happening because a lot of the screens are not frames I am converting them to one. This might take a while, if there is a specific design because of which you are stuck please let me know.

**Comment by Tushar-4781** [comment]
try to avoid copying the entire UI design ( which if of no use ) and modifying it. It better to create a another container based on the requirement. I tried to look at the design and this is the issue i found .
![image](https://user-images.githubusercontent.com/39093015/193195017-e1f746d1-2df8-42d5-be71-b87dc3208acb.png)

**Comment by tijlleenders** [comment]
Is it useful to integrate the design and the actual app in this way?

In my view the roadmap should only be a high-level visual guide - not something that is pixel-perfect and 'knows about' or prepares the implementation details.

**Comment by Tushar-4781** [comment]
@tijlleenders I copy and paste the design into a new file and I deconstructed the design. i m sorry but details have to be there how will I check the properties that have been decided for the component? I know you don't want a pixel-perfect design but at least basic functionalities like font, background color, transparency % & basic styling details are required which we can't figure out without inspecting the element ( which is inaccessible right now ).

**Comment by tijlleenders** [comment]
Yes of course that I understand.
I just want to stress we shouldn't overdo it.
I see the roadmap more as a way to hash out screen and UI/UX logic than anythong else.

**Comment by mallikarai05** [comment]
This has been fixed now that we have a new roadmap with new screens.
