### ISSUE TITLE
Design what a goal looks like while editing

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#671]
Goal titles are edited in-place so they should remain visually similar (ie same background color, placement on screen) but also different to show you that you're editing.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/193100291-b5c88020-823c-4f61-8b26-403cd8c4863b.png)
I can think of these 3 ways 
@tijlleenders @Tushar-4781 what do you think?

**Comment by Tushar-4781** [comment]
@mallikarai05 i prefer 2nd option

**Comment by tijlleenders** [comment]
Me too - but I also see that as an option to show the archive/public suggestions - ... although maybe with longer dots/stripes in the dotted line since many of these might be quite restless on the eyes.

**Comment by mallikarai05** [comment]
@tijlleenders so the archive/public suggestions are semi-transparent and with have a dotted boundary? I'll try that out

**Comment by tijlleenders** [comment]
@mallikarai05 Yes, but maybe not dots, but longer stripes and spaces - so it looks less 'busy/disco', more zen.

**Comment by tijlleenders** [comment]
For highlighting that we're editing I'm ok with either one (dots or stripes).
