### ISSUE TITLE
Why do we use multiple fonts?

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#673]
Right now:
dist/assets/montserrat-cyrillic-400-normal.cf31d26d.woff2       7.38 KiB
dist/assets/montserrat-latin-ext-400-normal.5d9974e2.woff2      9.98 KiB
dist/assets/montserrat-cyrillic-ext-400-normal.632ef59e.woff2   8.63 KiB
dist/assets/montserrat-latin-400-normal.a658b5f3.woff2          12.35 KiB
dist/assets/montserrat-all-400-normal.0861e14f.woff             49.54 KiB

Do we really need all these different fonts?

It might look insignificant, but this all adds to size which negatively affects user experience through longer waiting times and higher internet/hardware utilization.

**Comment by tijlleenders** [comment]
Currebt fonts can be cleaned up when #713 completes.

**Comment by Tushar-4781** [comment]
@tijlleenders can you confirm if this issue still exists ?

**Comment by tijlleenders** [comment]
@Tushar-4781 
Yep, this is resolved.
