### ISSUE TITLE
Show sharing status in sub menu

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#679]
Sometimes I forget if I've shared something. Rather than having to remember what I've shared and how I'd like to see this info instead of the sharing icon.

So the anonymous sharing icon if I've shared anonymously and the public sharing icon if I've shared publicly. If I have shared 1:1 I'd like to see that.

Clicking on the icon would then give more information like the list of people you've shared with and whether you've shared anonymous or public too (but we can design this at a later stage).

**Comment by Tushar-4781** [comment]
@tijlleenders we are displaying contact icon on the goal itself and when u click on it name of the contact will be visible. I think we can close this, shall we ?

**Comment by tijlleenders** [comment]
Actually this is about customizing the subicon for non-collaborated goals. Should be inplemented at some point - but low prio.

**Comment by tijlleenders** [comment]
Having the contact showing is clear enough.
When it's a collaboration both avatars are shown.
