### ISSUE TITLE
Check out how service worker / offline PWA works

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#68]
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers

**Comment by tijlleenders** [comment]
If you have any questions, ping me on Signal.

**Comment by mallikarai05** [comment]
I went through these resources too. They are quite good at explaining the whole working and setup. 
https://www.simicart.com/blog/pwa-offline/
https://medium.com/samsung-internet-dev/pwa-series-service-workers-the-basics-about-offline-a6e8f1d92dfd

**Comment by tijlleenders** [comment]
We used the create-react-app PWA template so also check https://create-react-app.dev/docs/making-a-progressive-web-app/
