### ISSUE TITLE
Fix MyTime default page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#684]
The default goals don't show up.
Not sure if this is since the new scheduler or if it was broken before.
![signal-2022-10-06-061044](https://user-images.githubusercontent.com/44887755/194213392-552122ef-74b7-4eac-812c-54f9544606d3.jpeg)

**Comment by tijlleenders** [comment]
On behalf of @Tushar-4781 :

Eric I want to know the current status of scheduler. 
1. Are we following the common schema
2. Can scheduler ignore the fields that are of no use ?

On behalf of @egithinji :
1. I believe so, except for the 'due' date
2. Yes

**Comment by tijlleenders** [comment]
@Tushar-4781 What 'common schema' are you referring to?

**Comment by egithinji** [comment]
There's this one from some time back that I've been basing the json input and output files on. From https://github.com/tijlleenders/ZinZen-scheduler/issues/37#issuecomment-1220757891:
```
input: {
goalid: number,
title: string,
duration: number,
start: String | date,
deadline: string | date
}

sorted Output : {
taskid: number,
goalid: number,
title: string,
duration: number,
start: String | date,
deadline: string | date } [ ]
```

**Comment by egithinji** [comment]
Also here is what the `Goal` struct looks like. It's in rust but @Tushar-4781 you can tell the optional fields (the ones with type Option<>). 
```
    pub id: usize,
    pub title: String,
    pub duration: usize,
    pub repeat: Option<Repetition>,
    pub start: Option<NaiveDateTime>,
    pub deadline: Option<NaiveDateTime>,
    pub after_time: Option<usize>,
    pub before_time: Option<usize>,
```

**Comment by Tushar-4781** [comment]
@egithinji if i pass this 
  id: number;
  title: string;
  duration?: number | null;
  sublist?: number[];
  repeat?: string | null;
  start: Date | null;
  due: Date | null;
  startTime: number | null;
  endTime: number | null;
  createdAt?: Date;
  status: 0 | 1; // 0 = active, 1 = archived
  parentGoalId: number | -1; // -1 = no parent
  goalColor?: string;
  language: string;
  link: string | null;
  
  can u extract the fields u need for scheduler?

**Comment by egithinji** [comment]
No that will not be deserialized by the scheduler into a `Goal`. There are several fields that are different or don't exist on scheduler side.

**Comment by Tushar-4781** [comment]
@egithinji yes, that's why i was asking. if we can ignore them at backend. else I have to filter the params that is accepted by scheduler

**Comment by Tushar-4781** [comment]
> There's this one from some time back that I've been basing the json input and output files on. From [tijlleenders/ZinZen-scheduler#37 (comment)](https://github.com/tijlleenders/ZinZen-scheduler/issues/37#issuecomment-1220757891):
> 
> ```
> input: {
> goalid: number,
> title: string,
> duration: number,
> start: String | date,
> deadline: string | date
> }
> 
> sorted Output : {
> taskid: number,
> goalid: number,
> title: string,
> duration: number,
> start: String | date,
> deadline: string | date } [ ]
> ```

alright then I think I can follow this one for now. And its clear that we have to create the format at frontend which is accepted by scheduler. @tijlleenders any objections or suggestions before I move ahead on this ?

**Comment by tijlleenders** [comment]
@Tushar-4781 I think this is outdated as the scheduler can already handle multiple cases of repetition and I don't see a repeat tag in here.

You can see for yourself here : https://github.com/tijlleenders/ZinZen-scheduler/tree/main/tests%2Fjsons

These are all valid instances of the schema.

**Comment by Tushar-4781** [comment]
@tijlleenders  oh yes, will include repeat tag for sure

**Comment by Tushar-4781** [comment]
@tijlleenders @egithinji we are missing after and before tags also

**Comment by tijlleenders** [comment]
See https://github.com/tijlleenders/ZinZen-scheduler/blob/main/tests/jsons/every-wednesday-1/input.json

This is a test case currently supported by the scheduler. It has after_time and before_time

**Comment by Tushar-4781** [comment]
@tijlleenders alright, i will configure the schema like this then. but @egithinji whenever possible try to shift to this schema

id: number;
title: string;
duration?: number | null;
sublist?: number[];
repeat?: string | null;
start: Date | null;
due: Date | null;
startTime: number | null;
endTime: number | null;
createdAt?: Date;
status: 0 | 1; // 0 = active, 1 = archived
parentGoalId: number | -1; // -1 = no parent
goalColor?: string;
language: string;
link: string | null;

cuz entire frontend features are using this only.

**Comment by tijlleenders** [comment]
Now the discussion is going somewhere!

Variable naming convention is different in TS and Rust. That explains some of the differences. 

@egithinji I think we should do the conversion inline during (de)serialization?

@egithinji Which of these are required by the scheduler?

@egithinji Which of these will never be used by the scheduler? 

@both Should we filter them out? Where?

**Comment by tijlleenders** [comment]
> Now the discussion is going somewhere!
> 
> Variable naming convention is different in TS and Rust. That explains some of the differences. 
> 
> @egithinji I think we should do the conversion inline during (de)serialization?
> 
> @egithinji Which of these are required by the scheduler?
> 
> @egithinji Which of these will never be used by the scheduler? 
> 
> @both Should we filter them out? Where?
> 

Oh I now see a whole part of the conversation from @egithinji that I missed somehow...

So @Tushar-4781 I think it is clear now that
- the frontend should do the filtering as you suggested since scheduler cannot handle extra fields - only optional fields. Which fields have to be filtered out can be deduced from the Goal struct Eric posted.
- Renaming can be done on either side but for now on frontend to keep the ball rolling

**Comment by Tushar-4781** [comment]
@egithinji 
![image](https://user-images.githubusercontent.com/39093015/198849126-7ba7197f-ded0-47cd-8c99-c6d524e0861b.png)
would u mind assisting me here? why scheduler is failing?
