### ISSUE TITLE
Add illustration to theme choice

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#689]
The design in #319 is good - but a little too minimal / pale in my opinion. 

It would be interesting to use the shared color palette of the light and dark theme to create some illustration for each choice.

For example,
- a landscape with a sun for the light theme 
- a landscape with stars and a moon for the dark theme.

**Comment by Tushar-4781** [comment]
@tijlleenders i think now we can close this one

**Comment by tijlleenders** [comment]
@Tushar-4781 
Yes, we don't have a theme choice anymore in the onboarding.
