### ISSUE TITLE
Feature list for MVP 2022-12

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#691]
**What is this issue?:**  
These are the features we want for the 2022-12 Most Viral Product (MVP)

**Why:** Increase the focus (prioritize) & make sure we don't miss anything
We can link the related issues here and/or have a tag for each feature.

**The killer features:**
- [x] The scheduler with text interface : type "Walk 1h daily" & let the calendar magic happen!
Need to scope this down : #635  

- [ ] Holistic personal calendar with simple overview and ability to 'postpone/push' stuff forward in time  
  #882
  #896
  #702
- [ ] UI & scheduler stretch goal: Hierarchy of goals (40h workweek with three projects) and fill up remaining time

- [x] Sharing goals/timeline privately
  - #745
  - #744
  - #759

- [x] Sharing private suggestions
  - #746
  - #747
  - #748
  - #750

Using the sharing button functions normally - no suggesting or notifying sharing to other people for now. 

- [ ] #916
- [x] Works offline first
- [x] Mood tracker
- [ ] Private by design
We have encryption at-rest and in-transit.  
That's good - but to make it great we need to add end-to-end encryption on top.
- [x] As free as possible / non-extractive / not for-profit
This is a promise for now: once there is revenue I'd like to work towards a foundation to formalize this.

**The features to make it Viral**:
- [x] Looks amazing from first page onwards (if not people don't even consider the product)  
#705
- [x] Simple (we need to deal with any necessary complexity)  
#319
- [x] Easy to use  
#709
- [x] Low to no initial cost
PWA optimized for low cost
- [x] Installs easily
Still needs some work on iOS... but maybe we focus on Android first?  
- [ ] Proves value fast
What use case can we use to prove this?
- [ ] Plays well with others
Documented open API for external use
- [ ] Return on Investment is obvious
Next to the killer features - we offer the many of the same features as a paid apps - but for free, open source and private-by-design!

We need to test these features with real customers before we check them off!

Am I forgetting something?

**Comment by tijlleenders** [comment]
@mallikarai05 @Tushar-4781 @egithinji @Y0h4n3s
Please contribute if anything is missing or if you disagree.

**Comment by egithinji** [comment]
I think it's also important for the app to handle impossible-to-schedule tasks before launch.

**Comment by tijlleenders** [comment]
> I think it's also important for the app to handle impossible-to-schedule tasks before launch.

Added #701

**Comment by tijlleenders** [comment]
Most of this is done - remaining issues will be picked up in normal backlog
