### ISSUE TITLE
Increase readability of edit

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#700]
Right now if you have a few constraints and edit the title goes offscreen and it is hard to read.

Wanted : show existing tags in their shortened form so there is less text and it is easier to read:
- "xh" instead of xhours
- remove any start today (will be added implicitly)

**Comment by tijlleenders** [comment]
@Tushar-4781 This issue is not adressed by the PR.
It's about shortening the long form of 1hours to 1h in the edit screen:
![image](https://user-images.githubusercontent.com/44887755/212411594-f32bde3d-6cd4-46e9-bb57-8112f5ef623f.png)

**Comment by Tushar-4781** [comment]
misinterpreted. cool fix it
