### ISSUE TITLE
Make design brief for outside designer consultation

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#705]
What we need:
- A fitting typography with free license
- Guidance on how to redesign the existing two main screens (MyGoals and MyTime)
- Theme should be suitable for extreme personalization - more than light/dark
- A hint of a design language to develop more screens

About the app:
ZinZen® is a fun life planner with collaboration.
ZinZen® helps you and your partner balance your lives with your priorities, plan your time realistically, and remember important stuff on time.
The app is non-extractive, open source and as free as possible. Slogan: "Realize dreams together".

Backstory brand:
"Zin" stands for passion, excitement, drive 
and "Zen" stands for relaxation, peace, in-the-moment.
Zin and Zen should be in the right balance.

Target audience:
In principle the app should be for everyone, students, etc ... but to get the features right and also possible find revenue we need to focus on a particular segment. I think this should be relatively rich couples (a few $ for an app is not a problem), both working, with children 30-40 years old.

Budget :
We're an as-free-as-possible open source app in the pre-MVP phase... so no revenue. Let's start with a consultation, a couple of hours for a first proposal, and another meeting to discuss ongoing coaching the possibilitities.

Timeline:
We need an well-designed MVP implemented before the end of the year, so getting a better sense of direction for the brand/design language in the coming two weeks would be great.

Inspiration:
Nature, sunrises, sunsets, open lakes/mountain views, rounded corners, gradients, meditation, starry night, wonder, awe, simplicity, autonomy, community, trust, collaboration, love.

**Comment by mallikarai05** [comment]
@tijlleenders Okay! I'll start working on this.

**Comment by mallikarai05** [comment]
https://docs.google.com/document/d/17uijObjtLLshdk2o9Pcsfrx6u-2bvnl_VvDFAq3VRyc/edit?usp=sharing
I'll add things to this doc, @tijlleenders @Tushar-4781 if you have something that needs to be added here's the link

**Comment by mallikarai05** [comment]
The doc has been updated with the final changes.
