### ISSUE TITLE
Rethink goal parser

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#708]
Interaction effects occur with the current implementation of detecting and removing tags. 

Example:
"Title start 12/3 @4 after 2" will not recognize the start hour because of the after tag.

Is it OK to have tags influence each other's detection? In what situations?

If there are situations - which I doubt - how will I know when typing that the goalparser ignores my text?

If anything - if there is any logical inconsistency between tags - shouldn't it be the job of the scheduler to signal this?

‐----

Having the possibility to recognize the name of the day of the week without having to specify "on" like "Pick up X Thursday" instead of "Pick up X on Thursday" would also be nice - but will probably cause issues with the current implementation?

**Comment by Tushar-4781** [comment]
@tijlleenders In that case you have to display some kind of error message. if you are trying to redefine a tag or its property. for example, the presence of @ in the start tag can't allow after or vice versa
