### ISSUE TITLE
Remove dashboard + switch Time/Goals with Logo

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#709]
Problem: 
Navigation via dashboard is slow and not accessible on all pages (+ om right, logo in middle and back button left).

Solution:
Use the ZZ logo as a switcher between My Time and MyGoals.

Stretch goal if not too complicated: Swiping left/right also switches between the MyTime / MyGoals screens.

**Comment by mallikarai05** [comment]
@tijlleenders I agree, this would be faster for the users too.

**Comment by Tushar-4781** [comment]
+1

> @tijlleenders I agree, this would be faster for the users too.

**Comment by tijlleenders** [comment]
Ok, so I removed the suggestion label.

**Comment by tijlleenders** [comment]
Actually, maybe we can just have two main pages: MyGoals and MyTime.

Pressing the ZZ logo would 'flip' the screen like a piece of paper between them.

MyContacts/Settings can be accessed from top left avatar.

Feelings would have to be integrated to the MyTime view - but that seems logical since it was basically already a calendar. Adding a feeling would be an extra option under the + top-right.
