### ISSUE TITLE
Design switching between identities

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#710]
After #709 the topleft dashboard icon on MyTime/Goals/Feelings is not useful anymore.

The proposal is to replace this with an avatar. Clickong on the avatar allows you to get a dropdown of contacts you can 'become'. After becoming a contact you will no longer see your Goals/Time but the other persons Goals/Time they've shared with you. Editing will result in sending a suggestion.

**Comment by mallikarai05** [comment]
@tijlleenders @Tushar-4781 are we still planning on this?

**Comment by Tushar-4781** [comment]
@tijlleenders i think we can close right ?

**Comment by tijlleenders** [comment]
I'm the only one wanting this feature it seems.
Let's mark it low-prio. I want to check this with some users. There are cases where switching could be interesting, ie for managing children's schedules.

**Comment by mallikarai05** [comment]
@tijlleenders okay, we can discuss it a bit first and see how things would work in case of switching.

**Comment by tijlleenders** [comment]
Yeah it would basically work the same way in the UI - except:
- you see a different avatar
- any changes you 'make' are not made, but only sent as suggestions to the person you are switched to

**Comment by mallikarai05** [comment]
Yes, but does the MyFeelings page disappear? 
Do you only see the goals shared with you?
I have a few doubts about it, maybe we can discuss it in the next meeting

**Comment by tijlleenders** [comment]
Valid points!
The interface would be 'stripped' - and really feel different - also to avoid confusion that you're in you 'own' environment.

**Comment by tijlleenders** [comment]
I think this is relevant again with the #1151 PR. 
The Journal page could be a place where you can share notes/feelings with someone - just like the calendar and goals page is where you share your schedule and goals.

**Comment by tijlleenders** [comment]
Experiment is #1158
