### ISSUE TITLE
Create JSON Schema for ZinZen

### ISSUE THREAD

**Issue by egithinji** [tijlleenders/ZinZen#722]
Creating a [https://json-schema.org/](https://json-schema.org/) schema will help prevent issues like #684 . It'll allow us to use a schema validator on both front-end and scheduler to make sure our inputs and outputs are always valid.

But even if we don't automate the validation, we'll still have a human-readable schema that everyone can reference.

There's some converters that can infer a schema from documents (the json input.json test cases in the https://github.com/tijlleenders/ZinZen-scheduler/tree/main/tests/jsons/stable dirs).
The first one I found is https://www.liquid-technologies.com/online-json-to-schema-converter ... but maybe there's a little utility for it too that you can run on a larger number of files.

**Comment by tijlleenders** [comment]
@Tushar-4781 Do you agree to use this standard?

**Comment by Tushar-4781** [comment]
> @Tushar-4781 Do you agree to use this standard?

agreed, we can use **yup** too, its highly used in both frontend and backend as well.

**Comment by tijlleenders** [comment]
@thinkrapido FYI Based on your comments I'm removing the low prio label on this and moving it to the top of the backlog.

**Comment by vinaybadgujar102** [comment]
@tijlleenders Generated a JSON Schema based on "ISchedulerInputGoal Interface" using '[ts-json-schema-generator](https://www.npmjs.com/package/ts-json-schema-generator)' library. I also did some basic validations using following schema with some test data present in Scheduler repo and it is working fine.   

JSON Schema file:
[jsonSchema.json](https://github.com/tijlleenders/ZinZen/files/13198228/jsonSchema.json)

**Comment by vinaybadgujar102** [comment]
Restricted date-related fields and min-max (duration) fields which are based on hours.

Updated Schema
[jsonSchema](https://github.com/tijlleenders/ZinZen/files/13206084/jsonSchema.json)

**Comment by tijlleenders** [comment]
@thinkrapido Is this what you had in mind when talking about a formal spec of the API format?
