### ISSUE TITLE
Don't auto-add start and deadline to goals

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#726]
Right now start and deadline is being added to goals sent to the scheduler - even if not in the typed input.

Wanted: Only add start/deadline if they are explicitly typed by the user.

Example of this going wrong:
![image](https://user-images.githubusercontent.com/44887755/198867501-651b56ed-234e-4b49-9526-a2956ffd24b4.png)

**Comment by Tushar-4781** [comment]
@tijlleenders uhm scheduler can ignore them right?

**Comment by tijlleenders** [comment]
They are optional, so they don't have to be sent to the scheduler if that's what you mean.

If you do send them they will not be ignored.

**Comment by Tushar-4781** [comment]
@tijlleenders yes, let scheduler ignore them no ?

**Comment by tijlleenders** [comment]
Closed by https://github.com/tijlleenders/ZinZen-scheduler/pull/165
