### ISSUE TITLE
Make new design for add feeling page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#73]
Currently it looks like this:
![image](https://user-images.githubusercontent.com/44887755/154662183-c1cdb530-6ffc-4e48-ac00-0bca7387dd88.png)

This requires a redesign to make it look nice and fit with the new theme.

**Comment by mallikarai05** [comment]
![Group 155](https://user-images.githubusercontent.com/73054648/155681189-a3721a4e-e52b-4a1d-ad5c-01c1a07c3ac6.png)

**Comment by tijlleenders** [comment]
Great, can we replace the colors with emoji's?
The colors might already be associated with categories of things in the My goals view.

**Comment by tijlleenders** [comment]
How would the previously logged feelings show up after selecting "My feeling"?

**Comment by tijlleenders** [comment]
What would it look like on mobile?

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/156593420-90f33f8f-b0e3-4e19-b47b-bfa091d51b30.png)
When no feelings are logged.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/156615056-6d36fab4-9571-4139-8d9d-74f8cc6346e4.png)
When previous feelings are logged.

**Comment by tijlleenders** [comment]
Hi Mallika, looks good!
What does it look like on mobile?

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/156700130-c1d27a28-ecaf-435d-985f-25d8cf1f00f8.png)
Will this be okay for the mobile?

**Comment by tijlleenders** [comment]
I like!
I'll check with some testers but seems like good to go.

**Comment by tijlleenders** [comment]
The collapse ^ is a little different from standard navigation in a multilevel hierarchy but maybe a collapse is good for the last level. Let's discuss today.

**Comment by tijlleenders** [comment]
Comments testers:
They want to see the options.
Seems like a lot of negativity - only one in five options is on the sunny
side.

**Comment by tijlleenders** [comment]
Discussed today, we need a "Quick-add" option from the dashboard.
![image](https://user-images.githubusercontent.com/44887755/156739391-9ff2bed5-91fe-4fbe-962e-86c2bd658de7.png)

Clicking the + will take user directly to the page designed here.

**Comment by tijlleenders** [comment]
The two step process of dropdown or clickthrough for a feeling category is problematic.
Decision is to reduce the number of options for each category to 4-6 so that it all fits on one screen.
The selected ones would highlight. Pressing a selected one again deselects it.
