### ISSUE TITLE
Make new design for the Discover page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#74]
Currently it looks like this:
![image](https://user-images.githubusercontent.com/44887755/154662556-c5b14f2f-b3f4-4cc4-b33e-7d6db57905cf.png)

This needs a redesign to new look & feel.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/155683049-775496c8-7190-4abb-83c1-c01b82057b28.png)

**Comment by tijlleenders** [comment]
Can we align it left and use lowercaps except for the first letter?
The width of the buttons on desktop should not be too large compared to the text.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/156589960-8830074f-2a0e-447b-89d5-fa560c12d63c.png)

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/156590142-f1bdba42-ba64-4fb5-8d3c-2706d69f94d7.png)
![image](https://user-images.githubusercontent.com/73054648/156590771-415666ea-9339-4f6b-9ce3-cd30f381808f.png)

**Comment by tijlleenders** [comment]
All testers choae the design with even width.

**Comment by mallikarai05** [comment]
Okay then, We can finalize the one you reacted to.
