### ISSUE TITLE
Ask and show a whole week schedule on UI

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#742]
Right now UI shows today, which is copy pasted to the other days of the week

Wanted: show the whole week's schedule, from Monday to and including Sunday. If the current day is not Monday, cross out the previous titles of the days.

**Comment by egithinji** [comment]
@tijlleenders , @Tushar-4781 This is actually working if the fix committed by @Tushar-4781 here is merged: https://github.com/tijlleenders/ZinZen/commit/13c32f6e7ff9de36d36792c0dd309d9840c92501

But I had to delete my local ZinZen IndexedDB and refresh. There's nothing wrong on the scheduler backend.
![Screenshot from 2023-01-10 13-04-25](https://user-images.githubusercontent.com/51313777/211522807-202539fa-9038-48e6-b29a-a26536c502bc.png)

**Comment by Tushar-4781** [comment]
@egithinji what we meant is that scheduler should give the schedule of entire week i.e. all seven days with what is scheduled and what's not ( the impossible ). Currently it return the schedule of the current day. and if u the same is repeated in entire week in the UI. @tijlleenders can u confirm this?

**Comment by egithinji** [comment]
Please check comment on the above draft pr I've just made.
Remaining thing is to fix how the front end is putting all the tasks on the first day.

**Comment by tijlleenders** [comment]
@egithinji has given the issue back.
Only thing left to do is some formatting on MyTime page - the data is ready and in the right format.

**Comment by tijlleenders** [comment]
@Tushar-4781 #955 did break the UI as there is a new option array within every schesuled task returned. This shows a max three options for rescheduling, if any, and assuming everything else remains equal.

I guess we can add fixing that to the scope of this issue instead of making a separate one?
