### ISSUE TITLE
Access feedback and other pages via search

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#766]
Idea for discussion:
Access special pages like feedback, light/darl theme toggle, theme switcher, via search. It would appear as a special button right below the search query.

It's not intuitive and you would only discover it after using the app for a while, if you type an F or any other letter from feedback in the search bar... but you will find it at some random moment.

It could also be annoying so after first time maybe we need to require more than one letter (ie 2 or 3) too match before the button appears? 

![Screenshot_20221111_171856_Chrome.jpg](https://user-images.githubusercontent.com/44887755/201385220-3ef7b88e-e037-4375-98ed-1a709d773ec9.jpg)

Alternative or simple first solution is a gear icon in the avatar dropdown where you can access all settings.

Another alternative: long-press zz logo will take you to settings page.

**Comment by Tushar-4781** [comment]
@tijlleenders as per our discussion in Friday meet we should go with siderbar where will show all the options and it can be pulled by clicking on the avatar at top right on myGoals and myTime page

**Comment by tijlleenders** [comment]
Closed by #785
