### ISSUE TITLE
Make batch add easier

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#768]
Adding lots of items to a list one after the other (like when making a shopping list for the first time) has a little friction:
- after pressing + you need to move your finger down to + new for every item. This requires hand-eye coordination and takes focus away from the item to add.

Solution:
Move the dropdown up so that add new can be performed by two single taps on the + icon without moving the tap position:
![Screenshot_20221113_070243_Chrome.jpg](https://user-images.githubusercontent.com/44887755/201517272-9d5d6deb-3c96-4f9e-aad5-c6d5b90ad52b.jpg)

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/202913125-91300110-e8f8-48d0-bb9e-7c57279928d7.png)
@tijlleenders do you mean it like this? so the + for 'New' is right over the original +?
