### ISSUE TITLE
Design a user feedback page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#77]
Design the page to let the user send anonymous feedback.

**Comment by mallikarai05** [comment]
Should there be a star of points rating (probably out of 5)?

**Comment by tijlleenders** [comment]
Go with what you think is best.

**Comment by mallikarai05** [comment]
Should we add something else? or will this be okay?
![image](https://user-images.githubusercontent.com/73054648/163722605-a55d34ee-1c09-44e3-80c9-ee6fe775b7d9.png)

**Comment by tijlleenders** [comment]
Maybe add at bottom: "Your feedback is anonymous. If you want a reply
please als leave an email or a phone number."

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/164230017-2d40032f-1aba-4a4c-b220-f3754a57aed6.png)
