### ISSUE TITLE
Implement 2022-11 theme

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#779]

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/202897577-f26bbef4-7720-4ee3-8e21-acd62a77179c.png)
I think we can have these as the palette for the dark and light themes for now. @tijlleenders @Tushar-4781 need your opinion for finalizing these.

**Comment by Tushar-4781** [comment]
discussion on the enhancement of the themes can be discussed later but for now, it looks good I m only going to take the color palette and the rest other changes and even further modifications in UI will be made as soon as we are done with the current backlog of high prior tasks.. @tijlleenders what's your take?
