### ISSUE TITLE
Round corner of cards when on desktop

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#821]

**Comment by elyessAR** [comment]
Is this the desired result? and should we also do this for the week day cards? (this would be applicable only to devices width>768px)
![radius](https://user-images.githubusercontent.com/49849558/211719002-e31ff766-8303-4f3b-ac65-033f470ef858.png)

**Comment by Tushar-4781** [comment]
@tijlleenders i think this issue doesn't exist now, can you confirm

**Comment by tijlleenders** [comment]
@Tushar-4781 
Yes, we don't have cards anymore.
