### ISSUE TITLE
Strikethrough goal text when done - hide done when revisiting

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#822]
Strikethrough when marking it done (just like on MyTime page) - so don't hide it.

After navigating away and coming back - hide it in the archived area at the bottom.  
It would be nice if the strikethrough has the color of the goal.

**Additional context**   
This issue was previously implemented, but not in the way as specified in the issue.  
The crossed out goal now remains for a number of seconds, then suddenly disappears. This is surprising, confusing and also makes the position of the Goals suddenly change, causing you frustration when you want to tap some goal, and right before you hit it, it shifts to some other goal.

**Comment by tijlleenders** [comment]
@shoonyank Maybe this is something for you?

**Comment by Tushar-4781** [comment]
@tijlleenders , i hope this will be applicable for sublist only right ?

**Comment by tijlleenders** [comment]
@Tushar-4781 Why can't we archive a top level goal?

**Comment by tijlleenders** [comment]
@Tushar-4781 This is partly implemented now.

I think it is nice if we only strikethrough first, then hide it in archive only after navigating away.

Low prio, but still an enhancement over the sudden disappear now - even though we get a popup.
There is also a certain 'satisfaction' in crossing stuff out.
