### ISSUE TITLE
Change hint behavior

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#840]
Only search for hint if explicitly requested.

Yes, this means:
- showing a loader while waiting for the internet instead of auto-searching hints with loader when pressing + on a goal 
- showing a 'Awww... no hints. We'll keep looking!' message when you're offline or if there are no results
- not showing the hint if there are no results
- keep looking for hints in the background every 24h

**Comment by Tushar-4781** [comment]
can we say "No internet connection" if users click on the hint in offline mode?

**Comment by Tushar-4781** [comment]
what if there is an api call in processing ?

**Comment by tijlleenders** [comment]
> what if there is an api call in processing ?

"Searching for hints around the globe..."

**Comment by tijlleenders** [comment]
> can we say "No internet connection" if users click on the hint in offline mode?

"No internet. No worries. We'll keep looking!"

**Comment by Tushar-4781** [comment]
> > what if there is an api call in processing ?
> 
> "Searching for hints around the globe..."

No if any api call is in progress like feedback submission etc

**Comment by tijlleenders** [comment]
@Tushar-4781 
I can see that the hint API is not being hit by default anymore. That's a good step.

Have all the points in this issue been addressed? In my view:
- [x] showing a loader while waiting for the internet instead of auto-searching hints with loader when pressing + on a goal
- [x] showing a 'Awww... no hints. We'll keep looking!' message when you're offline or if there are no results 
- [x] not showing the hint if there are no results
- [ ] keep looking for hints in the background every 24h

The last point is OK - let's forget about pulling and push this from the backend: #935 
You'll get the hint automatically in the inbox once something is available.

**So the PR does close this issue.**

**Comment by Tushar-4781** [comment]
@tijlleenders  looking continuously is not i m thinking. Right i have another way of caching responses. lets discuss in later version of the same
