### ISSUE TITLE
Change duration field to string?

### ISSUE THREAD

**Issue by egithinji** [tijlleenders/ZinZen#841]
@Tushar-4781 In order to implement flex-duration goals like "Work 35-40h weekdays after_time 6 before_time 18", should we change `duration` field to string? Or do you have another suggestion on how to implement this. 

See https://github.com/tijlleenders/ZinZen-scheduler/issues/207

**Comment by Tushar-4781** [comment]
Yeah, I need to check the conflicts that can happen with other patterns. Will pick this issue right after share 1:1 feature because that is the only heavy roadblock in the MVP list. As soon as it's done we will pick this issue up immediately. works for you?

**Comment by egithinji** [comment]
Makes sense. @tijlleenders as far as scheduler is concerned I guess we can park this feature for later?

**Comment by tijlleenders** [comment]
Assume we'll use String on scheduler side for now - but keep it in a separate branch.

**Comment by Tushar-4781** [comment]
Duplicate of #878
