### ISSUE TITLE
Make browser lang the first choice and highlight

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#843]
Right now we already succesfully detect the browser language and show the "Choose your language" in that language.

If it detects something, that language should also be the first choice in the list, and it should be highlighted with an accent color to make it easier to select.

**Comment by tijlleenders** [comment]
@mallikarai05 please propose how we can highlight the choice.

**Comment by mallikarai05** [comment]
@tijlleenders  Can the text have a little shadow? 
I thought of giving the detected language button a background color but with the latest design of language choice, it won't fit well.
The present design:
![Lang Choice](https://user-images.githubusercontent.com/73054648/206867399-c8ebdeb8-95df-4922-83bf-09f91d26f2fd.png)

**Comment by tijlleenders** [comment]
I'm open to suggestions.

Please make an example of how it would look in light/dark mode. It needs to be applicable to many places (ie also accepting collaboration/suggestions/etc).

**Comment by mallikarai05** [comment]
![Lang Choice (2)](https://user-images.githubusercontent.com/73054648/206868371-941a6937-cab7-4b3a-86f4-bbfe3c6aa301.png)
![Lang Choice (1)](https://user-images.githubusercontent.com/73054648/206868373-9ffad6c9-0608-40d2-b04f-2ae292d72e8b.png)
Tried these 2 out!

**Comment by tijlleenders** [comment]
The shadow doesn't work.
I guess we go for the other option then.

**Comment by mallikarai05** [comment]
I'll update the roadmap with the second one then and make an issue for @Tushar-4781 to implement it.
