### ISSUE TITLE
Change colors for better contrast

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#846]
We need to improve these colors so that they are distinct, and the user can differentiate between colors to assign them to different goals.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/206843851-668d18b5-01bf-4bce-ae91-d48cb3c3b9f0.png)
The present colors.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/206857257-c82222e2-6055-446e-a1fb-a7db22146213.png)
These are the updated colors and pass the contrast test. 
@tijlleenders @Tushar-4781 need your opinion on these

**Comment by tijlleenders** [comment]
Can't judge like this.
Let's start using these and evaluate in a week or two.

**Comment by mallikarai05** [comment]
Will add these to the code for now and make a PR then!
