### ISSUE TITLE
Design: design the sharing screens for 1:1 sharing

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#847]
Need to decide how a goal would look once it is shared.
- [x] How goal looks when someone completes it
- [x] How goal looks when someone edits it
- [x] How goal looks when deleted
- [x] How added subgoals look

**Comment by mallikarai05** [comment]
@tijlleenders @Tushar-4781 
I need a few suggestions, for example, if I share 1:1 a goal with Tushar (get a copy link and send it to him and he clicks on the link) this will be the screen that will appear for him. 
![Collaboration invite](https://user-images.githubusercontent.com/73054648/206860002-8b629696-da6e-4eba-a269-fb4fe5751930.png)
Will this be okay?
Also, regardless of what choice you make, should the next page be the language choice?
and the text should read - 'You have been invited by Mallika to collaborate.  Would you like to accept the invite? ' 
or 'You have been invited by Mallika to collaborate on a goal.  Would you like to accept the invitation?'

**Comment by tijlleenders** [comment]
We can put the language in the URL as a variable, based on the language of the goal that was shared.
After that, the next page should be the onboarding screen (starting with language choice) - if the user has not initialized ZinZen in the browser (s)he is viewing this in.

**Comment by mallikarai05** [comment]
I'll start working on the collaboration screens then!

**Comment by tijlleenders** [comment]
"Collaborate with the person who sent you this link?" with answers "Yes, collaborate." (highlighted) and "No, I don't trust this person." is a better way of formulating it. The I don't trust can do a callback to inform the sender they need to give more context/explanation for the other person to go along. The initial link was clicked on so there is willingness...

We don't have the name of the person who is sharing the goal, so we can't use that. At no point in the app do we ask for it.

We could add the name of the goal to make it more likely the other person accepts... and/or let the sender preview and customize the message - but this is easier and more logical to do in the communication channel the sender uses. If I use Signal, I can send the link with a customized message easily. 

Keep it simple.
No need to add complexity to ZinZen for this.

**Comment by mallikarai05** [comment]
@tijlleenders @Tushar-4781 I think we are done with this so we can close this issue!

**Comment by Tushar-4781** [comment]
@mallikarai05 yes
