### ISSUE TITLE
Add Tired as a category of feelings

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#848]

**Comment by tijlleenders** [comment]
@mallikarai05 Please provide the list of feelings (including translations) and icon for this category in this issue.
Then @Tushar-4781 can implement the UI side.

**Comment by mallikarai05** [comment]
List of feelings for Tired:
sleepy
drained
exhausted
spent
worn-out
weary
These were what I had in mind, @tijlleenders @Tushar-4781 is there anything else that should be there? 
I can add the translations and the icon to the code directly tomorrow.

**Comment by tijlleenders** [comment]
Seems good. Let's try!

**Comment by tijlleenders** [comment]
@elyessAR  Do you want to give this a try?

**Comment by elyessAR** [comment]
sure @tijlleenders I'll work on this.

**Comment by elyessAR** [comment]
@tijlleenders @mallikarai05  do we have the feelings translations and the emoji for "Tired"?

**Comment by tijlleenders** [comment]
@elyessAR Good you ask!
For now you can use "drained", "sleepy" and "exhausted" - and if you have additional suggestions feel free.
For the icon probably something like 😓

This is a configuration thing and can be easily changed after the fact if we change our mind.
