### ISSUE TITLE
Discussion: text color for My Time page

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#851]

**Comment by mallikarai05** [comment]
@tijlleenders @Tushar-4781 need your opinion on this.
Right now on the My Time page if we expand a tab the color of the text is the same as the color of the circle next to it, I suggest keeping the text color black for the light theme, and white for the dark to make sure it's always readable. 
![My Time 2](https://user-images.githubusercontent.com/73054648/206868967-6c9f6d67-d52e-40cf-8d76-9f39471cdcdc.png)

**Comment by mallikarai05** [comment]
@tijlleenders @Tushar-4781 need your opinion on this.
Right now the text on the My Time page when you expand the schedule for a day is the same as the circle next to it. 
I suggest keeping the text color constant across all pages and only having the circles colorful. 
Sample design:
 
![My Time 2 (1)](https://user-images.githubusercontent.com/73054648/206869177-8859547a-8445-4df6-ac26-f6274d6bfa79.png)

**Comment by tijlleenders** [comment]
Agree.
It's too colorful if the text is colored too.

Also hard to read sometimes - but maybe that's because of the color choice?

**Comment by mallikarai05** [comment]
Regardless of what color we choose if the text is readable on the light theme it would be a little tough to read on the dark one and vice-versa...and I agree it will be too colorful.

**Comment by tijlleenders** [comment]
@Tushar-4781 if you agree please close this discussion issue.

**Comment by Tushar-4781** [comment]
Yup sounds good. We can have the text color same as per the theme instead of the goal color
