### ISSUE TITLE
Fixed position top menu on MyGoals

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#859]
If you quickly want to add and you come back to the app in scrolled down mode you're confused as there is no + button.

This can be avoided by making the top menu fixed position. 

Negative side-effect: This reduces the available screen size when keyboard is enabled on-screen but on most screens nowadays there should be enough left to edit so acceptable.

**Comment by Tushar-4781** [comment]
Doesn't exist anymore. Died somewhere in refractoring
