### ISSUE TITLE
Design toggle button instead of ZinZen logo

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#867]
For a first user, and even for an experienced user, it is not intuitive that the ZinZen logo switches between MyTime and MyGoals.

Proposal is to make a 'Switch' - but we have to discuss how to implement this in the new year when @Tushar-4781 has time.
It could have a big impact if we want to have a smooth animation as currently MyTime and MyGoals are separate pages.

Option 1: Switch with a clock 🕒 and a 'bullseye' 🎯icon.
Option 2: Text switcher like so, but then with 'My Time' and 'My goals' : 
![image](https://user-images.githubusercontent.com/44887755/209970913-2e022125-81f1-4c55-8432-e6198835618a.png)

**Comment by mallikarai05** [comment]
![WhatsApp Image 2023-01-02 at 3 59 35 PM](https://user-images.githubusercontent.com/73054648/210219650-01beace6-acf0-456b-a490-2e25453371b3.jpeg)
I checked the interface of Google Tasks, this might be a good way to switch between MyTime and MyGoals.
@tijlleenders @Tushar-4781 what do you guys think?

**Comment by Tushar-4781** [comment]
@mallikarai05  that's exactly what I was referring to earlier haha. I like it. +1 from my side.

**Comment by mallikarai05** [comment]
![image](https://user-images.githubusercontent.com/73054648/210978114-35a4c1ed-e5a2-48ae-8587-ae27f6cc867f.png)
@tijlleenders @Tushar-4781

**Comment by tijlleenders** [comment]
We decided to go with the proposal in #866 for now.
