### ISSUE TITLE
Fix dark mode checkbox

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#871]
Currently showing as an empty box.

**Comment by mallikarai05** [comment]
@tijlleenders can you please elaborate on this a bit?

**Comment by tijlleenders** [comment]
Sorry @mallikarai05 - not very descriptive; figured you'd know since we talked about it.

Anyway - you already fixed it - but we still need the dark version of this screen / checkbox:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/44887755/210262371-401e9ed1-6fae-4afb-9e7a-7c0a7a10e156.png">

**Comment by mallikarai05** [comment]
@tijlleenders it's already on the roadmap, Tushar needed it this evening so completed it. 
![My Goals](https://user-images.githubusercontent.com/73054648/210262689-32695d6b-9810-4b66-9c55-ffc7ee4fb679.png)
Adding it here as well!
