### ISSUE TITLE
Fix add contact in dark mode

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#872]
Currently not showing well in dark mode

Added a screenshot but on mobile it doesn't work...

Need a dark design for this screen:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/44887755/210262608-71a2f1c7-c8a8-4ee5-a92c-82b3817dc41e.png">

**Comment by mallikarai05** [comment]
![Share New 8 dark](https://user-images.githubusercontent.com/73054648/210608905-d5614626-a7c8-4400-bbb9-bd8136fd3383.png)
@tijlleenders is this okay?

**Comment by tijlleenders** [comment]
Yeah fine for now.
A little confusing as it is identical to add Goal button. Ok for now.

**Comment by mallikarai05** [comment]
We can try it out a bit! 
@Tushar-4781 do you need me to add the SVG to the code?

**Comment by mallikarai05** [comment]
@Tushar-4781 can you please let me know about this, so we can close this issue

**Comment by Tushar-4781** [comment]
> We can try it out a bit! @Tushar-4781 do you need me to add the SVG to the code?

Not reqd anymore. Will take over from here
