### ISSUE TITLE
Fix Cypress tests based on roadmap

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#880]

**Comment by Tushar-4781** [comment]
Blocked by #691

**Comment by fendermany** [comment]
> Blocked by #883

What is the relationship between these tasks?

**Comment by tijlleenders** [comment]
I think that as long as you don't test the scheduler, sharing or collaboration features ... there is no blockage.

So it's fine to make tests for the onboarding flow and basic adding/editing/archiving/deleting of (sub)Goals.

@Tushar-4781 Can you confirm?
