### ISSUE TITLE
Replace copy with share

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#895]
Copy is not always working and it's not optimal from UX perspective.
 
Cannot consistently reproduce it - but here's an instance of it not working in Chrome. Other times it works fine...
![copy_not_working](https://user-images.githubusercontent.com/44887755/210935705-7bc07fe5-166e-48d7-9fbe-0fad5936d109.gif)

I suggest we replace this with the https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Comment by Tushar-4781** [comment]
@tijlleenders although #908 is resolved, but i like this navigator function.
@tijlleenders @mallikarai05  shall we replace it with our current process i.e. copy the link and raise a toast of "copied to clipboard" ?

**Comment by tijlleenders** [comment]
Yes, from UX perspective the sharing is nicer.

**Comment by Tushar-4781** [comment]
Does not Exist anymore

**Comment by tijlleenders** [comment]
@Tushar-4781 
So this indeed issues mentions some things that are also mentioned in #687 - which is now fixed.
... however, this issue is fundamentally about proposing to replace the 'copy' function with a 'share' function.

This could still be done - although I suspect we'd have to check the runtime to see if the share function is supported - and default back to copy if it is not.
'Share' is usually supported on mobile - but not always on desktop browsers. Also versions might impact?
