### ISSUE TITLE
Design UX for drag and drop

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#900]
How to change order of goals?
How to move goals around in the hierarchy?

**Comment by mallikarai05** [comment]
@tijlleenders I think simply dragging while long pressing on the goal is the simplest way around it

**Comment by tijlleenders** [comment]
Long pressing is quite hard for some people, can we also allow drag by the "circle slice" on the left?

**Comment by tijlleenders** [comment]
... and how to move goals around the hierarchy? Like moving root goal down or moving a deep goal to a different parent?

**Comment by mallikarai05** [comment]
@tijlleenders do we need to make any changes to these screens?

**Comment by tijlleenders** [comment]
Nope, all good!
