### ISSUE TITLE
subGoal sharing not working when using enter to save

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#909]
Add a subgoal right after accepting the invite is not propagated back when using enter to save instead of clicking checkmark button.
![subGoal sharing not working](https://user-images.githubusercontent.com/44887755/211183037-ff5420b6-79fa-4e4b-b4a6-c26d5e606f50.gif)

**Comment by Tushar-4781** [comment]
@tijlleenders the sharing can only start when both users have that two avatars on their respective sides. So in chrome window, you didn't reload & checked the status ( which means looking at the response of the invite ). give me 2 mins lemme prepare a demo

**Comment by tijlleenders** [comment]
Thanks, but I think I'm not explaining myself well. 

It works fine when you use the save button. Then if I add another subgoal that I save using desktop keyboard ENTER key it doesn't propagate. Then if I make a third sublist that I save using save checkmark button (like the first subgoal) it does propagate again.

**Comment by tijlleenders** [comment]
The screen recording is confusing as there are also other issues present.
