### ISSUE TITLE
Add additional color themes for light and dark mode

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#91]
Design three color themes in total for light.
Design three color themes in total for dark.

**Comment by tijlleenders** [comment]
GitHub has these special themes:
![image](https://user-images.githubusercontent.com/44887755/166120683-1e560578-785e-466e-9182-7a51afbccf08.png)

**Comment by mallikarai05** [comment]
I read a few articles and went through some resources for dark UI colors, usually, there is one primary color or 2 for dark UI, in our case, we might need a lot of them. I tried a few shades that went well according to the guidelines and are popular on the dribbble.
![image](https://user-images.githubusercontent.com/73054648/190919758-0ef28d6d-b86a-4676-9647-bfd6d50b2e25.png)

**Comment by tijlleenders** [comment]
This is an issue with the 'low prio' tag.
The backlog is ordered in terms of priority. This is not a priority as long as there are other items above it...

**Comment by tijlleenders** [comment]
These are nice colors @mallikarai05 - but I think this is for issue #586 and #319 ?

Should the font color be black/dark on a dark theme?

**Comment by mallikarai05** [comment]
I added them to the wrong issue...I'm sorry these were meant for issue #499. I will add it there.
Yes, the font can be dark if it is on a primary color.

**Comment by tijlleenders** [comment]
Not a prio - cleaning up the backlog.
