### ISSUE TITLE
Discuss graph structure for goals

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#914]
![20230108_211214_remastered.jpg](https://user-images.githubusercontent.com/44887755/211217125-b1f1d744-7782-4eb8-a906-236f94af255f.jpg)

@Tushar-4781 This requires some explanation and discussion.
Ping me when you can.

**Comment by tijlleenders** [comment]
So just to summarize our discussion this morning:
Basically I'm suggesting to:
1. Simplify the UX by only having a 'share' option - instead of 'share' as well as a similar but different 'collaborate'.
2. Introducing a 'notification object' that gets created once a goal that is received (shared with me) has the same title as a goal that I have in MyGoals. That object will decide if there are any notifications to be done (new collab opportunies, edits, deletes) and stay alive to store the answer to any such questions (like whether this is a collaborative goal or not or whether certain changes need to be propagated to MyGoals). These answers are local - the other party is not involved - so it could be that I see something as a collaborative goal - but you do not. Of course you will see the (non)effect of your changes for my Goals since I'm sharing these back so you can always make a diff between our views of the world.
**This puts the whole collaboration and notification concern out of the schema of MyGoals / GoalsSharedWithMe.**

**Comment by Tushar-4781** [comment]
The conclusion of another meeting is that we should think about the UI design of the new idea for showing collaboration goal. On the top right of the MyGoals page, there is a plus button that currently shows add, hint, and archive. We can add another button to that list that allows users to create collaborative goals, which means that when they press that button, the goal is created based on their input, and the second step is to ask them who they want to invite to this collaboration.

**Comment by tijlleenders** [comment]
@Tushar-4781 Great suggestion. This puts it front and center.

Another way of asking for a collaboration directly could be by creating/editing a goal and adding a contact with "@" - but that's a low prio one.
