### ISSUE TITLE
Icon for collaboration

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#915]
@mallikarai05 Please read #914 as backstory and:
- [x] create an icon, Icon: people hugging or two hands... This will be used in the + menu as alternative to New / Archive / Hint.
Corresponding screens for starting a collaboration:
- [x] Select goal, press share, choose contact => either a link if relationship is not accepted or a share confirmation message.

**Comment by tijlleenders** [comment]
Removed - [ ] how to show collaboration while editing ie tag @contactname showing between the other 'normal' tags? or do we just use the previously designed 'double circle'? from this issue.

**Comment by mallikarai05** [comment]
@tijlleenders I think there is still a lot of thinking required in the case of 'add via + =>select contact => make new goal' 
Can we make a separate issue for it and discuss it there? 
Then we can close this issue!

**Comment by tijlleenders** [comment]
@mallikarai05 Totally agree.

Removed "add via + =>select contact => make new goal (low prio for now => can go to separate issue)" from issue description - but did not make a new issue yet. Let's experiment with the new way of sharing first, then evaluate if we still really need it.
