### ISSUE TITLE
Search for a CICD license checker

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#92]
There must ve some kind of autocheck that checks added npm packages for compatibility with current license.
This issue is to find one that is compatible, not implement it.

**Comment by mallikarai05** [comment]
https://www.npmjs.com/package/license-checker
https://www.npmjs.com/package/license-checker-rseidelsohn

**Comment by tijlleenders** [comment]
Let's go with the fork since there is active dev on that.
