### ISSUE TITLE
Discuss groups/channels

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#930]
Are they anonymous by default?

Should we make exceptions where you can see who voted what?

Should we name it channel or group?

What types of groups/channels? Initial thoughts: 
1. for xx people 
2. [name@org.com](mailto:name@org.com) with email verification 
3. public

What is the simplest one to implement? Start screens for that one and try it out ourselves.

**Comment by tijlleenders** [comment]
@Tushar-4781 @elyessAR @egithinji @mallikarai05 

I guess the easiest one to implement would be the public one where you don't have to ask the initial funder if you can join?
@mallikarai05 Shall we start a design for that - so that we can use the UI design as a guide in the discussions?

**Comment by tijlleenders** [comment]
Just adding initial sketches:

![image](https://user-images.githubusercontent.com/44887755/212293012-fdb92f22-466d-4900-a31f-3d7dfb936e4d.png)

![image](https://user-images.githubusercontent.com/44887755/212293146-7aacdba3-e28a-4133-9af1-66670d1d8f1d.png)

![image](https://user-images.githubusercontent.com/44887755/212293248-053ebb77-db77-4bda-a791-7638de9a4c86.png)

**Comment by elyessAR** [comment]
> Are they anonymous by default?
> 
> Should we make exceptions where you can see who voted what?
> 
> Should we name it channel or group?
> 
> What types of groups/channels? Initial thoughts:
> 
> 1. for xx people
> 2. [name@org.com](mailto:name@org.com) with email verification
> 3. public
> 
> What is the simplest one to implement? Start screens for that one and try it out ourselves.
-I guess if we make it anonymous by default then the voting should be also anonymous, and if we want to go the road where we can see who voted what, we can let them know beforehand.
-channel (although both are convenient) .
-public will be a good way to start.

**Comment by tijlleenders** [comment]
First iteration of design for public group goals is done.
@elyessAR Is implementing this. Once we have a working version we can demo, try it ourselves, and discuss about next steps.

**Comment by tijlleenders** [comment]
#938 
#952

**Comment by tijlleenders** [comment]
We don't need groups when we can share 1:1, 1:n, or pseudo anonymously 1:*.
