### ISSUE TITLE
Simplify + and push hints from backend

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#935]

**Comment by tijlleenders** [comment]
@Tushar-4781 
To simplify the UI (and the onboarding) we could remove hints from the + interface.

Hints could be a feature you turn on automatically by sharing publicly. The "Sharing public" could be renamed "Share public and get hints". This takes care of the consent issue. Hints could then be pushed to your goals via the notification mechanism.

**Comment by tijlleenders** [comment]
@Tushar-4781 suggested to use "Share in group goal". I think that's a great idea!

It solves the fact that you don't have to share the parent (and thus that needs to be OK for the user AND explicitly asked).
User will just search the group goal their own goal contributes to and share. 
Mentally very close to familiar concepts like share in group".

**Comment by tijlleenders** [comment]
@Tushar-4781 Since hints are gone, maybe move the + closer to where we want to add?

![Screenshot-move-plus.jpg](https://user-images.githubusercontent.com/44887755/216781399-5fce716d-9fe9-49f8-affc-af72088762c6.jpg)

This also improves consistency in the header. It feela kind of weird clucking on Goals and then instantly seeing a different + icon in its place...

**Comment by Tushar-4781** [comment]
Doesn't exist anymore
