### ISSUE TITLE
After initial input, keep tags away from input text and edit/delete separately

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#936]
@Tushar-4781 
#507 made us realize that having the tag text editable in the title field is a little confusing when adding new goals.
Also - it obfuscates the title when editing. Right now we work around that by placing the title cursor at the beginning of the input field when editing, but it's not optimal.

A better way would be to have the tags removed from the input field once entered.
After that you can edit/remove them individually by clicking on them. Clicking on 'After 18' tag would for example open a popup where you can modify the after time - or delete the tag. This way the input box has only the title, no "text pollution" from tags.

**Comment by tijlleenders** [comment]
Only relevant if we re-instate the dev-style of entering goals with the cli-parser...

**Comment by Tushar-4781** [comment]
@tijlleenders i think we achieved a better version of showing tags, this can be closed right ?

**Comment by tijlleenders** [comment]
@Tushar-4781 
Yes, the new config modals make this requirement obsolete.  
I still think the tags approach is still very intuitive... Let's keep it in mind for if modals get bloated.
