### ISSUE TITLE
Public group goals API controller

### ISSUE THREAD

**Issue by elyessAR** [tijlleenders/ZinZen#938]
Create the controller for public group goals API based on provided documentation.

**Comment by tijlleenders** [comment]
@elyessAR Please drag the card to 'in progress' once you start working on it ;)

**Comment by elyessAR** [comment]
> @elyessAR have you started working on this ?

yes

**Comment by elyessAR** [comment]
> @elyessAR Please drag the card to 'in progress' once you start working on it ;)

yes, where can I do that @tijlleenders  ?

**Comment by tijlleenders** [comment]
@elyessAR [The project board](https://github.com/users/tijlleenders/projects/2)
