### ISSUE TITLE
Design the new header along with the dark theme

### ISSUE THREAD

**Issue by mallikarai05** [tijlleenders/ZinZen#978]

**Comment by mallikarai05** [comment]
![My Time home dark](https://user-images.githubusercontent.com/73054648/216095316-0b7adaf6-67c6-47f7-aa07-fceeee7e4b13.png)
![My Time Home (1)](https://user-images.githubusercontent.com/73054648/216095324-69e0e17d-dcd5-4cc3-8d3f-355e71b3f2ae.png)

**Comment by mallikarai05** [comment]
@Tushar-4781 Is there anything else you require?

**Comment by Tushar-4781** [comment]
@mallikarai05 why did u name this issue new interface? i m asking because the interface is already implemented. can we re-write as "Design the dark theme of new header"

**Comment by mallikarai05** [comment]
@Tushar-4781 named it so we could keep track of the things I have worked on, I'll change interface to header.

**Comment by Tushar-4781** [comment]
Yup we are good now
