### ISSUE TITLE
Remove MyFeelings from side menu

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#982]

**Comment by tijlleenders** [comment]
... or maybe we should keep it here so the header is less cluttered. The two main pages people will be switching between mostly are in my opinion Time and Goals.

**Comment by Tushar-4781** [comment]
are you sure, some people might want to use it from note taking feature? I think we have to enhance the myfeelings ui

**Comment by tijlleenders** [comment]
@Tushar-4781 
You have a point. Feelings/Notes combined does deserve a place in the top menu!

Please remove from side menu then.

**Comment by Frenzoid** [comment]
Fixed here: https://github.com/tijlleenders/ZinZen/pull/989
