### ISSUE TITLE
Remove extra text on choose theme page

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#99]
After the intro page where user selects language, the theme page should only be about making a choice of themes.
Right now there is extra 'general info' showing that distracts from the intention of the page.
It was already shown on the start page on can be removed on this page.

![image](https://user-images.githubusercontent.com/44887755/156721732-6ae8a0b0-b29e-4cec-b749-deeed6914edf.png)

**Comment by mallikarai05** [comment]
I have to make a few changes to the theme choice page for this, will the desktop view remain the same? We can remove the extra general info for the mobile view.

**Comment by tijlleenders** [comment]
I would remove it on both mobile and web as the information has already
been shown on the previous (initial start) page.

**Comment by tijlleenders** [comment]
Also easier to keep the objects shown on web and mobile identical for now.
We're developing mobile-first. We don't need the distraction of a different layout/UI elements for web at this point.

**Comment by mallikarai05** [comment]
Okay so will removing both the text and the book and then moving the theme choice to the center work?
