### ISSUE TITLE
Whole MyTime card should respond to tap and collapse again if tapped 2nd time

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#994]
The tap are of cards on MyTime should be like so:
![Screenshot_tap-area.jpg](https://user-images.githubusercontent.com/44887755/216833334-217ef4f5-6021-48a1-a806-eceb6b266f21.jpg)

In first tap - buttons forget / reschedule / done should show.

If tapped again (not on buttons) card should collapse again.

**Comment by kp30-bit** [comment]
I'll take this up

**Comment by tijlleenders** [comment]
Great news, thanks @kp30-bit !

**Comment by Tushar-4781** [comment]
@kp30-bit is this still in progress?

**Comment by Tushar-4781** [comment]
let's have a drop-down that will be visible only if you uncollapse the task. Clean, simple and direct

**Comment by kp30-bit** [comment]
Hey i am sorry. I am unable to run the program on my system for some reason. I am Unable to make the changes.

**Comment by tijlleenders** [comment]
@kp30-bit No worries!

We could improve our developerExperience a bit by providing a .devcontainer

Just curious : if you can provide us with some details about your system and error message  - so we can improve the devEx for others...?
